local v0, v1 = ...;
local v2 = HeroRotation();
local v3 = HeroLib;
local v4 = v3.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v2.HRGUIGet().CreateARPanelOption;
local v8 = v2.HRGUIGet().CreateARPanelOptions;
local v9 = v4.GetPanelByName("Interrupt");
local v10 = v2.GUISettingsGet();
v10.APL.Warrior = {Commons={CCIncorperal=false,AutoSpellreflection=true,BattleShout="only check us",Enabled={Potions=true,Trinkets=true,Items=true},DisplayStyle={Potions="Suggested",Signature="Suggested",Trinkets="Suggested",Charge="Suggested",HeroicLeap="Suggested"}},Arms={AttackonlyinCombat=false,AutoExecute=false,Defensives={VictoryRushHP=(250 - 170),ImpendingVictoryHP=(171 - 111),DiebytheSwordHP=(19 - 9),BitterImmunityHP=(0 - 0),IgnorePainHP=(619 - (555 + 64)),DefStanceHP=(931 - (857 + 74)),BattleStanceHP=(568 - (367 + 201)),IgnorePainUse="Not Used",IgnorePainEnemycount=(932 - (214 + 713))},PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"}},Arms_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=false,AutoTargetStun=false,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(16 + 44),InterruptPercentChannel=(10 + 50),UseStormbolt=true,UseShockwave=true}},Arms_TTD={RacialsTTD=(897 - (282 + 595)),TrinketsTTD=(1657 - (1523 + 114)),ChampionsSpearTTD=(9 + 1),DemolishTTD=(14 - 4),AvatarTTD=(1085 - (68 + 997)),BladestormTTD=(1280 - (226 + 1044)),ColossusSmashTTD=(65 - 50),ThunderousRoarTTD=(133 - (32 + 85)),PotionsTTD=(20 + 0),WeaponTTD=(3 + 7),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Arms_CDUSE={smallcdswithCooldowns=true,Enemycount=(962 - (892 + 65)),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",Avatar="with Cooldowns",ColossusSmash="with Cooldowns",Warbreaker="with Cooldowns",ThunderousRoar="with Cooldowns",ChampionsSpear="with Cooldowns",Bladestorm="with Cooldowns",Demolish="with Cooldowns",Weapon="with Cooldowns"},Fury={AttackonlyinCombat=false,Defensives={VictoryRushHP=(190 - 110),ImpendingVictoryHP=(110 - 50),EnragedRegenerationHP=(91 - 41),BitterImmunityHP=(350 - (87 + 263)),DefStanceHP=(180 - (67 + 113)),BerserkerStanceHP=(0 + 0)},PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"}},Fury_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=false,AutoTargetStun=false,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(147 - 87),InterruptPercentChannel=(45 + 15),UseStormbolt=true,UseShockwave=true}},Fury_TTD={RacialsTTD=(79 - 59),TrinketsTTD=(972 - (802 + 150)),ChampionsSpearTTD=(26 - 16),AvatarTTD=(36 - 16),RecklessnessTTD=(11 + 4),RavagerTTD=(1012 - (915 + 82)),OdynsFuryTTD=(28 - 18),ThunderousRoarTTD=(10 + 6),PotionsTTD=(26 - 6),WeaponTTD=(1197 - (1069 + 118)),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Fury_CDUSE={smallcdswithCooldowns=true,Enemycount=(10 - 5),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",Avatar="with Cooldowns",Recklessness="with Cooldowns",ThunderousRoar="with Cooldowns",ChampionsSpear="with Cooldowns",Ravager="with Cooldowns",OdynsFury="with Cooldowns",Weapon="with Cooldowns"},Protection={AllowIPOvercap=false,RageCapValue=(174 - 94),AttackonlyinCombat=false,UseShieldCharge=true,Stance="Battle Stance",Defensives={VictoryRushHP=(14 + 66),ImpendingVictoryHP=(106 - 46),BitterImmunityHP=(0 + 0),IgnorePainHP=(891 - (368 + 423)),ShieldWallHP=(62 - 42),LastStandHP=(28 - (10 + 8)),ShieldBlockHP=(365 - 270),DefStanceHP=(442 - (416 + 26)),BattleStanceHP=(0 - 0)},PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},DisplayStyle={Defensive="Suggested"}},Protection_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=false,AutoTargetStun=false,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(26 + 34),InterruptPercentChannel=(106 - 46),UseStormbolt=true,UseShockwave=true}},Protection_TTD={RacialsTTD=(458 - (145 + 293)),TrinketsTTD=(450 - (44 + 386)),ChampionsSpearTTD=(1496 - (998 + 488)),AvatarTTD=(7 + 13),ThunderousRoarTTD=(14 + 2),RavagerTTD=(787 - (201 + 571)),PotionsTTD=(1158 - (116 + 1022)),DemolishTTD=(41 - 31),DemoralizingShoutTTD=(6 + 4),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Protection_CDUSE={smallcdswithCooldowns=true,Enemycount=(18 - 13),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",Avatar="with Cooldowns",ThunderousRoar="with Cooldowns",ChampionsSpear="with Cooldowns",Ravager="with Cooldowns",Demolish="with Cooldowns",DemoralizingShout="small CDs",LastStand="Not Used",ShieldWall="Not Used"}};
v2.HRGUIGet().LoadSettingsRecursively(v10);
local v12 = v2.HRGUIGet().Panel;
local v13 = v5(v12, "Warrior");
local v14 = {"Not Used","always","with Cooldowns","small CDs","with Cooldowns or AoE","on Enemycount or Cooldowns","on Boss or with Cooldowns","on Boss only","with Bloodlust only","on AOE","on Enemycount","on Boss or on Enemycount"};
local v15 = {"Not Used","on HP","on Enemycount","on Enemycount and HP"};
local v16 = v5(v13, "Arms");
local v17 = v5(v16, "Defensives");
local v18 = v5(v16, "Interrupt");
local v19 = v5(v16, "TTD");
local v20 = v5(v16, "Cooldown settings");
local v21 = v5(v13, "Fury");
local v22 = v5(v21, "Defensives");
local v23 = v5(v21, "Interrupt");
local v24 = v5(v21, "TTD");
local v25 = v5(v21, "Cooldown settings");
local v26 = v5(v13, "Protection");
local v27 = v5(v26, "Defensives");
local v28 = v5(v26, "Interrupt");
local v29 = v5(v26, "TTD");
local v30 = v5(v26, "Cooldown settings");
v8(v13, "APL.Warrior.Commons");
v6("CheckButton", v13, "APL.Warrior.Commons.CCIncorperal", "CC Incoperal", "Enable this if you want the addon to CC Incoperal with Storm Bolt and Intimidating Shout - be aware that both are not long enough to handle this affix.");
v6("CheckButton", v13, "APL.Warrior.Commons.AutoSpellreflection", "Auto Spell Reflection", "Enable this if you want the addon to Auto Spell Reflection.");
v6("Dropdown", v13, "APL.Warrior.Commons.BattleShout", {"dont use","only check us","check whole group"}, "Battle Shout", "Decide if we want to use Battle Shout and who to check for the Buff.");
v6("CheckButton", v16, "APL.Warrior.Arms.AutoExecute", "Auto Tab for Execute", "Enable this if you want the addon to auto Tab for Execute.");
v6("CheckButton", v16, "APL.Warrior.Arms.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v8(v16, "APL.Warrior.Arms");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.VictoryRushHP", {(0 + 0),(440 - 340),(2 - 1)}, "Victory Rush HP", "Set the Victory Rush HP threshold. Set to 0 to disable.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.ImpendingVictoryHP", {(0 - 0),(801 - (376 + 325)),(2 - 1)}, "Impending Victory HP", "Set the Impending Victory HP threshold. Set to 0 to disable.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.DiebytheSwordHP", {(0 - 0),(476 - (85 + 291)),(3 - 2)}, "Die by the Sword HP", "Set the Die by the Sword HP threshold. Set to 0 to disable.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.BitterImmunityHP", {(1180 - (1123 + 57)),(354 - (163 + 91)),(1 + 0)}, "Bitter Immunity HP", "Set the Bitter Immunity HP threshold. Set to 0 to disable.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.IgnorePainHP", {(0 - 0),(137 - 37),(1475 - (1329 + 145))}, "Ignore Pain HP", "Set the IgnorePain HP threshold. Set to 0 to disable.");
v6("Dropdown", v17, "APL.Warrior.Arms.Defensives.IgnorePainUse", v15, "Ignore Pain use", "Set when to use Ignore Pain.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.IgnorePainEnemycount", {(1852 - (1409 + 441)),(5 + 5),(1722 - (345 + 1376))}, "Ignore Pain Enemycount", "How many Enemys we need in range to use Ignore Pain.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.DefStanceHP", {(0 - 0),(1306 - (696 + 510)),(1263 - (1091 + 171))}, "Defensive Stance HP", "Set the HP percentage threshold of when you want the addon to suggest Defensive Stance. (Set to 0 to disable)");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.BattleStanceHP", {(0 - 0),(474 - (123 + 251)),(699 - (208 + 490))}, "Battle Stance HP", "Set the HP percentage threshold of when you want the addon to get back Battle Stance. (Set to 0 to disable)");
v8(v17, "APL.Warrior.Arms.Defensives");
v6("CheckButton", v19, "APL.Warrior.Arms_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v19, "APL.Warrior.Arms_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v19, "APL.Warrior.Arms_TTD.RacialsTTD", {(0 + 0),(8 + 52),(676 - (534 + 141))}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v19, "APL.Warrior.Arms_TTD.TrinketsTTD", {(0 + 0),(126 - 66),(2 - 1)}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v19, "APL.Warrior.Arms_TTD.ChampionsSpearTTD", {(0 + 0),(139 - 79),(2 - 1)}, "Champions Spear TTD", "Time to die to use Champions Spear");
v6("Slider", v19, "APL.Warrior.Arms_TTD.DemolishTTD", {(867 - (550 + 317)),(84 - 24),(286 - (134 + 151))}, "Demolish TTD", "Time to die to use Demolish");
v6("Slider", v19, "APL.Warrior.Arms_TTD.AvatarTTD", {(0 - 0),(208 - 148),(3 - 2)}, "Avatar TTD", "Time to die to use Avatar");
v6("Slider", v19, "APL.Warrior.Arms_TTD.BladestormTTD", {(0 - 0),(840 - (162 + 618)),(1 + 0)}, "Bladestorm/Ravager TTD", "Time to die to use Bladestorm/Ravager");
v6("Slider", v19, "APL.Warrior.Arms_TTD.ColossusSmashTTD", {(0 - 0),(1696 - (1373 + 263)),(1 + 0)}, "Colossus Smash/Warbreaker TTD", "Time to die to use Colossus Smash/Warbreaker");
v6("Slider", v19, "APL.Warrior.Arms_TTD.ThunderousRoarTTD", {(0 - 0),(23 + 37),(342 - (218 + 123))}, "Thunderous Roar TTD", "Time to die to use Thunderous Roar");
v6("Slider", v19, "APL.Warrior.Arms_TTD.PotionsTTD", {(0 + 0),(620 - (306 + 254)),(1 - 0)}, "Potions TTD", "Time to die to use DPS Potions");
v6("Slider", v19, "APL.Warrior.Arms_TTD.WeaponTTD", {(0 + 0),(663 - (268 + 335)),(573 - (426 + 146))}, "Weapon TTD", "Time to die to use Weapon");
v8(v19, "APL.Warrior.Arms_TTD");
v6("CheckButton", v20, "APL.Warrior.Arms_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v20, "APL.Warrior.Arms_CDUSE.Enemycount", {(1458 - (282 + 1174)),(28 - 18),(1025 - (706 + 318))}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Racials", v14, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Potions", v14, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v20, "APL.Warrior.Arms_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Trinket1", v14, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Trinket2", v14, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Avatar", v14, "Avatar", "Choose an option on when to use Avatar");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.ColossusSmash", v14, "Colossus Smash", "Choose an option on when to use Colossus Smash");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Warbreaker", v14, "Warbreaker", "Choose an option on when to use Warbreaker");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.ThunderousRoar", v14, "Thunderous Roar", "Choose an option on when to use Thunderous Roar");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.ChampionsSpear", v14, "Champions Spear", "Choose an option on when to use Champions Spear");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Demolish", v14, "Demolish", "Choose an option on when to use Demolish");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Bladestorm", v14, "Bladestorm/Ravager", "Choose an option on when to use Bladestorm/Ravager");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Weapon", v14, "Weapon", "Choose an option on when to use Weapon");
v8(v20, "APL.Warrior.Arms_CDUSE");
v6("CheckButton", v18, "APL.Warrior.Arms_Interrupt.Interrupt.UseStormbolt", "Use Stormbolt", "Enable this if you want the addon to use Stormbolt.");
v6("CheckButton", v18, "APL.Warrior.Arms_Interrupt.Interrupt.UseShockwave", "Use Shockwave", "Enable this if you want the addon to use Shockwave.");
v8(v18, "APL.Warrior.Arms_Interrupt");
v6("CheckButton", v21, "APL.Warrior.Fury.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v8(v21, "APL.Warrior.Fury");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.VictoryRushHP", {(1271 - (945 + 326)),(89 + 11),(1 + 0)}, "Victory Rush HP", "Set the Victory Rush HP threshold. Set to 0 to disable.");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.ImpendingVictoryHP", {(1086 - (461 + 625)),(6 + 94),(1 + 0)}, "Impending Victory HP", "Set the Impending Victory HP threshold. Set to 0 to disable.");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.EnragedRegenerationHP", {(0 + 0),(629 - (406 + 123)),(1 + 0)}, "Enraged Regeneration HP", "Set the Enraged Regeneration HP threshold. Set to 0 to disable.");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.BitterImmunityHP", {(0 + 0),(240 - 140),(1901 - (106 + 1794))}, "Bitter Immunity HP", "Set the Bitter Immunity HP threshold. Set to 0 to disable.");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.DefStanceHP", {(0 + 0),(270 - 170),(585 - (57 + 527))}, "Defensive Stance HP", "Set the HP percentage threshold of when you want the addon to suggest Defensive Stance. (Set to 0 to disable)");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.BerserkerStanceHP", {(103 - (17 + 86)),(223 - 123),(167 - (122 + 44))}, "Berserker Stance HP", "Set the HP percentage threshold of when you want the addon to get back Berserker Stance. (Set to 0 to disable)");
v8(v22, "APL.Warrior.Fury.Defensives");
v6("CheckButton", v24, "APL.Warrior.Fury_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v24, "APL.Warrior.Fury_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v24, "APL.Warrior.Fury_TTD.RacialsTTD", {(0 - 0),(9 + 51),(66 - (30 + 35))}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v24, "APL.Warrior.Fury_TTD.TrinketsTTD", {(1257 - (1043 + 214)),(1272 - (323 + 889)),(581 - (361 + 219))}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v24, "APL.Warrior.Fury_TTD.ChampionsSpearTTD", {(0 + 0),(1042 - (18 + 964)),(1 + 0)}, "Champions Spear TTD", "Time to die to use Champions Spear");
v6("Slider", v24, "APL.Warrior.Fury_TTD.AvatarTTD", {(850 - (20 + 830)),(186 - (116 + 10)),(739 - (542 + 196))}, "Avatar TTD", "Time to die to use Avatar");
v6("Slider", v24, "APL.Warrior.Fury_TTD.RecklessnessTTD", {(0 + 0),(22 + 38),(2 - 1)}, "Recklessness TTD", "Time to die to use Recklessness");
v6("Slider", v24, "APL.Warrior.Fury_TTD.RavagerTTD", {(405 - (118 + 287)),(1181 - (118 + 1003)),(378 - (142 + 235))}, "Ravager/Bladestorm TTD", "Time to die to use Ravager/Bladestorm");
v6("Slider", v24, "APL.Warrior.Fury_TTD.OdynsFuryTTD", {(0 + 0),(113 - 53),(1 + 0)}, "OdynsFury TTD", "Time to die to use OdynsFury");
v6("Slider", v24, "APL.Warrior.Fury_TTD.ThunderousRoarTTD", {(0 + 0),(130 - 70),(2 - 1)}, "Thunderous Roar TTD", "Time to die to use Thunderous Roar");
v6("Slider", v24, "APL.Warrior.Fury_TTD.PotionsTTD", {(0 - 0),(22 + 38),(1 + 0)}, "Potions TTD", "Time to die to use DPS Potions");
v6("Slider", v24, "APL.Warrior.Fury_TTD.WeaponTTD", {(0 - 0),(791 - (476 + 255)),(1 + 0)}, "Weapon TTD", "Time to die to use Weapon");
v8(v24, "APL.Warrior.Fury_TTD");
v6("CheckButton", v25, "APL.Warrior.Fury_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v25, "APL.Warrior.Fury_CDUSE.Enemycount", {(3 - 1),(2 + 8),(337 - (144 + 192))}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Racials", v14, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Potions", v14, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v25, "APL.Warrior.Fury_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Trinket1", v14, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Trinket2", v14, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Avatar", v14, "Avatar", "Choose an option on when to use Avatar");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Recklessness", v14, "Recklessness", "Choose an option on when to use Recklessness");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Ravager", v14, "Ravager/Bladestorm", "Choose an option on when to use Ravager/Bladestorm");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.ThunderousRoar", v14, "Thunderous Roar", "Choose an option on when to use Thunderous Roar");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.ChampionsSpear", v14, "Champions Spear", "Choose an option on when to use Champions Spear");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.OdynsFury", v14, "Odyns Fury", "Choose an option on when to use Odyns Fury");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Weapon", v14, "Weapon", "Choose an option on when to use Weapon");
v8(v25, "APL.Warrior.Fury_CDUSE");
v6("CheckButton", v23, "APL.Warrior.Fury_Interrupt.Interrupt.UseStormbolt", "Use Stormbolt", "Enable this if you want the addon to use Stormbolt.");
v6("CheckButton", v23, "APL.Warrior.Fury_Interrupt.Interrupt.UseShockwave", "Use Shockwave", "Enable this if you want the addon to use Shockwave.");
v8(v23, "APL.Warrior.Fury_Interrupt");
v6("Slider", v26, "APL.Warrior.Protection.RageCapValue", {(23 + 7),(43 + 57),(1585 - (1183 + 397))}, "Rage Cap Value", "Set the highest amount of Rage we should allow to pool before dumping Rage with Ignore Pain. Setting this value to 30 will allow you to over-cap Rage.");
v6("CheckButton", v26, "APL.Warrior.Protection.AllowIPOvercap", "Allow Ignore Pain Overcap", "Enable this option to allow Ignore Pain to be suggested, even when it would push the absorb over its maximum absorb value.");
v6("CheckButton", v26, "APL.Warrior.Protection.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v6("CheckButton", v26, "APL.Warrior.Protection.UseShieldCharge", "Use Shield Charge in melee", "Enable this if you want the addon to suggest Shiled Charge in melee.");
v6("Dropdown", v26, "APL.Warrior.Protection.Stance", {"No Stance","Battle Stance","Defensive Stance"}, "Which stance do we want", "Choose which Stance to use.");
v8(v26, "APL.Warrior.Protection");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.VictoryRushHP", {(0 + 0),(2033 - (565 + 1368)),(1662 - (1477 + 184))}, "Victory Rush HP", "Set the Victory Rush HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.ImpendingVictoryHP", {(0 + 0),(172 - 72),(305 - (244 + 60))}, "Impending Victory HP", "Set the Impending Victory HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.BitterImmunityHP", {(476 - (41 + 435)),(77 + 23),(1 + 0)}, "Bitter Immunity HP", "Set the Bitter Immunity HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.IgnorePainHP", {(0 + 0),(367 - (176 + 91)),(1 - 0)}, "Ignore Pain HP", "Set the IgnorePain HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.ShieldWallHP", {(1875 - (157 + 1718)),(354 - 254),(1019 - (697 + 321))}, "Shield Wall HP", "Set the Shield Wall HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.LastStandHP", {(0 - 0),(39 + 61),(2 - 1)}, "Last Stand HP", "Set the Last Stand HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.ShieldBlockHP", {(611 - (602 + 9)),(972 - (826 + 46)),(3 - 2)}, "Shield Block HP", "Set the Shield Block HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.DefStanceHP", {(1898 - (260 + 1638)),(320 - 220),(1 - 0)}, "Defensive Stance HP", "Set the HP percentage threshold of when you want the addon to suggest Defensive Stance. (Set to 0 to disable)");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.BattleStanceHP", {(1205 - (902 + 303)),(240 - 140),(1691 - (1121 + 569))}, "Battle Stance HP", "Set the HP percentage threshold of when you want the addon to get back Battle Stance. (Set to 0 to disable)");
v8(v27, "APL.Warrior.Arms.Defensives");
v6("CheckButton", v29, "APL.Warrior.Protection_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v29, "APL.Warrior.Protection_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v29, "APL.Warrior.Protection_TTD.RacialsTTD", {(683 - (483 + 200)),(164 - 104),(766 - (468 + 297))}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v29, "APL.Warrior.Protection_TTD.TrinketsTTD", {(0 - 0),(108 - 48),(237 - (141 + 95))}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v29, "APL.Warrior.Protection_TTD.ChampionsSpearTTD", {(0 - 0),(15 + 45),(1 + 0)}, "Champions Spear TTD", "Time to die to use Champions Spear");
v6("Slider", v29, "APL.Warrior.Protection_TTD.AvatarTTD", {(0 - 0),(223 - (92 + 71)),(1 - 0)}, "Avatar TTD", "Time to die to use Avatar");
v6("Slider", v29, "APL.Warrior.Protection_TTD.ThunderousRoarTTD", {(0 + 0),(31 + 29),(127 - (55 + 71))}, "Thunderous Roar TTD", "Time to die to use Thunderous Roar");
v6("Slider", v29, "APL.Warrior.Protection_TTD.RavagerTTD", {(1790 - (573 + 1217)),(5 + 55),(940 - (714 + 225))}, "Ravager TTD", "Time to die to use Ravager");
v6("Slider", v29, "APL.Warrior.Protection_TTD.PotionsTTD", {(0 - 0),(86 - 26),(49 - (25 + 23))}, "Potions TTD", "Time to die to use DPS Potions");
v6("Slider", v29, "APL.Warrior.Protection_TTD.DemolishTTD", {(1886 - (927 + 959)),(792 - (16 + 716)),(98 - (11 + 86))}, "Demolish TTD", "Time to die to use Demolish");
v6("Slider", v29, "APL.Warrior.Protection_TTD.DemoralizingShoutTTD", {(285 - (175 + 110)),(295 - 235),(2 - 1)}, "Demoralizing Shout TTD", "Time to die to use Demoralizing Shout");
v8(v29, "APL.Warrior.Protection_TTD");
v6("CheckButton", v30, "APL.Warrior.Protection_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v30, "APL.Warrior.Protection_CDUSE.Enemycount", {(1063 - (810 + 251)),(4 + 6),(534 - (43 + 490))}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Racials", v14, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Potions", v14, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v30, "APL.Warrior.Protection_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Trinket1", v14, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Trinket2", v14, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Avatar", v14, "Avatar", "Choose an option on when to use Avatar");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Ravager", v14, "Ravager", "Choose an option on when to use Ravager");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.ThunderousRoar", v14, "Thunderous Roar", "Choose an option on when to use Thunderous Roar");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.ChampionsSpear", v14, "Champions Spear", "Choose an option on when to use Champions Spear");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.DemoralizingShout", v14, "Demoralizing Shout", "Choose an option on when to use Demoralizing Shout");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Demolish", v14, "Demolish", "Choose an option on when to use Demolish");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.LastStand", v14, "Last Stand", "Choose an option on when to use Last Stand aggressively ignoreing the defensive use");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.ShieldWall", v14, "Shield Wall", "Choose an option on when to use Shield Wall aggressively ignoreing the defensive use");
v8(v30, "APL.Warrior.Protection_CDUSE");
v6("CheckButton", v28, "APL.Warrior.Protection_Interrupt.Interrupt.UseStormbolt", "Use Stormbolt", "Enable this if you want the addon to use Stormbolt.");
v6("CheckButton", v28, "APL.Warrior.Protection_Interrupt.Interrupt.UseShockwave", "Use Shockwave", "Enable this if you want the addon to use Shockwave.");
v8(v28, "APL.Warrior.Protection_Interrupt");
v10.APL.Warrior.Arms.Display = function()
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v9);
	v3.GUI.ShowPanel(v16);
	v3.GUI.ShowPanel(v17);
	v3.GUI.ShowPanel(v18);
	v3.GUI.ShowPanel(v19);
	v3.GUI.ShowPanel(v20);
end;
v10.APL.Warrior.Fury.Display = function()
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v9);
	v3.GUI.ShowPanel(v21);
	v3.GUI.ShowPanel(v22);
	v3.GUI.ShowPanel(v23);
	v3.GUI.ShowPanel(v24);
	v3.GUI.ShowPanel(v25);
end;
v10.APL.Warrior.Protection.Display = function()
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v9);
	v3.GUI.ShowPanel(v26);
	v3.GUI.ShowPanel(v27);
	v3.GUI.ShowPanel(v28);
	v3.GUI.ShowPanel(v29);
	v3.GUI.ShowPanel(v30);
end;
