local v0, v1 = ...;
local v2 = HeroRotation();
local v3 = HeroLib;
local v4 = v3.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v2.HRGUIGet().CreateARPanelOption;
local v8 = v2.HRGUIGet().CreateARPanelOptions;
local v9 = v4.GetPanelByName("Interrupt");
local v10 = v2.GUISettingsGet();
v10.APL.Warrior = {Commons={CCIncorperal=false,AutoSpellreflection=true,BattleShout="only check us",Enabled={Potions=true,Trinkets=true,Items=true},DisplayStyle={Potions="Suggested",Signature="Suggested",Trinkets="Suggested",Charge="Suggested",HeroicLeap="Suggested"}},Arms={AttackonlyinCombat=false,AutoExecute=false,Defensives={VictoryRushHP=(250 - 170),ImpendingVictoryHP=(171 - 111),DiebytheSwordHP=(19 - 9),BitterImmunityHP=(0 - 0),IgnorePainHP=(619 - (555 + 64)),DefStanceHP=(931 - (857 + 74)),BattleStanceHP=(568 - (367 + 201)),IgnorePainUse="Not Used",IgnorePainEnemycount=(932 - (214 + 713))},PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"}},Arms_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(16 + 44),InterruptPercentChannel=(10 + 50),UseStormbolt=true,UseShockwave=true}},Arms_TTD={RacialsTTD=(897 - (282 + 595)),TrinketsTTD=(1657 - (1523 + 114)),ChampionsSpearTTD=(9 + 1),DemolishTTD=(14 - 4),AvatarTTD=(1085 - (68 + 997)),BladestormTTD=(1280 - (226 + 1044)),ColossusSmashTTD=(65 - 50),ThunderousRoarTTD=(133 - (32 + 85)),PotionsTTD=(20 + 0),WeaponTTD=(3 + 7),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Arms_CDUSE={smallcdswithCooldowns=true,Enemycount=(962 - (892 + 65)),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",Avatar="with Cooldowns",ColossusSmash="with Cooldowns",Warbreaker="with Cooldowns",ThunderousRoar="with Cooldowns",ChampionsSpear="with Cooldowns",Bladestorm="with Cooldowns",Demolish="with Cooldowns",Weapon="with Cooldowns"},Fury={AttackonlyinCombat=false,Defensives={VictoryRushHP=(190 - 110),ImpendingVictoryHP=(110 - 50),EnragedRegenerationHP=(91 - 41),BitterImmunityHP=(350 - (87 + 263)),DefStanceHP=(180 - (67 + 113)),BerserkerStanceHP=(0 + 0)},PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"}},Fury_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(147 - 87),InterruptPercentChannel=(45 + 15),UseStormbolt=true,UseShockwave=true}},Fury_TTD={RacialsTTD=(79 - 59),TrinketsTTD=(972 - (802 + 150)),ChampionsSpearTTD=(26 - 16),AvatarTTD=(36 - 16),RecklessnessTTD=(11 + 4),RavagerTTD=(1012 - (915 + 82)),OdynsFuryTTD=(28 - 18),ThunderousRoarTTD=(10 + 6),PotionsTTD=(26 - 6),WeaponTTD=(1197 - (1069 + 118)),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Fury_CDUSE={smallcdswithCooldowns=true,Enemycount=(10 - 5),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",Avatar="with Cooldowns",Recklessness="with Cooldowns",ThunderousRoar="with Cooldowns",ChampionsSpear="with Cooldowns",Ravager="with Cooldowns",OdynsFury="with Cooldowns",Weapon="with Cooldowns"},Protection={AllowIPOvercap=false,RageCapValue=(174 - 94),AttackonlyinCombat=false,UseShieldCharge=true,Stance="Battle Stance",Defensives={VictoryRushHP=(14 + 66),ImpendingVictoryHP=(106 - 46),BitterImmunityHP=(0 + 0),IgnorePainHP=(891 - (368 + 423)),ShieldWallHP=(62 - 42),LastStandHP=(28 - (10 + 8)),ShieldBlockHP=(365 - 270),DefStanceHP=(442 - (416 + 26)),BattleStanceHP=(0 - 0),RallyingCryHP=(13 + 17)},PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},DisplayStyle={Defensive="Suggested"}},Protection_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(106 - 46),InterruptPercentChannel=(498 - (145 + 293)),UseStormbolt=true,UseShockwave=true}},Protection_TTD={RacialsTTD=(450 - (44 + 386)),TrinketsTTD=(1506 - (998 + 488)),ChampionsSpearTTD=(4 + 6),AvatarTTD=(17 + 3),ThunderousRoarTTD=(788 - (201 + 571)),RavagerTTD=(1153 - (116 + 1022)),PotionsTTD=(83 - 63),DemolishTTD=(6 + 4),DemoralizingShoutTTD=(36 - 26),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Protection_CDUSE={smallcdswithCooldowns=true,Enemycount=(17 - 12),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",Avatar="with Cooldowns",ThunderousRoar="with Cooldowns",ChampionsSpear="with Cooldowns",Ravager="with Cooldowns",Demolish="with Cooldowns",DemoralizingShout="small CDs",LastStand="Not Used",ShieldWall="Not Used"}};
v2.HRGUIGet().LoadSettingsRecursively(v10);
local v12 = v2.HRGUIGet().Panel;
local v13 = v5(v12, "Warrior");
local v14 = {"Not Used","always","with Cooldowns","small CDs","with Cooldowns or AoE","on Enemycount or Cooldowns","on Boss or with Cooldowns","on Boss only","with Bloodlust only","on AOE","on Enemycount","on Boss or on Enemycount"};
local v15 = {"Not Used","on HP","on Enemycount","on Enemycount and HP"};
local v16 = v5(v13, "Arms");
local v17 = v5(v16, "Defensives");
local v18 = v5(v16, "Interrupt");
local v19 = v5(v16, "TTD");
local v20 = v5(v16, "Cooldown settings");
local v21 = v5(v13, "Fury");
local v22 = v5(v21, "Defensives");
local v23 = v5(v21, "Interrupt");
local v24 = v5(v21, "TTD");
local v25 = v5(v21, "Cooldown settings");
local v26 = v5(v13, "Protection");
local v27 = v5(v26, "Defensives");
local v28 = v5(v26, "Interrupt");
local v29 = v5(v26, "TTD");
local v30 = v5(v26, "Cooldown settings");
v8(v13, "APL.Warrior.Commons");
v6("CheckButton", v13, "APL.Warrior.Commons.CCIncorperal", "CC Incoperal", "Enable this if you want the addon to CC Incoperal with Storm Bolt and Intimidating Shout - be aware that both are not long enough to handle this affix.");
v6("CheckButton", v13, "APL.Warrior.Commons.AutoSpellreflection", "Auto Spell Reflection", "Enable this if you want the addon to Auto Spell Reflection.");
v6("Dropdown", v13, "APL.Warrior.Commons.BattleShout", {"dont use","only check us","check whole group"}, "Battle Shout", "Decide if we want to use Battle Shout and who to check for the Buff.");
v6("CheckButton", v16, "APL.Warrior.Arms.AutoExecute", "Auto Tab for Execute", "Enable this if you want the addon to auto Tab for Execute.");
v6("CheckButton", v16, "APL.Warrior.Arms.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v8(v16, "APL.Warrior.Arms");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.VictoryRushHP", {(1055 - (87 + 968)),(91 + 9),(1414 - (447 + 966))}, "Victory Rush HP", "Set the Victory Rush HP threshold. Set to 0 to disable.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.ImpendingVictoryHP", {(1817 - (1703 + 114)),(163 - 63),(1 + 0)}, "Impending Victory HP", "Set the Impending Victory HP threshold. Set to 0 to disable.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.DiebytheSwordHP", {(14 - (9 + 5)),(1365 - (243 + 1022)),(1 + 0)}, "Die by the Sword HP", "Set the Die by the Sword HP threshold. Set to 0 to disable.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.BitterImmunityHP", {(0 + 0),(2030 - (1869 + 61)),(3 - 2)}, "Bitter Immunity HP", "Set the Bitter Immunity HP threshold. Set to 0 to disable.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.IgnorePainHP", {(0 + 0),(94 + 6),(972 - (140 + 831))}, "Ignore Pain HP", "Set the IgnorePain HP threshold. Set to 0 to disable.");
v6("Dropdown", v17, "APL.Warrior.Arms.Defensives.IgnorePainUse", v15, "Ignore Pain use", "Set when to use Ignore Pain.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.IgnorePainEnemycount", {(720 - (15 + 703)),(448 - (262 + 176)),(689 - (198 + 490))}, "Ignore Pain Enemycount", "How many Enemys we need in range to use Ignore Pain.");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.DefStanceHP", {(0 - 0),(209 - 109),(1 + 0)}, "Defensive Stance HP", "Set the HP percentage threshold of when you want the addon to suggest Defensive Stance. (Set to 0 to disable)");
v6("Slider", v17, "APL.Warrior.Arms.Defensives.BattleStanceHP", {(0 - 0),(496 - 396),(1 + 0)}, "Battle Stance HP", "Set the HP percentage threshold of when you want the addon to get back Battle Stance. (Set to 0 to disable)");
v8(v17, "APL.Warrior.Arms.Defensives");
v6("CheckButton", v19, "APL.Warrior.Arms_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v19, "APL.Warrior.Arms_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v19, "APL.Warrior.Arms_TTD.RacialsTTD", {(836 - (660 + 176)),(262 - (14 + 188)),(1 + 0)}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v19, "APL.Warrior.Arms_TTD.TrinketsTTD", {(0 + 0),(95 - 35),(1 + 0)}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v19, "APL.Warrior.Arms_TTD.ChampionsSpearTTD", {(396 - (115 + 281)),(50 + 10),(3 - 2)}, "Champions Spear TTD", "Time to die to use Champions Spear");
v6("Slider", v19, "APL.Warrior.Arms_TTD.DemolishTTD", {(0 - 0),(167 - 107),(1666 - (970 + 695))}, "Demolish TTD", "Time to die to use Demolish");
v6("Slider", v19, "APL.Warrior.Arms_TTD.AvatarTTD", {(1990 - (582 + 1408)),(75 - 15),(1825 - (1195 + 629))}, "Avatar TTD", "Time to die to use Avatar");
v6("Slider", v19, "APL.Warrior.Arms_TTD.BladestormTTD", {(241 - (187 + 54)),(43 + 17),(1 - 0)}, "Bladestorm/Ravager TTD", "Time to die to use Bladestorm/Ravager");
v6("Slider", v19, "APL.Warrior.Arms_TTD.ColossusSmashTTD", {(0 + 0),(1060 - (451 + 549)),(1 - 0)}, "Colossus Smash/Warbreaker TTD", "Time to die to use Colossus Smash/Warbreaker");
v6("Slider", v19, "APL.Warrior.Arms_TTD.ThunderousRoarTTD", {(1384 - (746 + 638)),(91 - 31),(1582 - (1535 + 46))}, "Thunderous Roar TTD", "Time to die to use Thunderous Roar");
v6("Slider", v19, "APL.Warrior.Arms_TTD.PotionsTTD", {(0 + 0),(4 + 56),(1468 - (899 + 568))}, "Potions TTD", "Time to die to use DPS Potions");
v6("Slider", v19, "APL.Warrior.Arms_TTD.WeaponTTD", {(0 - 0),(350 - (60 + 230)),(1 + 0)}, "Weapon TTD", "Time to die to use Weapon");
v8(v19, "APL.Warrior.Arms_TTD");
v6("CheckButton", v20, "APL.Warrior.Arms_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v20, "APL.Warrior.Arms_CDUSE.Enemycount", {(813 - (569 + 242)),(1 + 9),(1252 - (721 + 530))}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Racials", v14, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Potions", v14, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v20, "APL.Warrior.Arms_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Trinket1", v14, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Trinket2", v14, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Avatar", v14, "Avatar", "Choose an option on when to use Avatar");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.ColossusSmash", v14, "Colossus Smash", "Choose an option on when to use Colossus Smash");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Warbreaker", v14, "Warbreaker", "Choose an option on when to use Warbreaker");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.ThunderousRoar", v14, "Thunderous Roar", "Choose an option on when to use Thunderous Roar");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.ChampionsSpear", v14, "Champions Spear", "Choose an option on when to use Champions Spear");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Demolish", v14, "Demolish", "Choose an option on when to use Demolish");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Bladestorm", v14, "Bladestorm/Ravager", "Choose an option on when to use Bladestorm/Ravager");
v6("Dropdown", v20, "APL.Warrior.Arms_CDUSE.Weapon", v14, "Weapon", "Choose an option on when to use Weapon");
v8(v20, "APL.Warrior.Arms_CDUSE");
v6("CheckButton", v18, "APL.Warrior.Arms_Interrupt.Interrupt.UseStormbolt", "Use Stormbolt", "Enable this if you want the addon to use Stormbolt.");
v6("CheckButton", v18, "APL.Warrior.Arms_Interrupt.Interrupt.UseShockwave", "Use Shockwave", "Enable this if you want the addon to use Shockwave.");
v8(v18, "APL.Warrior.Arms_Interrupt");
v6("CheckButton", v21, "APL.Warrior.Fury.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v8(v21, "APL.Warrior.Fury");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.VictoryRushHP", {(0 - 0),(800 - (271 + 429)),(1501 - (1408 + 92))}, "Victory Rush HP", "Set the Victory Rush HP threshold. Set to 0 to disable.");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.ImpendingVictoryHP", {(1288 - (993 + 295)),(1271 - (418 + 753)),(1 + 0)}, "Impending Victory HP", "Set the Impending Victory HP threshold. Set to 0 to disable.");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.EnragedRegenerationHP", {(0 + 0),(1869 - (1749 + 20)),(1323 - (1249 + 73))}, "Enraged Regeneration HP", "Set the Enraged Regeneration HP threshold. Set to 0 to disable.");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.BitterImmunityHP", {(1145 - (466 + 679)),(286 - 186),(1 + 0)}, "Bitter Immunity HP", "Set the Bitter Immunity HP threshold. Set to 0 to disable.");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.DefStanceHP", {(0 - 0),(214 - (4 + 110)),(1428 - (41 + 1386))}, "Defensive Stance HP", "Set the HP percentage threshold of when you want the addon to suggest Defensive Stance. (Set to 0 to disable)");
v6("Slider", v22, "APL.Warrior.Fury.Defensives.BerserkerStanceHP", {(0 + 0),(289 - 189),(1 - 0)}, "Berserker Stance HP", "Set the HP percentage threshold of when you want the addon to get back Berserker Stance. (Set to 0 to disable)");
v8(v22, "APL.Warrior.Fury.Defensives");
v6("CheckButton", v24, "APL.Warrior.Fury_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v24, "APL.Warrior.Fury_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v24, "APL.Warrior.Fury_TTD.RacialsTTD", {(0 + 0),(121 - 61),(1 + 0)}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v24, "APL.Warrior.Fury_TTD.TrinketsTTD", {(0 - 0),(161 - 101),(321 - (53 + 267))}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v24, "APL.Warrior.Fury_TTD.ChampionsSpearTTD", {(413 - (15 + 398)),(225 - 165),(1 + 0)}, "Champions Spear TTD", "Time to die to use Champions Spear");
v6("Slider", v24, "APL.Warrior.Fury_TTD.AvatarTTD", {(0 + 0),(5 + 55),(1 - 0)}, "Avatar TTD", "Time to die to use Avatar");
v6("Slider", v24, "APL.Warrior.Fury_TTD.RecklessnessTTD", {(0 + 0),(158 - 98),(1552 - (1126 + 425))}, "Recklessness TTD", "Time to die to use Recklessness");
v6("Slider", v24, "APL.Warrior.Fury_TTD.RavagerTTD", {(0 - 0),(175 - 115),(4 - 3)}, "Ravager/Bladestorm TTD", "Time to die to use Ravager/Bladestorm");
v6("Slider", v24, "APL.Warrior.Fury_TTD.OdynsFuryTTD", {(977 - (553 + 424)),(53 + 7),(1 + 0)}, "OdynsFury TTD", "Time to die to use OdynsFury");
v6("Slider", v24, "APL.Warrior.Fury_TTD.ThunderousRoarTTD", {(0 + 0),(167 - 107),(1 + 0)}, "Thunderous Roar TTD", "Time to die to use Thunderous Roar");
v6("Slider", v24, "APL.Warrior.Fury_TTD.PotionsTTD", {(753 - (239 + 514)),(1389 - (797 + 532)),(1 + 0)}, "Potions TTD", "Time to die to use DPS Potions");
v6("Slider", v24, "APL.Warrior.Fury_TTD.WeaponTTD", {(1202 - (373 + 829)),(1190 - (369 + 761)),(1 - 0)}, "Weapon TTD", "Time to die to use Weapon");
v8(v24, "APL.Warrior.Fury_TTD");
v6("CheckButton", v25, "APL.Warrior.Fury_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v25, "APL.Warrior.Fury_CDUSE.Enemycount", {(240 - (64 + 174)),(14 - 4),(217 - (42 + 174))}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Racials", v14, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Potions", v14, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v25, "APL.Warrior.Fury_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Trinket1", v14, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Trinket2", v14, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Avatar", v14, "Avatar", "Choose an option on when to use Avatar");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Recklessness", v14, "Recklessness", "Choose an option on when to use Recklessness");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Ravager", v14, "Ravager/Bladestorm", "Choose an option on when to use Ravager/Bladestorm");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.ThunderousRoar", v14, "Thunderous Roar", "Choose an option on when to use Thunderous Roar");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.ChampionsSpear", v14, "Champions Spear", "Choose an option on when to use Champions Spear");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.OdynsFury", v14, "Odyns Fury", "Choose an option on when to use Odyns Fury");
v6("Dropdown", v25, "APL.Warrior.Fury_CDUSE.Weapon", v14, "Weapon", "Choose an option on when to use Weapon");
v8(v25, "APL.Warrior.Fury_CDUSE");
v6("CheckButton", v23, "APL.Warrior.Fury_Interrupt.Interrupt.UseStormbolt", "Use Stormbolt", "Enable this if you want the addon to use Stormbolt.");
v6("CheckButton", v23, "APL.Warrior.Fury_Interrupt.Interrupt.UseShockwave", "Use Shockwave", "Enable this if you want the addon to use Shockwave.");
v8(v23, "APL.Warrior.Fury_Interrupt");
v6("Slider", v26, "APL.Warrior.Protection.RageCapValue", {(25 + 5),(1604 - (363 + 1141)),(15 - 10)}, "Rage Cap Value", "Set the highest amount of Rage we should allow to pool before dumping Rage with Ignore Pain. Setting this value to 30 will allow you to over-cap Rage.");
v6("CheckButton", v26, "APL.Warrior.Protection.AllowIPOvercap", "Allow Ignore Pain Overcap", "Enable this option to allow Ignore Pain to be suggested, even when it would push the absorb over its maximum absorb value.");
v6("CheckButton", v26, "APL.Warrior.Protection.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v6("CheckButton", v26, "APL.Warrior.Protection.UseShieldCharge", "Use Shield Charge in melee", "Enable this if you want the addon to suggest Shiled Charge in melee.");
v6("Dropdown", v26, "APL.Warrior.Protection.Stance", {"No Stance","Battle Stance","Defensive Stance"}, "Which stance do we want", "Choose which Stance to use.");
v8(v26, "APL.Warrior.Protection");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.VictoryRushHP", {(0 - 0),(376 - 276),(1 - 0)}, "Victory Rush HP", "Set the Victory Rush HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.ImpendingVictoryHP", {(856 - (564 + 292)),(301 - 201),(1 + 0)}, "Impending Victory HP", "Set the Impending Victory HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.BitterImmunityHP", {(1001 - (938 + 63)),(1225 - (936 + 189)),(1614 - (1565 + 48))}, "Bitter Immunity HP", "Set the Bitter Immunity HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.IgnorePainHP", {(1138 - (782 + 356)),(260 - 160),(1093 - (975 + 117))}, "Ignore Pain HP", "Set the IgnorePain HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.ShieldWallHP", {(0 + 0),(341 - 241),(2 - 1)}, "Shield Wall HP", "Set the Shield Wall HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.LastStandHP", {(0 - 0),(187 - 87),(1228 - (322 + 905))}, "Last Stand HP", "Set the Last Stand HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.ShieldBlockHP", {(1189 - (449 + 740)),(1047 - (245 + 702)),(1 + 0)}, "Shield Block HP", "Set the Shield Block HP threshold. Set to 0 to disable.");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.DefStanceHP", {(440 - (382 + 58)),(84 + 16),(2 - 1)}, "Defensive Stance HP", "Set the HP percentage threshold of when you want the addon to suggest Defensive Stance. (Set to 0 to disable)");
v6("Slider", v27, "APL.Warrior.Protection.Defensives.BattleStanceHP", {(0 - 0),(9 + 91),(215 - (22 + 192))}, "Battle Stance HP", "Set the HP percentage threshold of when you want the addon to get back Battle Stance. (Set to 0 to disable)");
v8(v27, "APL.Warrior.Arms.Defensives");
v6("CheckButton", v29, "APL.Warrior.Protection_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v29, "APL.Warrior.Protection_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v29, "APL.Warrior.Protection_TTD.RacialsTTD", {(1463 - (1404 + 59)),(80 - 20),(563 - (334 + 228))}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v29, "APL.Warrior.Protection_TTD.TrinketsTTD", {(0 - 0),(18 + 42),(1 + 0)}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v29, "APL.Warrior.Protection_TTD.ChampionsSpearTTD", {(0 - 0),(164 - 104),(1 + 0)}, "Champions Spear TTD", "Time to die to use Champions Spear");
v6("Slider", v29, "APL.Warrior.Protection_TTD.AvatarTTD", {(0 + 0),(30 + 30),(766 - (574 + 191))}, "Avatar TTD", "Time to die to use Avatar");
v6("Slider", v29, "APL.Warrior.Protection_TTD.ThunderousRoarTTD", {(0 - 0),(909 - (254 + 595)),(1 - 0)}, "Thunderous Roar TTD", "Time to die to use Thunderous Roar");
v6("Slider", v29, "APL.Warrior.Protection_TTD.RavagerTTD", {(0 - 0),(96 - 36),(2 - 1)}, "Ravager TTD", "Time to die to use Ravager");
v6("Slider", v29, "APL.Warrior.Protection_TTD.PotionsTTD", {(0 + 0),(866 - (118 + 688)),(1 + 0)}, "Potions TTD", "Time to die to use DPS Potions");
v6("Slider", v29, "APL.Warrior.Protection_TTD.DemolishTTD", {(0 - 0),(115 - 55),(2 - 1)}, "Demolish TTD", "Time to die to use Demolish");
v6("Slider", v29, "APL.Warrior.Protection_TTD.DemoralizingShoutTTD", {(0 - 0),(1856 - (503 + 1293)),(1 + 0)}, "Demoralizing Shout TTD", "Time to die to use Demoralizing Shout");
v8(v29, "APL.Warrior.Protection_TTD");
v6("CheckButton", v30, "APL.Warrior.Protection_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v30, "APL.Warrior.Protection_CDUSE.Enemycount", {(2 + 0),(10 + 0),(734 - (711 + 22))}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Racials", v14, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Potions", v14, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v30, "APL.Warrior.Protection_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Trinket1", v14, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Trinket2", v14, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Avatar", v14, "Avatar", "Choose an option on when to use Avatar");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Ravager", v14, "Ravager", "Choose an option on when to use Ravager");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.ThunderousRoar", v14, "Thunderous Roar", "Choose an option on when to use Thunderous Roar");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.ChampionsSpear", v14, "Champions Spear", "Choose an option on when to use Champions Spear");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.DemoralizingShout", v14, "Demoralizing Shout", "Choose an option on when to use Demoralizing Shout");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.Demolish", v14, "Demolish", "Choose an option on when to use Demolish");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.LastStand", v14, "Last Stand", "Choose an option on when to use Last Stand aggressively ignoreing the defensive use");
v6("Dropdown", v30, "APL.Warrior.Protection_CDUSE.ShieldWall", v14, "Shield Wall", "Choose an option on when to use Shield Wall aggressively ignoreing the defensive use");
v8(v30, "APL.Warrior.Protection_CDUSE");
v6("CheckButton", v28, "APL.Warrior.Protection_Interrupt.Interrupt.UseStormbolt", "Use Stormbolt", "Enable this if you want the addon to use Stormbolt.");
v6("CheckButton", v28, "APL.Warrior.Protection_Interrupt.Interrupt.UseShockwave", "Use Shockwave", "Enable this if you want the addon to use Shockwave.");
v8(v28, "APL.Warrior.Protection_Interrupt");
v10.APL.Warrior.Arms.Display = function()
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v9);
	v3.GUI.ShowPanel(v16);
	v3.GUI.ShowPanel(v17);
	v3.GUI.ShowPanel(v18);
	v3.GUI.ShowPanel(v19);
	v3.GUI.ShowPanel(v20);
end;
v10.APL.Warrior.Fury.Display = function()
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v9);
	v3.GUI.ShowPanel(v21);
	v3.GUI.ShowPanel(v22);
	v3.GUI.ShowPanel(v23);
	v3.GUI.ShowPanel(v24);
	v3.GUI.ShowPanel(v25);
end;
v10.APL.Warrior.Protection.Display = function()
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v9);
	v3.GUI.ShowPanel(v26);
	v3.GUI.ShowPanel(v27);
	v3.GUI.ShowPanel(v28);
	v3.GUI.ShowPanel(v29);
	v3.GUI.ShowPanel(v30);
end;
