local v0, v1 = ...;
local v2 = HeroRotation();
local v3 = HeroLib;
local v4 = v3.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v2.HRGUIGet().CreateARPanelOption;
local v8 = v2.HRGUIGet().CreateARPanelOptions;
local v9 = v2.GUISettingsGet();
v9.APL.DeathKnight = {Commons={Enabled={Potions=true,Trinkets=true,Items=true},DnDMoving=false,RaiseAlly=true,AttackOutOfCombat=false,BlindingSleet=true},Blood={PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},Mobcount=(5 - 3),EmpowerRuneWeaponSetting="With Cooldowns",RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",TrinketHP=(114 - 74),RaiseDeadSetting="With Cooldowns",AbominationLimbSetting="With Cooldowns",PotionSetting="With Cooldowns",DancingRuneWeaponSetting="With Cooldowns",DancingRuneWeaponHP=(77 - 37),Weapon="With Cooldowns",Bonestorm="With Cooldowns",ReapersMarkSetting="With Cooldowns",Defensives={TankBusters=true,RuneTapThreshold=(103 - 63),VampiricBloodThreshold=(684 - (555 + 64)),DeathStrikeDumpAmount=(996 - (857 + 74)),AntiMagicShellHP=(608 - (367 + 201)),AntiMagicZoneHP=(967 - (214 + 713)),IceboundFortitudeHP=(13 + 37),LichborneHP=(8 + 42)}},Blood_TTD={EmpowerRuneWeaponTTD=(897 - (282 + 595)),AbominationLimbTTD=(1657 - (1523 + 114)),RacialsTTD=(18 + 2),TrinketsTTD=(28 - 8),DancingRuneWeaponTTD=(1085 - (68 + 997)),RaiseDeadTTD=(1290 - (226 + 1044))},Frost={PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},Mobcount=(8 - 6),EmpowerRuneWeaponSetting="With Cooldowns",RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",RaiseDeadSetting="With Cooldowns",BreathOfSindragosaSetting="With Cooldowns",FrostwyrmsFurySetting="With Cooldowns",PillarofFrostSetting="With Cooldowns",AbominationLimbSetting="With Cooldowns",PotionSetting="With Cooldowns",Weapon="With Cooldowns",ReapersMarkSetting="With Cooldowns",Defensives={UseDeathStrikeHP=(177 - (32 + 85)),UseDarkSuccorHP=(79 + 1),AntiMagicShellHP=(9 + 31),AntiMagicZoneHP=(997 - (892 + 65)),IceboundFortitudeHP=(119 - 69),LichborneHP=(92 - 42)}},Frost_TTD={EmpowerRuneWeaponTTD=(36 - 16),AbominationLimbTTD=(370 - (87 + 263)),RacialsTTD=(200 - (67 + 113)),TrinketsTTD=(15 + 5),RaiseDeadTTD=(49 - 29),BreathOfSindragosaTTD=(15 + 5),FrostwyrmsFuryTTD=(79 - 59),PillarofFrostTTD=(972 - (802 + 150))},Unholy={Mobcount=(5 - 3),DarkTransformationSetting="With Cooldowns",RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",PotionSetting="With Cooldowns",ApocalypseSetting="With Cooldowns",UnholyAssaultSetting="With Cooldowns",UnholyBlightSetting="With Cooldowns",EmpowerRuneWeaponSetting="With Cooldowns",AbominationLimbSetting="With Cooldowns",ArmyOfTheDeadSetting="Not Used",SummonGargoyleSetting="With Cooldowns",RaiseAbominationSetting="With Cooldowns",Weapon="With Cooldowns",PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},Defensives={UseDeathStrikeHP=(108 - 48),UseDarkSuccorHP=(59 + 21),AntiMagicShellHP=(1037 - (915 + 82)),AntiMagicZoneHP=(113 - 73),AntiMagicZoneOnTankBuster=true,IceboundFortitudeHP=(30 + 20),LichborneHP=(65 - 15)}},Unholy_TTD={EmpowerRuneWeaponTTD=(1207 - (1069 + 118)),AbominationLimbTTD=(45 - 25),RacialsTTD=(43 - 23),TrinketsTTD=(4 + 16),ApocalypseTTD=(35 - 15),DarkTransformationTTD=(10 + 0),UnholyAssaultTTD=(811 - (368 + 423)),UnholyBlightTTD=(62 - 42),SummonGargoyleTTD=(38 - (10 + 8)),RaiseAbominationTTD=(76 - 56)}};
v2.HRGUIGet().LoadSettingsRecursively(v9);
local v11 = v2.HRGUIGet().Panel;
local v12 = v5(v11, "DeathKnight");
local v13 = v5(v12, "Blood");
local v14 = v5(v13, "Defensives");
local v15 = v5(v13, "TTD");
local v16 = v5(v12, "Frost");
local v17 = v5(v16, "Defensives");
local v18 = v5(v16, "TTD");
local v19 = v5(v12, "Unholy");
local v20 = v5(v19, "Defensives");
local v21 = v5(v19, "TTD");
local v22 = {"Not Used","Always","With Cooldowns","With Small or Cooldowns","With Small CDs","On Mobcount","On Mobcount or Cooldowns","On Bosses","Mobcount or Boss"};
local v23 = {"Not Used","Always","With Cooldowns","With Small or Cooldowns","With Small CDs","On Mobcount","On Mobcount or Cooldowns","On Bosses","Mobcount or Boss","On HealthPercent"};
v6("CheckButton", v12, "APL.DeathKnight.Commons.DnDMoving", "DnD while moving", "Use Death and Decay while moving");
v6("CheckButton", v12, "APL.DeathKnight.Commons.RaiseAlly", "Use Raise Ally", "Use Raise Ally");
v6("CheckButton", v12, "APL.DeathKnight.Commons.AttackOutOfCombat", "Attack out of combat", "Attack out of combat");
v6("CheckButton", v12, "APL.DeathKnight.Commons.BlindingSleet", "Use Binding Sleet", "Use Binding Sleet");
v8(v12, "APL.DeathKnight.Commons");
v6("Slider", v13, "APL.DeathKnight.Blood.Mobcount", {(0 - 0),(1483 - (630 + 793)),(4 - 3)}, "Mobcount", "Mobcount");
v6("Dropdown", v13, "APL.DeathKnight.Blood.RacialsSetting", v22, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v13, "APL.DeathKnight.Blood.Trinket1Setting", v23, "Trinket 1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v13, "APL.DeathKnight.Blood.Trinket2Setting", v23, "Trinket 2 Usage", "Select how to use Trinket 2.");
v6("Slider", v13, "APL.DeathKnight.Blood.TrinketHP", {(0 - 0),(2013 - (1789 + 124)),(1 + 0)}, "Trinket HP Value", "Select Trinket HP Value");
v6("Dropdown", v13, "APL.DeathKnight.Blood.PotionSetting", v22, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v13, "APL.DeathKnight.Blood.EmpowerRuneWeaponSetting", v22, "Empower Rune Weapon Usage", "Select how to use Empower Rune Weapon.");
v6("Dropdown", v13, "APL.DeathKnight.Blood.RaiseDeadSetting", v22, "Raise Dead Usage", "Select how to use Raise Dead.");
v6("Dropdown", v13, "APL.DeathKnight.Blood.AbominationLimbSetting", v22, "Abomination Limb Usage", "Select how to use Abomination Limb.");
v6("Dropdown", v13, "APL.DeathKnight.Blood.DancingRuneWeaponSetting", v23, "Dancing Rune Weapon Usage", "Select how to use Dancing Rune Weapon.");
v6("Slider", v13, "APL.DeathKnight.Blood.DancingRuneWeaponHP", {(0 - 0),(79 + 21),(4 - 3)}, "Dancing Rune Weapon HP", "Select how to use Dancing Rune Weapon.");
v6("Dropdown", v13, "APL.DeathKnight.Blood.Weapon", v22, "Weapon", "Choose an option on when to use Weapon");
v6("Dropdown", v13, "APL.DeathKnight.Blood.ReapersMarkSetting", v22, "Reaper's Mark", "Choose an option on when to use Reaper's Mark");
v6("Dropdown", v13, "APL.DeathKnight.Blood.Bonestorm", v22, "Bonestorm", "Choose an option on when to use Bonestorm");
v8(v13, "APL.DeathKnight.Blood");
v6("CheckButton", v14, "APL.DeathKnight.Blood.Defensives.TankBusters", "Use Defensives on Tankbusters", "Use your defensives as Tankbusters");
v6("Slider", v14, "APL.DeathKnight.Blood.Defensives.AntiMagicShellHP", {(0 - 0),(273 - 173),(702 - (376 + 325))}, "Use Anti-Magic shell on Low HP", "Set the HP threshold to use Anti-Magic Shell.");
v6("Slider", v14, "APL.DeathKnight.Blood.Defensives.AntiMagicZoneHP", {(0 - 0),(220 - 120),(377 - (85 + 291))}, "Use Anti-Magic Zone on Low HP", "Set the HP threshold to use Anti-Magic Zone.");
v6("CheckButton", v14, "APL.DeathKnight.Blood.Defensives.AntiMagicZoneOnTankBuster", "Anti-Magic Zone on Tank Buster", "Anti-Magic Zone on Tanbkbuster.");
v6("Slider", v14, "APL.DeathKnight.Blood.Defensives.LichborneHP", {(0 - 0),(1280 - (1123 + 57)),(255 - (163 + 91))}, "Use Lichborne on Low HP", "Set the HP threshold to use Lichborne.");
v6("Slider", v14, "APL.DeathKnight.Blood.Defensives.IceboundFortitudeHP", {(0 + 0),(153 - 53),(1 - 0)}, "Icebound Fortitude on low HP", "Icebound Fortitude when below this health percentage.");
v6("Slider", v14, "APL.DeathKnight.Blood.Defensives.RuneTapThreshold", {(1479 - (1329 + 145)),(1950 - (1409 + 441)),(3 + 2)}, "Rune Tap Health Threshold", "Suggest Rune Tap when below this health percentage.");
v6("Slider", v14, "APL.DeathKnight.Blood.Defensives.VampiricBloodThreshold", {(1726 - (345 + 1376)),(441 - 341),(1211 - (696 + 510))}, "Vampiric Blood Health Threshold", "Suggest Vampiric Blood when below this health percentage.");
v6("Slider", v14, "APL.DeathKnight.Blood.Defensives.DeathStrikeDumpAmount", {(1327 - (1091 + 171)),(409 - 279),(379 - (123 + 251))}, "Death Strike Dump Amount", "Suggest Death Strike as a Runic Power dump when above this amount of Runic Power.");
v8(v14, "APL.DeathKnight.Blood.Defensives");
v6("Slider", v15, "APL.DeathKnight.Blood_TTD.EmpowerRuneWeaponTTD", {(698 - (208 + 490)),(27 + 33),(1 + 0)}, "Empower Rune Weapon TTD", "TTD to use Empower Rune Weapon on Dungeon Mobs");
v6("Slider", v15, "APL.DeathKnight.Blood_TTD.AbominationLimbTTD", {(675 - (534 + 141)),(54 + 6),(1 - 0)}, "Abomination Limb TTD", "TTD to use Abomination Limb on Dungeon Mobs");
v6("Slider", v15, "APL.DeathKnight.Blood_TTD.RacialsTTD", {(0 - 0),(39 + 21),(2 - 1)}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v15, "APL.DeathKnight.Blood_TTD.TrinketsTTD", {(0 - 0),(927 - (550 + 317)),(1 - 0)}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v15, "APL.DeathKnight.Blood_TTD.DancingRuneWeaponTTD", {(285 - (134 + 151)),(114 - 54),(3 - 2)}, "Dancing Rune Weapon TTD", "TTD to use Dancing Rune Weapon on Dungeon Mobs");
v6("Slider", v15, "APL.DeathKnight.Blood_TTD.RaiseDeadTTD", {(0 - 0),(79 - 19),(781 - (162 + 618))}, "Raise Dead TTD", "TTD to use Raise Dead on Dungeon Mobs");
v8(v15, "APL.DeathKnight.Blood_TTD");
v6("Slider", v16, "APL.DeathKnight.Frost.Mobcount", {(0 + 0),(100 - 40),(1637 - (1373 + 263))}, "Mobcount", "Mobcount");
v6("Dropdown", v16, "APL.DeathKnight.Frost.RacialsSetting", v22, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v16, "APL.DeathKnight.Frost.Trinket1Setting", v22, "Trinket 1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v16, "APL.DeathKnight.Frost.Trinket2Setting", v22, "Trinket 2 Usage", "Select how to use Trinket 2.");
v6("Dropdown", v16, "APL.DeathKnight.Frost.PotionSetting", v22, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v16, "APL.DeathKnight.Frost.EmpowerRuneWeaponSetting", v22, "Empower Rune Weapon Usage", "Select how to use Empower Rune Weapon.");
v6("Dropdown", v16, "APL.DeathKnight.Frost.RaiseDeadSetting", v22, "Raise Dead Usage", "Select how to use Raise Dead.");
v6("Dropdown", v16, "APL.DeathKnight.Frost.BreathOfSindragosaSetting", v22, "Breath of Sindragosa Usage", "Select how to use Breath of Sindragosa.");
v6("Dropdown", v16, "APL.DeathKnight.Frost.FrostwyrmsFurySetting", v22, "Frostwyrm's Fury Usage", "Select how to use Frostwyrm's Fury.");
v6("Dropdown", v16, "APL.DeathKnight.Frost.PillarofFrostSetting", v22, "Pillar of Frost Usage", "Select how to use Pillar of Frost.");
v6("Dropdown", v16, "APL.DeathKnight.Frost.AbominationLimbSetting", v22, "Abomination Limb Usage", "Select how to use Abomination Limb.");
v6("Dropdown", v16, "APL.DeathKnight.Frost.Weapon", v22, "Weapon", "Choose an option on when to use Weapon");
v6("Dropdown", v16, "APL.DeathKnight.Frost.ReapersMarkSetting", v22, "Reaper's Mark", "Choose an option on when to use Reaper's Mark");
v8(v16, "APL.DeathKnight.Frost");
v6("Slider", v17, "APL.DeathKnight.Frost.Defensives.AntiMagicShellHP", {(0 + 0),(168 - 68),(1 + 0)}, "Use Anti-Magic shell on Low HP", "Set the HP threshold to use Anti-Magic Shell.");
v6("Slider", v17, "APL.DeathKnight.Frost.Defensives.AntiMagicZoneHP", {(341 - (218 + 123)),(100 + 0),(561 - (306 + 254))}, "Use Anti-Magic Zone on Low HP", "Set the HP threshold to use Anti-Magic Zone.");
v6("Slider", v17, "APL.DeathKnight.Frost.Defensives.LichborneHP", {(0 - 0),(66 + 34),(604 - (268 + 335))}, "Use Lichborne on Low HP", "Set the HP threshold to use Lichborne.");
v6("Slider", v17, "APL.DeathKnight.Frost.Defensives.IceboundFortitudeHP", {(572 - (426 + 146)),(1556 - (282 + 1174)),(2 - 1)}, "Icebound Fortitude on low HP", "Icebound Fortitude when below this health percentage.");
v6("Slider", v17, "APL.DeathKnight.Frost.Defensives.UseDeathStrikeHP", {(1024 - (706 + 318)),(1371 - (945 + 326)),(1 + 0)}, "Use Death Strike on Low HP", "Set the HP threshold to use Death Strike.");
v6("Slider", v17, "APL.DeathKnight.Frost.Defensives.UseDarkSuccorHP", {(0 + 0),(1186 - (461 + 625)),(1 + 0)}, "Death Strike - Dark Succor", "Set the HP threshold to use Death Strike to Consume Dark Succor.");
v8(v17, "APL.DeathKnight.Frost.Defensives");
v6("Slider", v18, "APL.DeathKnight.Frost_TTD.EmpowerRuneWeaponTTD", {(0 + 0),(18 + 42),(530 - (406 + 123))}, "Empower Rune Weapon TTD", "TTD to use Empower Rune Weapon on Dungeon Mobs");
v6("Slider", v18, "APL.DeathKnight.Frost_TTD.AbominationLimbTTD", {(0 + 0),(22 + 38),(2 - 1)}, "Abomination Limb TTD", "TTD to use Abomination Limb on Dungeon Mobs");
v6("Slider", v18, "APL.DeathKnight.Frost_TTD.RacialsTTD", {(1900 - (106 + 1794)),(16 + 44),(2 - 1)}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v18, "APL.DeathKnight.Frost_TTD.TrinketsTTD", {(584 - (57 + 527)),(163 - (17 + 86)),(1 - 0)}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v18, "APL.DeathKnight.Frost_TTD.RaiseDeadTTD", {(166 - (122 + 44)),(199 - 139),(1 + 0)}, "Raise Dead TTD", "TTD to use Raise Dead on Dungeon Mobs");
v6("Slider", v18, "APL.DeathKnight.Frost_TTD.BreathOfSindragosaTTD", {(65 - (30 + 35)),(1317 - (1043 + 214)),(1213 - (323 + 889))}, "Breath of Sindragosa TTD", "TTD to use Breath of Sindragosa on Dungeon Mobs");
v6("Slider", v18, "APL.DeathKnight.Frost_TTD.FrostwyrmsFuryTTD", {(580 - (361 + 219)),(14 + 46),(983 - (18 + 964))}, "Frostwyrm's Fury TTD", "TTD to use Frostwyrm's Fury on Dungeon Mobs");
v6("Slider", v18, "APL.DeathKnight.Frost_TTD.PillarofFrostTTD", {(0 + 0),(910 - (20 + 830)),(127 - (116 + 10))}, "Pillar of Frost TTD", "TTD to use Pillar of Frost on Dungeon Mobs");
v8(v18, "APL.DeathKnight.Frost_TTD");
v6("Slider", v19, "APL.DeathKnight.Unholy.Mobcount", {(738 - (542 + 196)),(18 + 42),(1 + 0)}, "Mobcount", "Mobcount");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.RacialsSetting", v22, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.Trinket1Setting", v22, "Trinket1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.Trinket2Setting", v22, "Trinket2 Usage", "Select how to use Trinket 2.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.PotionSetting", v22, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.DarkTransformationSetting", v22, "Dark Transformation Usage", "Select how to use Dark Transformation.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.ApocalypseSetting", v22, "Apocalypse Usage", "Select how to use Apocalypse.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.UnholyAssaultSetting", v22, "Unholy Assault Usage", "Select how to use Unholy Assault.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.UnholyBlightSetting", v22, "Unholy Blight Usage", "Select how to use Unholy Blight.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.EmpowerRuneWeaponSetting", v22, "Empower Rune Weapon Usage", "Select how to use Empower Rune Weapon.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.AbominationLimbSetting", v22, "Abomination Limb Usage", "Select how to use Abomination Limb.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.ArmyOfTheDeadSetting", v22, "Army of the Dead Usage", "Select how to use Army of the Dead.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.SummonGargoyleSetting", v22, "Summon Gargoyle Usage", "Select how to use Summon Gargoyle.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.RaiseAbominationSetting", v22, "Raise Abomination Usage", "Select how to use Raise Abomination.");
v6("Dropdown", v19, "APL.DeathKnight.Unholy.Weapon", v22, "Weapon", "Choose an option on when to use Weapon");
v8(v19, "APL.DeathKnight.Unholy");
v6("Slider", v20, "APL.DeathKnight.Unholy.Defensives.AntiMagicShellHP", {(0 - 0),(505 - (118 + 287)),(1122 - (118 + 1003))}, "Use Anti-Magic shell on Low HP", "Set the HP threshold to use Anti-Magic Shell.");
v6("Slider", v20, "APL.DeathKnight.Unholy.Defensives.AntiMagicZoneHP", {(377 - (142 + 235)),(22 + 78),(1 - 0)}, "Use Anti-Magic Zone on Low HP", "Set the HP threshold to use Anti-Magic Zone.");
v6("Slider", v20, "APL.DeathKnight.Unholy.Defensives.LichborneHP", {(0 + 0),(43 + 57),(2 - 1)}, "Use Lichborne on Low HP", "Set the HP threshold to use Lichborne.");
v6("Slider", v20, "APL.DeathKnight.Unholy.Defensives.IceboundFortitudeHP", {(0 - 0),(483 - 383),(1 + 0)}, "Icebound Fortitude on low HP", "Icebound Fortitude when below this health percentage.");
v6("Slider", v20, "APL.DeathKnight.Unholy.Defensives.UseDeathStrikeHP", {(0 + 0),(235 - 135),(732 - (476 + 255))}, "Use Death Strike on Low HP", "Set the HP threshold to use Death Strike.");
v6("Slider", v20, "APL.DeathKnight.Unholy.Defensives.UseDarkSuccorHP", {(0 + 0),(189 - 89),(1 + 0)}, "Death Strike - Dark Succor", "Set the HP threshold to use Death Strike to Consume Dark Succor.");
v8(v20, "APL.DeathKnight.Unholy.Defensives");
v6("Slider", v21, "APL.DeathKnight.Unholy_TTD.EmpowerRuneWeaponTTD", {(336 - (144 + 192)),(46 + 14),(1 + 0)}, "Empower Rune Weapon TTD", "TTD to use Empower Rune Weapon on Dungeon Mobs");
v6("Slider", v21, "APL.DeathKnight.Unholy_TTD.AbominationLimbTTD", {(1580 - (1183 + 397)),(44 + 16),(1976 - (1913 + 62))}, "Abomination Limb TTD", "TTD to use Abomination Limb on Dungeon Mobs");
v6("Slider", v21, "APL.DeathKnight.Unholy_TTD.RacialsTTD", {(0 - 0),(225 - 165),(1 - 0)}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v21, "APL.DeathKnight.Unholy_TTD.TrinketsTTD", {(856 - (564 + 292)),(180 - 120),(1 + 0)}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v21, "APL.DeathKnight.Unholy_TTD.ApocalypseTTD", {(1001 - (938 + 63)),(1185 - (936 + 189)),(1614 - (1565 + 48))}, "Apocalypse TTD", "TTD to use Apocalypse on Dungeon Mobs");
v6("Slider", v21, "APL.DeathKnight.Unholy_TTD.DarkTransformationTTD", {(1138 - (782 + 356)),(156 - 96),(1093 - (975 + 117))}, "Dark Transformation TTD", "TTD to use Dark Transformation on Dungeon Mobs");
v6("Slider", v21, "APL.DeathKnight.Unholy_TTD.UnholyAssaultTTD", {(0 + 0),(205 - 145),(2 - 1)}, "Unholy Assault TTD", "TTD to use Unholy Assault on Dungeon Mobs");
v6("Slider", v21, "APL.DeathKnight.Unholy_TTD.UnholyBlightTTD", {(0 - 0),(112 - 52),(1228 - (322 + 905))}, "Unholy Blight TTD", "TTD to use Unholy Blight on Dungeon Mobs");
v6("Slider", v21, "APL.DeathKnight.Unholy_TTD.SummonGargoyleTTD", {(1189 - (449 + 740)),(1007 - (245 + 702)),(1 + 0)}, "Summon Gargoyle TTD", "TTD to use Summon Gargoyle on Dungeon Mobs");
v6("Slider", v21, "APL.DeathKnight.Unholy_TTD.RaiseAbominationTTD", {(440 - (382 + 58)),(50 + 10),(2 - 1)}, "Raise Abomination TTD", "TTD to use Raise Abomination on Dungeon Mobs");
v8(v21, "APL.DeathKnight.Unholy_TTD");
v9.APL.DeathKnight.Unholy.Display = function()
	v3.GUI.ShowPanel(v19);
	v3.GUI.ShowPanel(v21);
	v3.GUI.ShowPanel(v20);
	v3.GUI.ShowPanel(v12);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v13);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v14);
end;
v9.APL.DeathKnight.Frost.Display = function()
	v3.GUI.ShowPanel(v17);
	v3.GUI.ShowPanel(v12);
	v3.GUI.ShowPanel(v16);
	v3.GUI.ShowPanel(v18);
	v3.GUI.HidePanel(v13);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v14);
	v3.GUI.HidePanel(v20);
end;
v9.APL.DeathKnight.Blood.Display = function()
	v3.GUI.ShowPanel(v14);
	v3.GUI.ShowPanel(v12);
	v3.GUI.ShowPanel(v15);
	v3.GUI.ShowPanel(v13);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v20);
end;
