local v0, v1 = ...;
local v2 = HeroLib;
local v3 = HeroRotation();
local v4 = v2.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v3.HRGUIGet().CreateARPanelOption;
local v8 = v3.HRGUIGet().CreateARPanelOptions;
local v9 = "With Logic";
local v10 = v4.GetPanelByName("Interrupt");
local v11 = v3.GUISettingsGet();
v11.APL.Shaman = {Commons={Enabled={Potions=true,Trinkets=true,Items=true},SkyFury="only check us",AutoWolf="Only out of combat",TabForPurge=false,DisplayStyle={Potions="Suggested",Trinkets="Suggested",Items="Suggested",Signature="Suggested",SpiritwalkersGrace="SuggestedRight"},UseBloodlust=false},Enhancement={PreferEarthShield=false,AttackonlyinCombat=false,AutoTabDot=false,Defensives={Earthshieldooc=false,InstantHealingSurgeHP=(156 - 106),HealingSurgeHP=(85 - 55),HealingStreamTotemHP=(57 - 27),AstralShiftHP=(103 - 63),AncestralGuidanceHP=(679 - (555 + 64)),StoneBulkwarkTotemHP=(961 - (857 + 74)),AncestralGuidanceCount=(571 - (367 + 201)),EarthElemental=(927 - (214 + 713))},PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"}},Enhancement_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=false,AutoTargetStun=false,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(16 + 44),InterruptPercentChannel=(10 + 50)}},Enhancement_TTD={RacialsTTD=(897 - (282 + 595)),TrinketsTTD=(1657 - (1523 + 114)),SunderingTTD=(9 + 1),FeralSpiritTTD=(20 - 5),AscendanceTTD=(1085 - (68 + 997)),PrimordialWaveTTD=(1280 - (226 + 1044)),DoomWindsTTD=(43 - 33),PotionsTTD=(137 - (32 + 85)),SurgingTotemTTD=(20 + 0),TempestTTD=(0 + 0),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Enhancement_CDUSE={smallcdswithCooldowns=true,Enemycount=(962 - (892 + 65)),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",Ascendance="with Cooldowns",DoomWinds="with Cooldowns",EarthElemental="with Cooldowns",FeralSpirit="with Cooldowns",Sundering="with Cooldowns",FireNova="with Cooldowns",IceStrike="with Cooldowns",PrimordialWave="with Cooldowns",SurgingTotem="with Cooldowns"},Elemental={PreferEarthShield=false,AttackonlyinCombat=false,CursorCheck=true,ForceAOE=false,Defensives={Earthshieldooc=false,AstralShiftHP=(95 - 55),HealingStreamTotemHP=(55 - 25),HealingSurgeHP=(55 - 25),AncestralGuidanceHP=(410 - (87 + 263)),StoneBulkwarkTotemHP=(210 - (67 + 113)),AncestralGuidanceCount=(3 + 0),EarthElemental=(0 - 0)},PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},DisplayStyle={Meteor="Suggested",EyeOfTheStorm="Suggested"}},Elemental_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=false,AutoTargetStun=false,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(45 + 15),InterruptPercentChannel=(238 - 178)}},Elemental_TTD={RacialsTTD=(972 - (802 + 150)),TrinketsTTD=(53 - 33),FireElementalTTD=(54 - 24),AscendanceTTD=(15 + 5),StormkeeperTTD=(1007 - (915 + 82)),LiquidMagmaTotemTTD=(28 - 18),PrimordialWaveTTD=(6 + 4),PotionsTTD=(26 - 6),TempestTTD=(1187 - (1069 + 118)),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Elemental_CDUSE={smallcdswithCooldowns=true,Enemycount=(10 - 5),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",Ascendance="with Cooldowns",NaturesSwiftness="with Cooldowns",EarthElemental="with Cooldowns",FireElemental="with Cooldowns",StormElemental="with Cooldowns",Stormkeeper="with Cooldowns",LiquidMagmaTotem="with Cooldowns",PrimordialWave="with Cooldowns"},Restoration={AstralShiftHP=(87 - 47),SpiritwalkersGrace=true,EarthlivingWeapon=false,TotemRecall=true,AttackOOC=false,Cooldowns={UseAG=v9,UseAscendance=v9,EarthEle=v9,Stormkeeper=v9,Trinket1Use="With Logic",Trinket2Use="With Logic",Trinket1HP=(12 + 53),Trinket2HP=(115 - 50)},AoE={AGHP=(50 + 0),AscendanceHP=(826 - (368 + 423)),ChainHealHighTideHP=(266 - 181),ChainHealHP=(18 - (10 + 8)),CloudBurstHP=(211 - 156),CloudBurstRecastHP=(467 - (416 + 26)),DownpourHP=(207 - 142),EarthenWallHP=(33 + 42),HealingRainHP=(141 - 61),HealingTideHP=(468 - (145 + 293)),SpiritLinkHP=(445 - (44 + 386)),WellspringHP=(1556 - (998 + 488)),AGCount=(1 + 2),AscendanceCount=(3 + 0),ChainHealHighTideCount=(774 - (201 + 571)),ChainHealCount=(1140 - (116 + 1022)),CloudBurstCount=(8 - 6),CloudBurstRecastCount=(2 + 1),DownpourCount=(10 - 7),EarthenWallCount=(81 - 58),HealingRainCount=(862 - (814 + 45)),HealingTideCount=(7 - 4),SpiritLinkCount=(1 + 3),WellspringCount=(2 + 1)},Healing={HealingSurgeHP=(955 - (261 + 624)),HealingSurgeTankHP=(161 - 70),HealingWaveHP=(1090 - (1020 + 60)),HealingWaveTankHP=(1433 - (630 + 793)),ManaTideMP=(287 - 202),PrimordiaWaveHP=(369 - 291),RiptideHP=(36 + 54),UnleashLifeHP=(275 - 195),WhichUndulation="Healing Wave",NSHP=(1792 - (760 + 987))},RaidAoE={AGHP=(1988 - (1789 + 124)),AscendanceHP=(811 - (745 + 21)),ChainHealHighTideHP=(30 + 55),ChainHealHP=(0 - 0),CloudBurstHP=(294 - 219),CloudBurstRecastHP=(1 + 44),DownpourHP=(52 + 13),EarthenWallHP=(1150 - (87 + 968)),HealingRainHP=(418 - 323),HealingTideHP=(41 + 4),SpiritLinkHP=(79 - 44),WellspringHP=(1483 - (447 + 966)),AGCount=(19 - 12),AscendanceCount=(1825 - (1703 + 114)),ChainHealHighTideCount=(706 - (376 + 325)),ChainHealCount=(8 - 3),CloudBurstCount=(24 - 16),CloudBurstRecastCount=(3 + 5),DownpourCount=(12 - 6),EarthenWallCount=(23 - (9 + 5)),HealingRainCount=(383 - (85 + 291)),HealingTideCount=(1273 - (243 + 1022)),SpiritLinkCount=(30 - 22),WellspringCount=(7 + 1)},RaidHealing={HealingSurgeHP=(1250 - (1123 + 57)),HealingSurgeTankHP=(75 + 16),HealingWaveHP=(264 - (163 + 91)),HealingWaveTankHP=(1940 - (1869 + 61)),ManaTideMP=(24 + 61),PrimordiaWaveHP=(274 - 196),RiptideHP=(138 - 48),UnleashLifeHP=(11 + 69),WhichUndulation="Healing Wave",NSHP=(61 - 16)},PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},GCDasOffGCD={},OffGCDasOffGCD={}},Restoration_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=true,AutoTargetStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(57 + 3),InterruptPercentChannel=(1534 - (1329 + 145))}}};
v3.HRGUIGet().LoadSettingsRecursively(v11);
local v13 = v3.HRGUIGet().Panel;
local v14 = v5(v13, "Shaman");
local v15 = v5(v14, "Enhancement");
local v16 = v5(v15, "Defensives");
local v17 = v5(v15, "Interrupt");
v8(v17, "APL.Shaman.Enhancement_Interrupt");
local v18 = v5(v15, "TTD");
local v19 = v5(v15, "Cooldown settings");
local v20 = v5(v14, "Elemental");
local v21 = v5(v20, "Defensives");
local v22 = v5(v20, "Interrupt");
v8(v22, "APL.Shaman.Elemental_Interrupt");
local v23 = v5(v20, "TTD");
local v24 = v5(v20, "Cooldown settings");
local v25 = v5(v14, "Restoration");
local v26 = v5(v25, "Interrupt");
v8(v26, "APL.Shaman.Restoration_Interrupt");
local v27 = v5(v25, "Healing");
local v28 = v5(v25, "Cooldowns");
local v29 = v5(v25, "AoE Healing");
local v30 = v5(v25, "AoE Healing 2");
local v31 = v5(v25, "Raid Healing");
local v32 = v5(v25, "Raid AoE Healing");
local v33 = v5(v25, "Raid AoE Healing 2");
local v34 = {"With Cooldowns","With Logic","With Cooldowns and Logic","Not Used"};
local v35 = {"Not Used","always","with Cooldowns","small CDs","with Cooldowns or AoE","on Enemycount or Cooldowns","on Boss or with Cooldowns","on Boss only","with Bloodlust only","on AOE","on Enemycount","on Boss or on Enemycount"};
v8(v14, "APL.Shaman.Commons");
v6("CheckButton", v14, "APL.Shaman.Commons.TabForPurge", "Purge Auto Tab", "Enable this if you want the addon to auto tab for Purge");
v6("Dropdown", v14, "APL.Shaman.Commons.SkyFury", {"dont use","only check us","check whole group"}, "SkyFury", "Decide if we want to use SkyFury and who to check for the Buff.");
v6("Dropdown", v14, "APL.Shaman.Commons.AutoWolf", {"never","Only out of combat","Only in Combat","always"}, "AutoWolf", "Choose when to auto use Ghost Wolf.");
v8(v15, "APL.Shaman.Enhancement");
v6("CheckButton", v15, "APL.Shaman.Enhancement.PreferEarthShield", "Prefer Earth Shield", "Prefer using Earth Shield over Lightning Shield, when it's available.");
v6("CheckButton", v15, "APL.Shaman.Enhancement.AutoTabDot", "Auto Tab for auto spreading Lashing Flames", "Enable this if you want the addon to auto Tab for spreading Lashing Flames.");
v6("CheckButton", v15, "APL.Shaman.Enhancement.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v6("CheckButton", v16, "APL.Shaman.Enhancement.Defensives.Earthshieldooc", "Earth Shield / Lightning Shield only out of Combat", "Enable this if you want the addon to only use Earth Shield out of combat.");
v6("Slider", v16, "APL.Shaman.Enhancement.Defensives.EarthElemental", {(0 + 0),(97 + 3),(1 - 0)}, "Earth Elemental", "Sets the health percentage under which Earth Elemental should be used. Set this to 0 to disable the use.");
v6("Slider", v16, "APL.Shaman.Enhancement.Defensives.InstantHealingSurgeHP", {(0 + 0),(496 - (115 + 281)),(1 + 0)}, "Healing Surge with 5 Maelstrom", "Sets the health percentage under which Healing Surge should be suggested with 5 Maelstrom. Set this to 0 to disable healing suggestions.");
v6("Slider", v16, "APL.Shaman.Enhancement.Defensives.HealingSurgeHP", {(0 - 0),(144 - 44),(2 - 1)}, "Healing Surge without 5 Maelstrom", "Sets the health percentage under which Healing Surge should be suggested when below 5 Maelstrom. Set this to 0 to disable healing suggestions.");
v6("Slider", v16, "APL.Shaman.Enhancement.Defensives.AstralShiftHP", {(1665 - (970 + 695)),(2090 - (582 + 1408)),(1 - 0)}, "Astral Shift", "Sets the health percentage under which Astral Shift should be suggested. Set this to 0 to disable healing suggestions.");
v6("Slider", v16, "APL.Shaman.Enhancement.Defensives.HealingStreamTotemHP", {(1824 - (1195 + 629)),(341 - (187 + 54)),(1 + 0)}, "Healing Stream Totem", "Sets the health percentage under which Healing Stream Totem should be suggested. Set this to 0 to disable healing suggestions.");
v6("Slider", v16, "APL.Shaman.Enhancement.Defensives.StoneBulkwarkTotemHP", {(0 - 0),(8 + 92),(1001 - (451 + 549))}, "Stone Bulkwark Totem", "Sets the health percentage under which Stone Bulkwark Totem should be suggested. Set this to 0 to disable healing suggestions.");
v6("Slider", v16, "APL.Shaman.Enhancement.Defensives.AncestralGuidanceHP", {(0 - 0),(1484 - (746 + 638)),(1 - 0)}, "Ancestral Guidance HP", "Set the HP threshold of when you want the addon to suggest defensive usgae of Ancestral Guidance. (Set to 0 to disable)");
v6("Slider", v16, "APL.Shaman.Enhancement.Defensives.AncestralGuidanceCount", {(1581 - (1535 + 46)),(1 + 4),(1 + 0)}, "Ancestral Guidance Count", "Set the Unit Count threshold to Cast Ancestral Guidance.");
v8(v16, "APL.Shaman.Enhancement.Defensives");
v6("CheckButton", v18, "APL.Shaman.Enhancement_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v18, "APL.Shaman.Enhancement_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v18, "APL.Shaman.Enhancement_TTD.RacialsTTD", {(1467 - (899 + 568)),(145 - 85),(291 - (60 + 230))}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v18, "APL.Shaman.Enhancement_TTD.TrinketsTTD", {(0 + 0),(871 - (569 + 242)),(1 + 0)}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v18, "APL.Shaman.Enhancement_TTD.SunderingTTD", {(1251 - (721 + 530)),(149 - 89),(701 - (271 + 429))}, "Sundering TTD", "Time to die to use Sundering");
v6("Slider", v18, "APL.Shaman.Enhancement_TTD.FeralSpiritTTD", {(1500 - (1408 + 92)),(1348 - (993 + 295)),(1172 - (418 + 753))}, "Feral Spirit TTD", "Time to die to use Feral Spirit");
v6("Slider", v18, "APL.Shaman.Enhancement_TTD.AscendanceTTD", {(0 + 0),(16 + 44),(1770 - (1749 + 20))}, "Ascendance TTD", "Time to die to use Ascendance");
v6("Slider", v18, "APL.Shaman.Enhancement_TTD.PrimordialWaveTTD", {(1322 - (1249 + 73)),(1205 - (466 + 679)),(2 - 1)}, "Primordial Wave TTD", "Time to die to use Primordial Wave");
v6("Slider", v18, "APL.Shaman.Enhancement_TTD.DoomWindsTTD", {(0 + 0),(177 - 117),(115 - (4 + 110))}, "Doom Winds TTD", "Time to die to use Doom Winds");
v6("Slider", v18, "APL.Shaman.Enhancement_TTD.PotionsTTD", {(1427 - (41 + 1386)),(41 + 19),(2 - 1)}, "Potions TTD", "Time to die to use DPS Potions");
v6("Slider", v18, "APL.Shaman.Enhancement_TTD.TempestTTD", {(0 - 0),(49 + 11),(1 - 0)}, "Tempest TTD", "Time to die to use Tempest");
v6("Slider", v18, "APL.Shaman.Enhancement_TTD.SurgingTotemTTD", {(0 + 0),(226 - 166),(2 - 1)}, "Surging Totem TTD", "Time to die to use Surging Totem");
v8(v18, "APL.Shaman.Enhancement_TTD");
v6("CheckButton", v19, "APL.Shaman.Enhancement_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v19, "APL.Shaman.Enhancement_CDUSE.Enemycount", {(322 - (53 + 267)),(423 - (15 + 398)),(3 - 2)}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.Racials", v35, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.Potions", v35, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v19, "APL.Shaman.Enhancement_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.Trinket1", v35, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.Trinket2", v35, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.Ascendance", v35, "Ascendance", "Choose an option on when to use Ascendance");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.DoomWinds", v35, "Doom Winds", "Choose an option on when to use Doom Winds");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.FeralSpirit", v35, "Feral Spirit", "Choose an option on when to use Feral Spirit");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.EarthElemental", v35, "Earth Elemental", "Choose an option on when to use Earth Elemental");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.Sundering", v35, "Sundering", "Choose an option on when to use Sundering");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.FireNova", v35, "Fire Nova", "Choose an option on when to use Fire Nova");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.IceStrike", v35, "Ice Strike", "Choose an option on when to use Ice Strike");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.PrimordialWave", v35, "Primordial Wave", "Choose an option on when to use Primordial Wave");
v6("Dropdown", v19, "APL.Shaman.Enhancement_CDUSE.SurgingTotem", v35, "Surging Totem", "Choose an option on when to use Surging Totem");
v8(v19, "APL.Shaman.Enhancement_CDUSE");
v8(v20, "APL.Shaman.Elemental");
v6("CheckButton", v20, "APL.Shaman.Elemental.PreferEarthShield", "Prefer Earth Shield", "Prefer using Earth Shield over Lightning Shield, when it's available.");
v6("CheckButton", v20, "APL.Shaman.Elemental.ShowMovementSpells", "Show Movement Spells", "Show Flame Shock and Frost Shock suggestions while moving. Note: This tends to make the rotation choppy when making small movements.");
v6("CheckButton", v20, "APL.Shaman.Elemental.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v6("CheckButton", v20, "APL.Shaman.Elemental.CursorCheck", "Cursor Check", "Will check if an Enemy is at the cursor Place currently before fireing Placeable Spells.");
v6("CheckButton", v20, "APL.Shaman.Elemental.ForceAOE", "AoE toggle forced", "The AoE toggle is now forcing aoe to be used and ignore the target count.");
v6("CheckButton", v21, "APL.Shaman.Elemental.Defensives.Earthshieldooc", "Earth Shield / Lightning Shield only out of Combat", "Enable this if you want the addon to only use Earth Shield out of combat.");
v6("Slider", v21, "APL.Shaman.Elemental.Defensives.EarthElemental", {(0 + 0),(79 + 21),(1 + 0)}, "Earth Elemental", "Sets the health percentage under which Earth Elemental should be used. Set this to 0 to disable the use.");
v6("Slider", v21, "APL.Shaman.Elemental.Defensives.HealingSurgeHP", {(0 - 0),(51 + 49),(2 - 1)}, "Healing Surge", "Sets the health percentage under which Healing Surge should be suggested when below 5 Maelstrom. Set this to 0 to disable healing suggestions.");
v6("Slider", v21, "APL.Shaman.Elemental.Defensives.AstralShiftHP", {(1551 - (1126 + 425)),(391 - 291),(2 - 1)}, "Astral Shift", "Sets the health percentage under which Astral Shift should be suggested. Set this to 0 to disable healing suggestions.");
v6("Slider", v21, "APL.Shaman.Elemental.Defensives.HealingStreamTotemHP", {(0 - 0),(1077 - (553 + 424)),(1 + 0)}, "Healing Stream Totem", "Sets the health percentage under which Healing Stream Totem should be suggested. Set this to 0 to disable healing suggestions.");
v6("Slider", v21, "APL.Shaman.Elemental.Defensives.StoneBulkwarkTotemHP", {(0 + 0),(58 + 42),(2 - 1)}, "Stone Bulkwark Totem", "Sets the health percentage under which Stone Bulkwark Totem should be suggested. Set this to 0 to disable healing suggestions.");
v6("Slider", v21, "APL.Shaman.Elemental.Defensives.AncestralGuidanceHP", {(0 + 0),(853 - (239 + 514)),(1330 - (797 + 532))}, "Ancestral Guidance HP", "Set the HP threshold of when you want the addon to suggest defensive usgae of Ancestral Guidance. (Set to 0 to disable)");
v6("Slider", v21, "APL.Shaman.Elemental.Defensives.AncestralGuidanceCount", {(0 + 0),(1207 - (373 + 829)),(1131 - (369 + 761))}, "Ancestral Guidance Count", "Set the Unit Count threshold to Cast Ancestral Guidance.");
v8(v21, "APL.Shaman.Elemental.Defensives");
v6("CheckButton", v23, "APL.Shaman.Elemental_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v23, "APL.Shaman.Elemental_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v23, "APL.Shaman.Elemental_TTD.RacialsTTD", {(0 - 0),(298 - (64 + 174)),(1 - 0)}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v23, "APL.Shaman.Elemental_TTD.TrinketsTTD", {(216 - (42 + 174)),(50 + 10),(1505 - (363 + 1141))}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v23, "APL.Shaman.Elemental_TTD.FireElementalTTD", {(0 - 0),(45 + 15),(1 + 0)}, "Fire/Storm Elemental TTD", "Time to die to use Fire/Storm Elemental");
v6("Slider", v23, "APL.Shaman.Elemental_TTD.StormkeeperTTD", {(1933 - (565 + 1368)),(1721 - (1477 + 184)),(1 + 0)}, "Stormkeeper TTD", "Time to die to use Stormkeeper");
v6("Slider", v23, "APL.Shaman.Elemental_TTD.AscendanceTTD", {(0 - 0),(364 - (244 + 60)),(477 - (41 + 435))}, "Ascendance TTD", "Time to die to use Ascendance");
v6("Slider", v23, "APL.Shaman.Elemental_TTD.PrimordialWaveTTD", {(0 + 0),(20 + 40),(1 + 0)}, "Primordial Wave TTD", "Time to die to use Primordial Wave");
v6("Slider", v23, "APL.Shaman.Elemental_TTD.LiquidMagmaTotemTTD", {(267 - (176 + 91)),(88 - 28),(1876 - (157 + 1718))}, "Liquid Magma Totem TTD", "Time to die to use Liquid Magma Totem");
v6("Slider", v23, "APL.Shaman.Elemental_TTD.PotionsTTD", {(0 - 0),(1078 - (697 + 321)),(1 - 0)}, "Potions TTD", "Time to die to use DPS Potions");
v6("Slider", v23, "APL.Shaman.Elemental_TTD.TempestTTD", {(0 + 0),(160 - 100),(612 - (602 + 9))}, "Tempest TTD", "Time to die to use Tempest");
v8(v23, "APL.Shaman.Elemental_TTD");
v6("CheckButton", v24, "APL.Shaman.Elemental_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v24, "APL.Shaman.Elemental_CDUSE.Enemycount", {(874 - (826 + 46)),(31 - 21),(1899 - (260 + 1638))}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.Racials", v35, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.Potions", v35, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v24, "APL.Shaman.Elemental_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.Trinket1", v35, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.Trinket2", v35, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.Ascendance", v35, "Ascendance", "Choose an option on when to use Ascendance");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.NaturesSwiftness", v35, "Natures Swiftness", "Choose an option on when to use Natures Swiftness");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.FireElemental", v35, "Fire Elemental", "Choose an option on when to use Fire Elemental");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.EarthElemental", v35, "Earth Elemental", "Choose an option on when to use Earth Elemental");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.StormElemental", v35, "Storm Elemental", "Choose an option on when to use Storm Elemental");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.Stormkeeper", v35, "Stormkeeper", "Choose an option on when to use Stormkeeper");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.LiquidMagmaTotem", v35, "Liquid Magma Totem", "Choose an option on when to use Liquid Magma Totem");
v6("Dropdown", v24, "APL.Shaman.Elemental_CDUSE.PrimordialWave", v35, "Primordial Wave", "Choose an option on when to use Primordial Wave");
v8(v24, "APL.Shaman.Elemental_CDUSE");
v6("Slider", v25, "APL.Shaman.Restoration.AstralShiftHP", {(0 - 0),(206 - 106),(1206 - (902 + 303))}, "Astral Shift Threshold", "Sets the health percentage under which Astral Shift should be used");
v6("CheckButton", v25, "APL.Shaman.Restoration.SpiritwalkersGrace", "Spiritwalkers Grace", "Would you like to use Spiritwalkers Grace while moving?");
v6("CheckButton", v25, "APL.Shaman.Restoration.EarthlivingWeapon", "Earthliving Weapon", "Would you like to use Earthliving Weapon out of Combat?");
v6("CheckButton", v25, "APL.Shaman.Restoration.TotemRecall", "Totemic Recall", "Use Totem Recall?");
v6("CheckButton", v25, "APL.Shaman.Restoration.AttackOOC", "Attack with OOC", "Attack not in Combat?");
v6("Dropdown", v28, "APL.Shaman.Restoration.Cooldowns.UseAG", v34, "Use Ancestral Guidance", "How would you like to use this Cooldown?");
v6("Dropdown", v28, "APL.Shaman.Restoration.Cooldowns.UseAscendance", v34, "Use Ascendance", "How would you like to use this Cooldown?");
v6("Dropdown", v28, "APL.Shaman.Restoration.Cooldowns.EarthEle", v34, "Use Earth Elemental", "How would you like to use this Cooldown?");
v6("Dropdown", v28, "APL.Shaman.Restoration.Cooldowns.Stormkeeper", v34, "Use Stormkeeper", "How would you like to use this Cooldown?");
v6("Dropdown", v28, "APL.Shaman.Restoration.Cooldowns.Trinket1Use", v34, "Trinket 1 Usage", "How would you like to use this Cooldown?");
v6("Dropdown", v28, "APL.Shaman.Restoration.Cooldowns.Trinket2Use", v34, "Trinket 2  Usage", "How would you like to use this Cooldown?");
v6("Slider", v28, "APL.Shaman.Restoration.Cooldowns.Trinket1HP", {(0 - 0),(1790 - (1121 + 569)),(684 - (483 + 200))}, "Trinket 1 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("Slider", v28, "APL.Shaman.Restoration.Cooldowns.Trinket2HP", {(0 - 0),(865 - (468 + 297)),(3 - 2)}, "Trinket 2 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("Slider", v30, "APL.Shaman.Restoration.AoE.AscendanceHP", {(0 - 0),(336 - (141 + 95)),(2 - 1)}, "Ascendance HP", "HP for abiltiy to be used");
v6("Slider", v30, "APL.Shaman.Restoration.AoE.AscendanceCount", {(0 + 0),(4 + 1),(1 - 0)}, "Ascendance Count", "Unit Count for abiltiy to be used");
v6("Slider", v30, "APL.Shaman.Restoration.AoE.AGHP", {(163 - (92 + 71)),(168 - 68),(1 + 0)}, "Ancestral Guidance HP", "HP for abiltiy to be used");
v6("Slider", v30, "APL.Shaman.Restoration.AoE.AGCount", {(0 + 0),(131 - (55 + 71)),(1791 - (573 + 1217))}, "Ancestral GuidanceCount", "Unit Count for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.ChainHealHighTideHP", {(0 + 0),(1039 - (714 + 225)),(1 - 0)}, "CH With Hightide HP", "HP for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.ChainHealHighTideCount", {(0 - 0),(53 - (25 + 23)),(1887 - (927 + 959))}, "CH With Hightide Count", "Unit Count for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.ChainHealHP", {(732 - (16 + 716)),(197 - (11 + 86)),(286 - (175 + 110))}, "Chain Heal HP", "HP for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.ChainHealCount", {(0 - 0),(13 - 8),(1062 - (810 + 251))}, "Chain Heal Count", "Unit Count for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.CloudBurstHP", {(0 + 0),(633 - (43 + 490)),(3 - 2)}, "Cloudburst/Healing Stream HP", "HP for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.CloudBurstCount", {(0 + 0),(1 + 4),(406 - (255 + 150))}, "Cloudburst/Healing Stream Count", "Unit Count for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.CloudBurstRecastHP", {(0 + 0),(322 - 222),(407 - (183 + 223))}, "Cloudburst Recast HP", "HP for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.CloudBurstRecastCount", {(0 + 0),(342 - (10 + 327)),(339 - (118 + 220))}, "Cloudburst Recast Count", "Unit Count for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.EarthenWallHP", {(449 - (108 + 341)),(422 - 322),(1 - 0)}, "Earthen Wall HP", "HP for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.EarthenWallCount", {(0 + 0),(14 - 9),(1 + 0)}, "Earthen Wall Count", "Unit Count for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.HealingRainHP", {(0 - 0),(1267 - (645 + 522)),(1 + 0)}, "Healing Rain HP", "HP for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.HealingRainCount", {(0 - 0),(12 - 7),(506 - (351 + 154))}, "Healing Rain Count", "Unit Count for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.HealingTideHP", {(266 - (28 + 238)),(1659 - (1381 + 178)),(1 + 0)}, "Healing Tide HP", "HP for abiltiy to be used");
v6("Slider", v29, "APL.Shaman.Restoration.AoE.HealingTideCount", {(0 - 0),(475 - (381 + 89)),(1 + 0)}, "Healing Tide Count", "Unit Count for abiltiy to be used");
v6("Slider", v30, "APL.Shaman.Restoration.AoE.SpiritLinkHP", {(1156 - (1074 + 82)),(1884 - (214 + 1570)),(1 + 0)}, "Spirit Link Totem HP", "HP for abiltiy to be used");
v6("Slider", v30, "APL.Shaman.Restoration.AoE.SpiritLinkCount", {(0 + 0),(1731 - (1668 + 58)),(2 - 1)}, "Spirit Link Totem Count", "Unit Count for abiltiy to be used");
v6("Slider", v30, "APL.Shaman.Restoration.AoE.WellspringHP", {(0 - 0),(19 + 81),(3 - 2)}, "Wellspring HP", "HP for abiltiy to be used");
v6("Slider", v30, "APL.Shaman.Restoration.AoE.WellspringCount", {(1469 - (1269 + 200)),(820 - (98 + 717)),(1 - 0)}, "Wellspring Count", "Unit Count for abiltiy to be used");
v6("Slider", v27, "APL.Shaman.Restoration.Healing.HealingSurgeHP", {(0 + 0),(17 + 83),(2 - 1)}, "Healing Surge HP", "HP Threshold for abiltiy to be used");
v6("Slider", v27, "APL.Shaman.Restoration.Healing.HealingSurgeTankHP", {(0 + 0),(83 + 17),(1 + 0)}, "Healing Surge Tank HP", "HP Threshold for abiltiy to be used");
v6("Slider", v27, "APL.Shaman.Restoration.Healing.HealingWaveHP", {(0 - 0),(35 + 65),(1 + 0)}, "Healing Wave HP", "HP Threshold for abiltiy to be used");
v6("Slider", v27, "APL.Shaman.Restoration.Healing.HealingWaveTankHP", {(326 - (192 + 134)),(56 + 44),(1 + 0)}, "Healing Wave Tank HP", "HP Threshold for abiltiy to be used");
v6("Slider", v27, "APL.Shaman.Restoration.Healing.ManaTideMP", {(551 - (83 + 468)),(466 - 366),(2 - 1)}, "Mana Tide MP", "MP Threshold for abiltiy to be used");
v6("Slider", v27, "APL.Shaman.Restoration.Healing.PrimordiaWaveHP", {(0 + 0),(37 + 63),(1 + 0)}, "Primoridal Wave HP", "HP Threshold for abiltiy to be used");
v6("Slider", v27, "APL.Shaman.Restoration.Healing.RiptideHP", {(1911 - (340 + 1571)),(1872 - (1733 + 39)),(1035 - (125 + 909))}, "Riptide HP", "HP Threshold for abiltiy to be used");
v6("Slider", v27, "APL.Shaman.Restoration.Healing.UnleashLifeHP", {(0 + 0),(97 + 3),(237 - (46 + 190))}, "Unleash Life HP", "HP Threshold for abiltiy to be used");
v6("Dropdown", v27, "APL.Shaman.Restoration.Healing.WhichUndulation", {"Healing Wave","Healing Surge"}, "Which Spell for Undulation/Nature Swiftness", "How would you like to use this Cooldown?");
v6("Slider", v27, "APL.Shaman.Restoration.Healing.NSHP", {(726 - (228 + 498)),(56 + 44),(2 - 1)}, "Nature's Swiftness/Undulation HP", "HP Threshold for abiltiy to be used");
v6("Slider", v33, "APL.Shaman.Restoration.RaidAoE.AscendanceHP", {(524 - (303 + 221)),(84 + 16),(4 - 3)}, "Ascendance HP", "Avg HP for abiltiy to be used");
v6("Slider", v33, "APL.Shaman.Restoration.RaidAoE.AscendanceCount", {(0 - 0),(140 - 100),(1 - 0)}, "Ascendance Count", "Unit Count for abiltiy to be used");
v6("Slider", v33, "APL.Shaman.Restoration.RaidAoE.AGHP", {(1248 - (111 + 1137)),(297 - 197),(524 - (423 + 100))}, "Ancestral Guidance HP", "HP for abiltiy to be used");
v6("Slider", v33, "APL.Shaman.Restoration.RaidAoE.AGCount", {(0 - 0),(811 - (326 + 445)),(2 - 1)}, "Ancestral GuidanceCount", "Unit Count for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.ChainHealHighTideHP", {(711 - (530 + 181)),(132 - (19 + 13)),(2 - 1)}, "CH With Hightide HP", "HP for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.ChainHealHighTideCount", {(0 + 0),(82 - 42),(1 - 0)}, "CH With Hightide Count", "Unit Count for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.ChainHealHP", {(0 - 0),(235 - 135),(1 + 0)}, "Chain Heal HP", "HP for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.ChainHealCount", {(0 + 0),(25 + 15),(1859 - (673 + 1185))}, "Chain Heal Count", "Unit Count for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.CloudBurstHP", {(0 - 0),(72 + 28),(1 - 0)}, "Cloudburst/Healing Stream HP", "HP for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.CloudBurstCount", {(0 - 0),(1920 - (446 + 1434)),(2 - 1)}, "Cloudburst/Healing Stream Count", "Unit Count for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.CloudBurstRecastHP", {(1931 - (609 + 1322)),(373 - 273),(4 - 3)}, "Cloudburst Recast HP", "HP for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.CloudBurstRecastCount", {(0 - 0),(18 + 22),(1 + 0)}, "Cloudburst Recast Count", "Unit Count for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.EarthenWallHP", {(0 + 0),(72 + 28),(1 + 0)}, "Earthen Wall HP", "HP for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.EarthenWallCount", {(0 - 0),(16 + 24),(1 + 0)}, "Earthen Wall Count", "Unit Count for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.HealingRainHP", {(0 - 0),(767 - (89 + 578)),(1 - 0)}, "Healing Rain HP", "HP for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.HealingRainCount", {(0 + 0),(5 + 35),(1 - 0)}, "Healing Rain Count", "Unit Count for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.HealingTideHP", {(842 - (497 + 345)),(17 + 83),(1 + 0)}, "Healing Tide HP", "HP for abiltiy to be used");
v6("Slider", v32, "APL.Shaman.Restoration.RaidAoE.HealingTideCount", {(0 + 0),(37 + 3),(1 + 0)}, "Healing Tide Count", "Unit Count for abiltiy to be used");
v6("Slider", v33, "APL.Shaman.Restoration.RaidAoE.SpiritLinkHP", {(0 + 0),(95 + 5),(3 - 2)}, "Spirit Link Totem HP", "HP for abiltiy to be used");
v6("Slider", v33, "APL.Shaman.Restoration.RaidAoE.SpiritLinkCount", {(796 - (588 + 208)),(1840 - (884 + 916)),(1 + 0)}, "Spirit Link Totem Count", "Unit Count for abiltiy to be used");
v6("Slider", v33, "APL.Shaman.Restoration.RaidAoE.WellspringHP", {(1889 - (1569 + 320)),(19 + 81),(606 - (316 + 289))}, "Wellspring HP", "HP for abiltiy to be used");
v6("Slider", v33, "APL.Shaman.Restoration.RaidAoE.WellspringCount", {(0 + 0),(465 - (360 + 65)),(255 - (79 + 175))}, "Wellspring Count", "Unit Count for abiltiy to be used");
v6("Slider", v31, "APL.Shaman.Restoration.RaidHealing.HealingSurgeHP", {(0 + 0),(192 - 92),(182 - (92 + 89))}, "Healing Surge HP", "HP Threshold for abiltiy to be used");
v6("Slider", v31, "APL.Shaman.Restoration.RaidHealing.HealingSurgeTankHP", {(0 + 0),(391 - 291),(2 - 1)}, "Healing Surge Tank HP", "HP Threshold for abiltiy to be used");
v6("Slider", v31, "APL.Shaman.Restoration.RaidHealing.HealingWaveHP", {(0 + 0),(13 + 87),(1245 - (485 + 759))}, "Healing Wave HP", "HP Threshold for abiltiy to be used");
v6("Slider", v31, "APL.Shaman.Restoration.RaidHealing.HealingWaveTankHP", {(1189 - (442 + 747)),(1046 - (88 + 858)),(1 + 0)}, "Healing Wave Tank HP", "HP Threshold for abiltiy to be used");
v6("Slider", v31, "APL.Shaman.Restoration.RaidHealing.ManaTideMP", {(789 - (766 + 23)),(136 - 36),(3 - 2)}, "Mana Tide MP", "MP Threshold for abiltiy to be used");
v6("Slider", v31, "APL.Shaman.Restoration.RaidHealing.PrimordiaWaveHP", {(0 + 0),(79 + 21),(914 - (910 + 3))}, "Primoridal Wave HP", "HP Threshold for abiltiy to be used");
v6("Slider", v31, "APL.Shaman.Restoration.RaidHealing.RiptideHP", {(1684 - (1466 + 218)),(1248 - (556 + 592)),(809 - (329 + 479))}, "Riptide HP", "HP Threshold for abiltiy to be used");
v6("Slider", v31, "APL.Shaman.Restoration.RaidHealing.UnleashLifeHP", {(0 - 0),(72 + 28),(1 + 0)}, "Unleash Life HP", "HP Threshold for abiltiy to be used");
v6("Dropdown", v31, "APL.Shaman.Restoration.RaidHealing.WhichUndulation", {"Healing Wave","Healing Surge"}, "Which Spell for Undulation/Nature Swiftness", "How would you like to use this Cooldown?");
v6("Slider", v31, "APL.Shaman.Restoration.RaidHealing.NSHP", {(0 - 0),(1627 - (389 + 1138)),(1 + 0)}, "Nature's Swiftness/Undulation HP", "HP Threshold for abiltiy to be used");
v8(v28, "APL.Shaman.Restoration.Cooldowns");
v8(v29, "APL.Shaman.Restoration.AoE");
v8(v27, "APL.Shaman.Restoration.Healing");
v8(v32, "APL.Shaman.Restoration.RaidAoE");
v8(v31, "APL.Shaman.Restoration.RaidHealing");
v8(v25, "APL.Shaman.Restoration");
v11.APL.Shaman.Enhancement.Display = function()
	v2.GUI.HidePanel(v25);
	v2.GUI.HidePanel(v29);
	v2.GUI.HidePanel(v30);
	v2.GUI.HidePanel(v28);
	v2.GUI.HidePanel(v27);
	v2.GUI.HidePanel(v20);
	v2.GUI.HidePanel(v21);
	v2.GUI.HidePanel(v22);
	v2.GUI.HidePanel(v23);
	v2.GUI.HidePanel(v24);
	v2.GUI.HidePanel(v10);
	v2.GUI.HidePanel(v31);
	v2.GUI.HidePanel(v32);
	v2.GUI.HidePanel(v33);
	v2.GUI.HidePanel(v26);
	v2.GUI.ShowPanel(v15);
	v2.GUI.ShowPanel(v16);
	v2.GUI.ShowPanel(v17);
	v2.GUI.ShowPanel(v18);
	v2.GUI.ShowPanel(v19);
end;
v11.APL.Shaman.Elemental.Display = function()
	v2.GUI.HidePanel(v25);
	v2.GUI.HidePanel(v29);
	v2.GUI.HidePanel(v30);
	v2.GUI.HidePanel(v28);
	v2.GUI.HidePanel(v27);
	v2.GUI.HidePanel(v15);
	v2.GUI.HidePanel(v16);
	v2.GUI.HidePanel(v17);
	v2.GUI.HidePanel(v18);
	v2.GUI.HidePanel(v19);
	v2.GUI.HidePanel(v10);
	v2.GUI.HidePanel(v31);
	v2.GUI.HidePanel(v32);
	v2.GUI.HidePanel(v33);
	v2.GUI.HidePanel(v26);
	v2.GUI.ShowPanel(v20);
	v2.GUI.ShowPanel(v21);
	v2.GUI.ShowPanel(v22);
	v2.GUI.ShowPanel(v23);
	v2.GUI.ShowPanel(v24);
end;
v11.APL.Shaman.Restoration.Display = function()
	v2.GUI.ShowPanel(v25);
	v2.GUI.ShowPanel(v29);
	v2.GUI.ShowPanel(v30);
	v2.GUI.ShowPanel(v28);
	v2.GUI.ShowPanel(v27);
	v2.GUI.ShowPanel(v31);
	v2.GUI.ShowPanel(v32);
	v2.GUI.ShowPanel(v33);
	v2.GUI.ShowPanel(v26);
	v2.GUI.HidePanel(v15);
	v2.GUI.HidePanel(v16);
	v2.GUI.HidePanel(v17);
	v2.GUI.HidePanel(v18);
	v2.GUI.HidePanel(v19);
	v2.GUI.HidePanel(v10);
	v2.GUI.HidePanel(v20);
	v2.GUI.HidePanel(v21);
	v2.GUI.HidePanel(v22);
	v2.GUI.HidePanel(v23);
	v2.GUI.HidePanel(v24);
end;
