local v0, v1 = ...;
local v2 = HeroRotation();
local v3 = HeroLib;
local v4 = v3.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v2.HRGUIGet().CreateARPanelOption;
local v8 = v2.HRGUIGet().CreateARPanelOptions;
local v9 = v4.GetPanelByName("Interrupt");
local v10 = v2.GUISettingsGet();
v10.APL.Hunter = {Commons={Enabled={Potions=true,Trinkets=true,Items=true},KillShot=false,SerpentSting=false,AttackOutOfCombat="Solo",UseMisdirection="On Combat Start",TabForTranquilizingShot=false,HuntersMark="On Bosses",HighExplsoiveTrap=true,ImplosiveTrap=true,BurstingShot=true},Defensives={ExhilarationHP=(156 - 106),SurvivalOfTheFittestHP=(200 - 130),AspectOfTheTurtleHP=(38 - 18),FeignDeathHP=(25 - 15),FeignDeathOnSpell=true,FortitudeOfTheBearHP=(669 - (555 + 64))},BeastMastery={PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},BarbedShot=false,RecommendBarbedShot=false,Mobcount=(933 - (857 + 74)),RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",PotionSetting="With Cooldowns",BestialWrathSetting="With Cooldowns",BloodshedSetting="With Cooldowns",CallOfTheWildSetting="With Cooldowns",StampedeSetting="With Cooldowns",BarrageSetting="With Cooldowns"},BeastMastery_TTD={IgnoreTTD=true,RacialsTTD=(588 - (367 + 201)),TrinketsTTD=(947 - (214 + 713)),BestialWrathTTD=(4 + 11),AMurderOfCrowsTTD=(4 + 16),BloodshedTTD=(892 - (282 + 595)),CallOfTheWildTTD=(1657 - (1523 + 114))},BMPet={SummonPetSlot=(1 + 0),MendPetHP=(57 - 17),WhenSummonPet="Always",SpiritMend=(1115 - (68 + 997))},Marksmanship={PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},Mobcount=(1272 - (226 + 1044)),RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",TrueshotSetting="With Cooldowns",PotionSetting="With Cooldowns",VolleySetting="With Cooldowns",SalvoSetting="With Cooldowns",RapidFireSetting="Always",CursorCheck=false},Marksmanship_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(261 - 201),InterruptPercentChannel=(177 - (32 + 85))}},Marksmanship_TTD={RacialsTTD=(20 + 0),TrinketsTTD=(5 + 15),TrueshotTTD=(982 - (892 + 65))},MMPet={SummonPetSlot=(2 - 1),SoloPet=false,WhenSummonPet="Always",MendPetHP=(73 - 33)},Survival={AspectoftheEagle=true,CAKSMacro=false,Mobcount=(3 - 1),UseHarpoon=true,RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",PotionSetting="With Cooldowns",FuryoftheEagleSetting="With Cooldowns",CoordinatedAssaultSetting="With Cooldowns",SpearheadSetting="With Cooldowns",DjaruunSetting="With Cooldowns",FlankingStrikeSetting="Always",PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},GCDasOffGCD={Harpoon=true}},Survival_TTD={RacialsTTD=(370 - (87 + 263)),TrinketsTTD=(200 - (67 + 113)),FuryoftheEagleTTD=(11 + 4),CoordinatedAssaultTTD=(49 - 29),SpearheadTTD=(15 + 5)},Survival_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(238 - 178),InterruptPercentChannel=(1012 - (802 + 150))}},SVPet={SummonPetSlot=(2 - 1),MendPetHP=(72 - 32),WhenSummonPet="Always"}};
v2.HRGUIGet().LoadSettingsRecursively(v10);
local v12 = {"Not Used","Always","With Cooldowns","With Small or Cooldowns","On Mobcount","On Mobcount or Cooldowns","On Bosses","Mobcount or Boss","With Bloodlust only"};
local v13 = {"Not Used","Solo","On Combat Start","On AoE","Always"};
local v14 = {"Not Used","On Bosses","Always"};
local v15 = {"Never","Solo","Always"};
local v16 = {"Never","Out of combat","In combat","Always"};
local v17 = v2.HRGUIGet().Panel;
local v18 = v5(v17, "Hunter");
local v19 = v5(v17, "Defensives");
local v20 = v5(v17, "BeastMastery");
local v21 = v5(v20, "TTD");
local v22 = v5(v20, "Pet");
local v23 = v5(v17, "Marksmanship");
local v24 = v5(v23, "Interrupt");
v8(v24, "APL.Hunter.Marksmanship_Interrupt");
local v25 = v5(v23, "TTD");
local v26 = v5(v23, "Pet");
local v27 = v5(v17, "Survival");
local v28 = v5(v27, "Interrupt");
local v29 = v5(v27, "TTD");
local v30 = v5(v27, "Pet");
v8(v28, "APL.Hunter.Survival_Interrupt");
v6("Dropdown", v18, "APL.Hunter.Commons.AttackOutOfCombat", v15, "Attack out of Combat", "Attack out of Combat");
v6("Dropdown", v18, "APL.Hunter.Commons.UseMisdirection", v13, "Misdirection usage", "Misdirection");
v6("Dropdown", v18, "APL.Hunter.Commons.HuntersMark", v14, "Hunter's Mark", "Hunter's Mark Settings");
v6("CheckButton", v18, "APL.Hunter.Commons.TabForTranq", "TranquilizingShot Auto Tab", "Enable this if you want the addon to auto tab for TranquilizingShot");
v6("CheckButton", v18, "APL.Hunter.Commons.ImplosiveTrap", "Implosive Trap", "Enable Implosive Trap");
v6("CheckButton", v18, "APL.Hunter.Commons.HighExplsoiveTrap", "High Explsoive Trap", "Enable High Explsoive Trap");
v6("CheckButton", v18, "APL.Hunter.Commons.BurstingShot", "Bursting Shot", "Enable Bursting Shot");
v8(v18, "APL.Hunter.Commons");
v6("Slider", v19, "APL.Hunter.Defensives.ExhilarationHP", {(1138 - (116 + 1022)),(59 + 41),(3 - 2)}, "Exhilaration HP", "Set the Exhilaration HP threshold. Set to 0 to disable.");
v6("Slider", v19, "APL.Hunter.Defensives.SurvivalOfTheFittestHP", {(0 - 0),(36 + 64),(1 - 0)}, "Survival of the Fittest HP", "Set the Survival of the Fittest HP threshold. Set to 0 to disable.");
v6("Slider", v19, "APL.Hunter.Defensives.AspectOfTheTurtleHP", {(1423 - (630 + 793)),(473 - 373),(3 - 2)}, "Aspect of the Turtle HP", "Set the Aspect of the Turtle HP threshold. Set to 0 to disable.");
v6("Slider", v19, "APL.Hunter.Defensives.FeignDeathHP", {(1913 - (1789 + 124)),(35 + 65),(3 - 2)}, "Feign Death HP", "Set the Feign Death HP threshold. Set to 0 to disable.");
v6("CheckButton", v19, "APL.Hunter.Defensives.FeignDeathOnSpell", "Feign Death on Spell", "Enable this if you want to use Feign Death on Spell");
v6("Slider", v19, "APL.Hunter.Defensives.FortitudeOfTheBearHP", {(0 + 0),(440 - 340),(2 - 1)}, "Fortitude of the Bear HP", "Set the Fortitude of the Bear HP threshold. Set to 0 to disable.");
v8(v19, "APL.Hunter.Defensives");
v6("CheckButton", v20, "APL.Hunter.BeastMastery.BarbedShot", "Barbed Shot Tab Multidot", "Tab to Multidot with Barbed Shot");
v6("CheckButton", v20, "APL.Hunter.BeastMastery.RecommendBarbedShot", "Recommend BS Target", "Recommend BS Target (you need to mouseover them)");
v6("Slider", v20, "APL.Hunter.BeastMastery.Mobcount", {(0 - 0),(761 - (376 + 325)),(2 - 1)}, "Mobcount", "Mobcount");
v6("Dropdown", v20, "APL.Hunter.BeastMastery.RacialsSetting", v12, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v20, "APL.Hunter.BeastMastery.Trinket1Setting", v12, "Trinket 1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v20, "APL.Hunter.BeastMastery.Trinket2Setting", v12, "Trinket 2 Usage", "Select how to use Trinket 2.");
v6("Dropdown", v20, "APL.Hunter.BeastMastery.PotionSetting", v12, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v20, "APL.Hunter.BeastMastery.BestialWrathSetting", v12, "Bestial Wrath Usage", "Select how to use Bestial Wrath.");
v6("Dropdown", v20, "APL.Hunter.BeastMastery.CallOfTheWildSetting", v12, "Call of the Wild Usage", "Select how to use Call of the Wild.");
v6("Dropdown", v20, "APL.Hunter.BeastMastery.BloodshedSetting", v12, "Bloodshed Usage", "Select how to use Bloodshed.");
v6("Dropdown", v20, "APL.Hunter.BeastMastery.StampedeSetting", v12, "Stampede Usage", "Select how to use Stampede.");
v6("Dropdown", v20, "APL.Hunter.BeastMastery.BarrageSetting", v12, "Barrage Usage", "Select how to use Barrage.");
v8(v20, "APL.Hunter.BeastMastery");
v6("CheckButton", v21, "APL.Hunter.BeastMastery_TTD.IgnoreTTD", "Ignore TTD on Dungeon Boss", "Will Ignore TTD on Dungeon Bosses");
v6("Slider", v21, "APL.Hunter.BeastMastery_TTD.RacialsTTD", {(0 - 0),(436 - (85 + 291)),(3 - 2)}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v21, "APL.Hunter.BeastMastery_TTD.TrinketsTTD", {(1180 - (1123 + 57)),(314 - (163 + 91)),(1 + 0)}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v21, "APL.Hunter.BeastMastery_TTD.BestialWrathTTD", {(0 - 0),(82 - 22),(1475 - (1329 + 145))}, "Bestial Wrath TTD", "TTD to use Bestial Wrath on Dungeon Mobs");
v6("Slider", v21, "APL.Hunter.BeastMastery_TTD.BloodshedTTD", {(1850 - (1409 + 441)),(28 + 32),(1722 - (345 + 1376))}, "Bloodshed TTD", "TTD to use Bloodshed on Dungeon Mobs");
v6("Slider", v21, "APL.Hunter.BeastMastery_TTD.CallOfTheWildTTD", {(0 - 0),(1266 - (696 + 510)),(1263 - (1091 + 171))}, "Call of the Wild TTD", "TTD to use Call of the Wild on Dungeon Mobs");
v8(v21, "APL.Hunter.BeastMastery_TTD");
v6("Slider", v22, "APL.Hunter.BMPet.MendPetHP", {(0 - 0),(474 - (123 + 251)),(699 - (208 + 490))}, "Mend Pet High HP", "Set the Mend Pet HP threshold. Set to 0 to disable.");
v6("Slider", v22, "APL.Hunter.BMPet.SummonPetSlot", {(0 + 0),(1 + 2),(676 - (534 + 141))}, "Summon Pet Slot", "Which pet stable slot to suggest when summoning a pet. 0 to disable.");
v6("Dropdown", v22, "APL.Hunter.BMPet.WhenSummonPet", v16, "When Summon Pet", "When do you want to use Pet?");
v6("Slider", v22, "APL.Hunter.BMPet.SpiritMend", {(0 + 0),(210 - 110),(2 - 1)}, "Spirit Mend", "Use Spirit Mend below %HP");
v8(v22, "APL.Hunter.BMPet");
v6("CheckButton", v23, "APL.Hunter.Marksmanship.CursorCheck", "CursorCheck", "Check if enemy is on cursor");
v6("Slider", v23, "APL.Hunter.Marksmanship.Mobcount", {(0 + 0),(139 - 79),(2 - 1)}, "Mobcount", "Mobcount");
v6("Dropdown", v23, "APL.Hunter.Marksmanship.RacialsSetting", v12, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v23, "APL.Hunter.Marksmanship.Trinket1Setting", v12, "Trinket 1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v23, "APL.Hunter.Marksmanship.Trinket2Setting", v12, "Trinket 2 Usage", "Select how to use Trinket 2.");
v6("Dropdown", v23, "APL.Hunter.Marksmanship.PotionSetting", v12, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v23, "APL.Hunter.Marksmanship.TrueshotSetting", v12, "Trueshot Usage", "Select how to use Trueshot.");
v6("Dropdown", v23, "APL.Hunter.Marksmanship.VolleySetting", v12, "Volley Usage", "Select how to use Volley.");
v6("Dropdown", v23, "APL.Hunter.Marksmanship.SalvoSetting", v12, "Salvo Usage", "Select how to use Salvo.");
v6("Dropdown", v23, "APL.Hunter.Marksmanship.RapidFireSetting", v12, "Rapid Fire Usage", "Select how to use Rapid Fire.");
v8(v23, "APL.Hunter.Marksmanship");
v6("Slider", v25, "APL.Hunter.Marksmanship_TTD.RacialsTTD", {(867 - (550 + 317)),(84 - 24),(286 - (134 + 151))}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v25, "APL.Hunter.Marksmanship_TTD.TrinketsTTD", {(0 - 0),(208 - 148),(3 - 2)}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v25, "APL.Hunter.Marksmanship_TTD.TrueshotTTD", {(0 - 0),(840 - (162 + 618)),(1 + 0)}, "Trueshot TTD", "TTD to use Trueshot on Dungeon Mobs");
v8(v25, "APL.Hunter.Marksmanship_TTD");
v6("Slider", v26, "APL.Hunter.MMPet.MendPetHP", {(0 - 0),(1736 - (1373 + 263)),(1 + 0)}, "Mend Pet High HP", "Set the Mend Pet HP threshold. Set to 0 to disable.");
v6("Slider", v26, "APL.Hunter.MMPet.SummonPetSlot", {(0 - 0),(2 + 1),(342 - (218 + 123))}, "Summon Pet Slot", "Which pet stable slot to suggest when summoning a pet. 0 to disable.");
v6("CheckButton", v26, "APL.Hunter.MMPet.SoloPet", "Summon Pet when solo", "Summon your Pet when you are doing Solo Content.");
v6("Dropdown", v26, "APL.Hunter.MMPet.WhenSummonPet", v16, "When Summon Pet", "When do you want to use Pet?");
v8(v26, "APL.Hunter.MMPet");
v6("CheckButton", v27, "APL.Hunter.Survival.AspectoftheEagle", "Use Aspect of the Eagle", "Use Aspect of the Eagle when out of Melee Range.");
v6("CheckButton", v27, "APL.Hunter.Survival.CAKSMacro", "Using Coordinated Assault Macro", "Enable this option to fix Kill Shot recommendations when you are using a Coordinated Assault/Kill Shot macro.");
v6("Slider", v27, "APL.Hunter.Survival.Mobcount", {(0 + 0),(620 - (306 + 254)),(1 - 0)}, "Mobcount", "Mobcount");
v6("CheckButton", v27, "APL.Hunter.Survival.UseHarpoon", "Use Harpoon", "Enable Harpoon");
v6("Dropdown", v27, "APL.Hunter.Survival.RacialsSetting", v12, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v27, "APL.Hunter.Survival.Trinket1Setting", v12, "Trinket 1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v27, "APL.Hunter.Survival.Trinket2Setting", v12, "Trinket 2 Usage", "Select how to use Trinket 2.");
v6("Dropdown", v27, "APL.Hunter.Survival.PotionSetting", v12, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v27, "APL.Hunter.Survival.FuryoftheEagleSetting", v12, "Fury of the Eagle Usage", "Select how to use Fury of the Eagle.");
v6("Dropdown", v27, "APL.Hunter.Survival.CoordinatedAssaultSetting", v12, "Coordinated Assault Usage", "Select how to use Coordinated Assault.");
v6("Dropdown", v27, "APL.Hunter.Survival.SpearheadSetting", v12, "Spearhead Usage", "Select how to use Spearhead.");
v6("Dropdown", v27, "APL.Hunter.Survival.FlankingStrikeSetting", v12, "Flanking Strike Usage", "Select how to use Flanking Strike.");
v6("Dropdown", v27, "APL.Hunter.Survival.DjaruunSetting", v12, "Djaruun Usage", "Select how to use Djaruun.");
v8(v27, "APL.Hunter.Survival");
v6("Slider", v29, "APL.Hunter.Survival_TTD.RacialsTTD", {(0 + 0),(663 - (268 + 335)),(573 - (426 + 146))}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v29, "APL.Hunter.Survival_TTD.TrinketsTTD", {(1456 - (282 + 1174)),(172 - 112),(1025 - (706 + 318))}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v29, "APL.Hunter.Survival_TTD.CoordinatedAssaultTTD", {(1271 - (945 + 326)),(54 + 6),(1 + 0)}, "CoordinatedAssault TTD", "TTD to use Coordinated Assault on Dungeon Mobs");
v6("Slider", v29, "APL.Hunter.Survival_TTD.FuryoftheEagleTTD", {(1086 - (461 + 625)),(4 + 56),(1 + 0)}, "Fury of the Eagle TTD", "TTD to use Fury of the Eagle on Dungeon Mobs");
v6("Slider", v29, "APL.Hunter.Survival_TTD.SpearheadTTD", {(0 + 0),(589 - (406 + 123)),(1 + 0)}, "Spearhead TTD", "TTD to use Fury of the Eagle on Dungeon Mobs");
v8(v29, "APL.Hunter.Survival_TTD");
v6("Slider", v30, "APL.Hunter.SVPet.MendPetHP", {(0 + 0),(240 - 140),(1901 - (106 + 1794))}, "Mend Pet High HP", "Set the Mend Pet HP threshold. Set to 0 to disable.");
v6("Slider", v30, "APL.Hunter.SVPet.SummonPetSlot", {(0 + 0),(7 - 4),(585 - (57 + 527))}, "Summon Pet Slot", "Which pet stable slot to suggest when summoning a pet. 0 to disable.");
v6("Dropdown", v30, "APL.Hunter.SVPet.WhenSummonPet", v16, "When Summon Pet", "When do you want to use Pet?");
v8(v30, "APL.Hunter.SVPet");
v10.APL.Hunter.BeastMastery.Display = function()
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v30);
	v3.GUI.ShowPanel(v20);
	v3.GUI.ShowPanel(v9);
	v3.GUI.ShowPanel(v21);
	v3.GUI.ShowPanel(v22);
end;
v10.APL.Hunter.Marksmanship.Display = function()
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v9);
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v30);
	v3.GUI.ShowPanel(v23);
	v3.GUI.ShowPanel(v24);
	v3.GUI.ShowPanel(v25);
	v3.GUI.ShowPanel(v26);
end;
v10.APL.Hunter.Survival.Display = function()
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v9);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v22);
	v3.GUI.ShowPanel(v27);
	v3.GUI.ShowPanel(v28);
	v3.GUI.ShowPanel(v29);
	v3.GUI.ShowPanel(v30);
end;
