local v0, v1 = ...;
local v2 = HeroRotation();
local v3 = HeroLib;
local v4 = v3.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v2.HRGUIGet().CreateARPanelOption;
local v8 = v2.HRGUIGet().CreateARPanelOptions;
local v9 = v2.GUISettingsGet();
v9.APL.Paladin = {Commons={Enabled={Trinkets=true,Potions=true,Items=true}},Protection={PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},Consecration=true,UseBoF=true,UseCleanse=true,AttackOutOfCombat=true,UseFreedom=true,Mobcount=(12 - 8),AvengingWrathSetting="With Cooldowns",RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",TrinketHP=(114 - 74),PotionSetting="With Cooldowns",DivineTollSetting="With Cooldowns",EyeOfTyrSetting="With Cooldowns"},ProtectionDefensives={BubbleHP=(28 - 13),LoHHP=(38 - 23),BoPHP=(639 - (555 + 64)),BoPDebuff=true,GoAKHP=(971 - (857 + 74)),WordofGloryPlayerHP=(608 - (367 + 201)),FreeWordofGloryPlayerHP=(1017 - (214 + 713)),WordofGloryPartyHP=(6 + 14),FreeWordofGloryPartyHP=(10 + 50),WordofGloryFaithintheLight=true,ArdentDefenderHP=(937 - (282 + 595)),LoHPartyHP=(1647 - (1523 + 114)),BlessingOfSacrificeHP=(27 + 3),TankBusters=true,IntercessionTarget=true,MostDefensive=true},ProtTTD={AvengingWrathTTD=(28 - 8),RacialsTTD=(1085 - (68 + 997)),TrinketsTTD=(1290 - (226 + 1044)),DivineTollTTD=(87 - 67)},Retribution={AuraSelect="Retribution Aura",PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},AttackOutOfCombat=false,UseCleanse=true,UseBoF=true,XalatathsBargain=true},RetCooldowns={Mobcount=(119 - (32 + 85)),AvengingWrathSetting="With Cooldowns",ExecutionSentenceSetting="With Cooldowns",FinalReckoningSetting="With Cooldowns",CrusadeSetting="With Cooldowns",RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",PotionSetting="With Cooldowns",DivineTollSetting="With Cooldowns",WakeofAshesSetting="With Cooldowns",WeaponSetting="With Cooldowns"},RetHealing={BubbleHP=(15 + 0),LoHHP=(4 + 11),LoHPartyHP=(967 - (892 + 65)),WordofGloryPlayerHP=(35 - 20),WordofGloryPartyHP=(0 - 0),FlashofLightPlayerHP=(0 - 0),FlashofLightPartyHP=(350 - (87 + 263)),ShieldofVengeanceHP=(275 - (67 + 113)),DivineProtectionHP=(37 + 13),BoPHP=(49 - 29),BlessingOfSacrificeHP=(23 + 7),BoPDebuff=true,BoPPlayerOnly=false,UnboundFreedomUnit="party1",IntercessionTarget=true},RetTTD={AvengingWrathTTD=(79 - 59),ExecutionSentenceTTD=(972 - (802 + 150)),FinalReckoningTTD=(53 - 33),CrusadeTTD=(36 - 16),RacialsTTD=(15 + 5),TrinketsTTD=(1017 - (915 + 82)),DivineTollTTD=(56 - 36),WakeofAshesTTD=(12 + 8)},Holy={BubbleHP=(19 - 4),DivineProtectionHP=(1237 - (1069 + 118)),Overcap=true,UseSoTR=false,UseDTDPS=false,UseHolyShockDPS=true,ManualBeacon=false,AutoTabMelee=false,EntangleSelf=true,AttackOOC=false,UseFreedom=true,UseBL=false,PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"}},HolyBlessings={ManualBlessings=false,SummerOnSelf=true,BlessingofAutumnParty="player",BlessingofAutumnRaid="raid1",BlessingOfWinterParty="player",BlessingOfWinterRaid="raid1",BlessingOfSummerParty="player",BlessingOfSummerRaid="raid1",BlessingOFSpringParty="player",BlessingOFSpringRaid="raid1"},HolyCooldowns={AWUsage="With Logic",ACUsage="With Logic",DayUsage="With Logic",AMUsage="With Logic",BoVUsage="With Logic",DTUsage="With Logic",LHUsage="With Logic",HPUsage="With Logic",Trinket1Use="With Logic",Trinket2Use="With Logic",Trinket1HP=(147 - 82),Trinket2HP=(142 - 77),ManualSacredWeapon=false,SacredWeaponPartyUnit="player",SacredWeaponRaidUnit="raid1"},HolyAoE={AWHP=(8 + 37),ACHP=(133 - 58),AMHP=(45 + 0),BoVHP=(876 - (368 + 423)),DivineTollHP=(251 - 171),LoDHP=(103 - (10 + 8)),TyrsHP=(346 - 256),AWCount=(446 - (416 + 26)),ACCount=(9 - 6),AMCount=(2 + 2),BoVCount=(4 - 1),DivineTollCount=(441 - (145 + 293)),LoDCount=(434 - (44 + 386)),TyrsCount=(1487 - (998 + 488))},HolyAoE2={HPHP=(28 + 57),LHHP=(66 + 14),HPCount=(774 - (201 + 571)),LHCount=(1141 - (116 + 1022))},HolyHealing={WoGHP=(249 - 189),FoLHP=(9 + 6),FoLIHP=(127 - 92),HLHP=(35 - 25),HLIHP=(904 - (814 + 45)),HolyShockHP=(243 - 144),HolyShock2HP=(4 + 61),HolyShockRHP=(23 + 42),WoGTankHP=(960 - (261 + 624)),WoGOverHP=(44 - 19),HBHP=(1155 - (1020 + 60)),HBTank=true},HolySpecialHealing={LoHHP=(1433 - (630 + 793)),BoPHP=(33 - 23),BoSHP=(213 - 168),UseBoS=true,UseBoP=true,DivineFavorHP=(26 + 39),FoLDFHP=(154 - 109),HLDFHP=(1832 - (760 + 987)),HandofDivinityHP=(1968 - (1789 + 124)),HLBoth=(821 - (745 + 21)),FoLBoth=(23 + 42)},HolyRaidAoE={AWHP=(123 - 78),ACHP=(294 - 219),AMHP=(1 + 44),BoVHP=(67 + 18),DivineTollHP=(1135 - (87 + 968)),LoDHP=(374 - 289),TyrsHP=(82 + 8),AWCount=(8 - 4),ACCount=(1416 - (447 + 966)),AMCount=(10 - 6),BoVCount=(1820 - (1703 + 114)),DivineTollCount=(704 - (376 + 325)),LoDCount=(5 - 1),TyrsCount=(2 - 1)},HolyRaidAoE2={HPHP=(25 + 60),LHHP=(176 - 96),HPCount=(16 - (9 + 5)),LHCount=(379 - (85 + 291))},HolyRaidHealing={WoGHP=(1325 - (243 + 1022)),FoLHP=(57 - 42),FoLIHP=(29 + 6),HLHP=(1190 - (1123 + 57)),HLIHP=(37 + 8),HolyShockHP=(353 - (163 + 91)),HolyShock2HP=(1995 - (1869 + 61)),HolyShockRHP=(19 + 46),WoGTankHP=(263 - 188),WoGOverHP=(38 - 13),HBHP=(11 + 64),HBTank=true},HolyRaidSpecialHealing={LoHHP=(13 - 3),BoPHP=(10 + 0),BoSHP=(1519 - (1329 + 145)),UseBoS=true,UseBoP=true,DivineFavorHP=(1036 - (140 + 831)),FoLDFHP=(1895 - (1409 + 441)),HLDFHP=(803 - (15 + 703)),HandofDivinityHP=(26 + 29),HLBoth=(493 - (262 + 176)),FoLBoth=(1786 - (345 + 1376))},HolyTyrs={BeforeTyrs=true,TyrFoLHP=(688 - (198 + 490)),TyrHLHP=(0 - 0)},HolyDaybreak={DaybreakHP=(191 - 111),DaybreakCount=(1211 - (696 + 510)),DaybreakAfterDT=true,DayBreakCombo=true,DaybreakComboHP=(188 - 98),DaybreakComboUnit=(1267 - (1091 + 171))}};
v2.HRGUIGet().LoadSettingsRecursively(v9);
local v11 = v2.HRGUIGet().Panel;
local v12 = v5(v11, "Paladin");
local v13 = v5(v12, "Protection");
local v14 = v5(v13, "Defensives");
local v15 = v5(v13, "TTD");
local v16 = v5(v12, "Retribution");
local v17 = v5(v12, "Cooldowns");
local v18 = v5(v16, "TTD");
local v19 = v5(v16, "Healing/Defensives");
local v20 = v5(v12, "Holy");
local v21 = v5(v20, "Blessings");
local v22 = v5(v20, "Cooldowns");
local v23 = v5(v20, "Healing");
local v24 = v5(v20, "Special Healing");
local v25 = v5(v20, "Tyr's Deliverance");
local v26 = v5(v20, "Day Break");
local v27 = v5(v20, "AoE Healing");
local v28 = v5(v20, "AoE Healing 2");
local v29 = v5(v20, "Raid Healing");
local v30 = v5(v20, "Raid AoE Healing");
local v31 = v5(v20, "Raid AoE Healing 2");
local v32 = v5(v20, "Raid Special Healing");
local v33 = {"With Cooldowns","With Logic","With Cooldowns and Logic","Not Used"};
local v34 = {"Not Used","Always","With Cooldowns","With Small or Cooldowns","On Mobcount","On Mobcount or Cooldowns","On Bosses","Mobcount or Boss"};
local v35 = {"None","Tank","Healer","Tank and Healer","DD","All"};
local v36 = {"Not Used","Always","With Cooldowns","With Small or Cooldowns","On Mobcount","On Mobcount or Cooldowns","On Bosses","Mobcount or Boss","On HealthPercent"};
local v37 = {"raid1","raid2","raid3","raid4","raid5","raid6","raid7","raid8","raid9","raid10","raid11","raid12","raid13","raid14","raid15","raid16","raid17","raid18","raid19","raid20","raid21","raid22","raid23","raid24","raid25","raid26","raid27","raid28","raid29","raid30","raid31","raid32","raid33","raid34","raid35","raid36","raid37","raid38","raid39","raid40"};
local v38 = {"player","party1","party2","party3","party4"};
local v39 = {"None","Retribution Aura","Devotion Aura","Concentration Aura"};
v8(v12, "APL.Paladin.Commons");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.BubbleHP", {(0 + 0),(1186 - (461 + 625)),(1 + 0)}, "Bubble HP", "Set the Bubble HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.LoHHP", {(0 + 0),(30 + 70),(530 - (406 + 123))}, "Lay on Hands HP", "Set the Lay on Hands HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.LoHPartyHP", {(0 + 0),(36 + 64),(2 - 1)}, "Lay on Hands Party HP", "Set the Lay on Hands on Player HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.BoPHP", {(1900 - (106 + 1794)),(26 + 74),(2 - 1)}, "Blessing of Protection HP", "Set the Blessing of Protection on HP threshold.");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.BoPDebuff", "Blessing of Protection on Debuff", "Use Blessing of Protection on Debuffs");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.GoAKHP", {(584 - (57 + 527)),(203 - (17 + 86)),(1 - 0)}, "Guardian of Ancient Kings HP", "Set the Guardian of Ancient Kings HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.ArdentDefenderHP", {(166 - (122 + 44)),(331 - 231),(1 + 0)}, "Ardent Defender HP", "Set the Ardent Defender HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.WordofGloryPlayerHP", {(65 - (30 + 35)),(1357 - (1043 + 214)),(1213 - (323 + 889))}, "Player Word of Glory HP", "Set the Word of Glory HP threshold for casting on ourself: if we drop below this HP, we'll prio WOG over economy globals.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.FreeWordofGloryPlayerHP", {(580 - (361 + 219)),(23 + 77),(983 - (18 + 964))}, "Free Word of Glory Player HP", "Set the Free Word of Glory HP threshold for casting on ourself.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.WordofGloryPartyHP", {(0 + 0),(950 - (20 + 830)),(127 - (116 + 10))}, "Party Word of Glory HP", "Set the party Word of Glory HP threshold for casting on a friendly.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.FreeWordofGloryPartyHP", {(738 - (542 + 196)),(30 + 70),(1 + 0)}, "Free Word of Glory Party HP", "Set the Free Word of Glory HP threshold for casting on party.");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.WordofGloryFaithintheLight", "Word of Glory with FitL", "Use Word of Glory with Faith in the Light");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.BlessingOfSacrificeHP", {(0 - 0),(505 - (118 + 287)),(1122 - (118 + 1003))}, "Blessing of Sacrifice Party HP", "Set the Blessing of Sacrifice HP threshold for casting on party.");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.TankBusters", "Defensives on Tank Busters", "Use Defensives on Tank Busters");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.IntercessionTarget", "Intercession on Target", "Use Intercession on your Target");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.MostDefensive", "Most Defensive", "Will adjust the rotation to be more defensive");
v8(v14, "APL.Paladin.ProtectionDefensives");
v6("CheckButton", v13, "APL.Paladin.Protection.Consecration", "Consecration while moving", "Use Consecration while moving");
v6("CheckButton", v13, "APL.Paladin.Protection.AttackOutOfCombat", "Attack out of combat", "Attack out of combat");
v6("CheckButton", v13, "APL.Paladin.Protection.UseFreedom", "Use Blessing of Freedom", "Use Blessing of Freedom");
v6("CheckButton", v13, "APL.Paladin.Protection.UseBoF", "Enable Blessing of Freedom", "Enable this option to use Blessing of Freedom");
v6("CheckButton", v13, "APL.Paladin.Protection.UseCleanse", "Enable Cleanse", "Enable this option to use Cleanse");
v6("Slider", v13, "APL.Paladin.Protection.Mobcount", {(377 - (142 + 235)),(14 + 46),(1 - 0)}, "Mobcount", "Mobcount");
v6("Dropdown", v13, "APL.Paladin.Protection.RacialsSetting", v34, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v13, "APL.Paladin.Protection.Trinket1Setting", v36, "Trinket 1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v13, "APL.Paladin.Protection.Trinket2Setting", v36, "Trinket 2 Usage", "Select how to use Trinket 2.");
v6("Slider", v13, "APL.Paladin.Protection.TrinketHP", {(0 + 0),(43 + 57),(2 - 1)}, "Trinket HP", "HP Value to use the Trinket setting");
v6("Dropdown", v13, "APL.Paladin.Protection.PotionSetting", v34, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v13, "APL.Paladin.Protection.DivineTollSetting", v34, "Divine Toll Usage", "Select how to use Divine Toll.");
v6("Dropdown", v13, "APL.Paladin.Protection.AvengingWrathSetting", v34, "Avenging Wrath Usage", "Select how to use Avenging Wrath.");
v6("Dropdown", v13, "APL.Paladin.Protection.EyeOfTyrSetting", v34, "Eye of Tyr Usage", "Select how to use Eye of Tyr.");
v8(v13, "APL.Paladin.Protection");
v6("Slider", v15, "APL.Paladin.ProtTTD.AvengingWrathTTD", {(0 - 0),(289 - 229),(1 + 0)}, "Avenging Wrath TTD", "TTD to use Avenging Wrath on Dungeon Mobs");
v6("Slider", v15, "APL.Paladin.ProtTTD.RacialsTTD", {(0 + 0),(141 - 81),(732 - (476 + 255))}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v15, "APL.Paladin.ProtTTD.TrinketsTTD", {(0 + 0),(113 - 53),(1 + 0)}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v15, "APL.Paladin.ProtTTD.DivineTollTTD", {(336 - (144 + 192)),(46 + 14),(1 + 0)}, "Divine Toll TTD", "TTD to use Divine Toll on Dungeon Mobs");
v8(v15, "APL.Paladin.ProtTTD");
v6("Slider", v19, "APL.Paladin.RetHealing.BubbleHP", {(1580 - (1183 + 397)),(74 + 26),(1976 - (1913 + 62))}, "Bubble Player HP", "Set the Bubble on Player HP threshold.");
v6("Slider", v19, "APL.Paladin.RetHealing.LoHHP", {(0 - 0),(376 - 276),(1 - 0)}, "Lay on Hands Player HP", "Set the Lay on Hands on Player HP threshold.");
v6("Slider", v19, "APL.Paladin.RetHealing.LoHPartyHP", {(856 - (564 + 292)),(301 - 201),(1 + 0)}, "Lay on Hands Party HP", "Set the Lay on Hands on Party HP threshold.");
v6("Slider", v19, "APL.Paladin.RetHealing.BoPHP", {(1001 - (938 + 63)),(1225 - (936 + 189)),(1614 - (1565 + 48))}, "Blessing of Protection HP", "Set the Blessing of Protection on HP threshold.");
v6("CheckButton", v19, "APL.Paladin.RetHealing.BoPDebuff", "Blessing of Protection on Debuff", "Use Blessing of Protection on Debuffs");
v6("CheckButton", v19, "APL.Paladin.RetHealing.BoPPlayerOnly", "Blessing of Protection Player only", "Use Blessing of Protection only on Player");
v6("Slider", v19, "APL.Paladin.RetHealing.WordofGloryPlayerHP", {(1138 - (782 + 356)),(260 - 160),(1093 - (975 + 117))}, "WoG/EF Player HP", "Set the Word of Glory HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.WordofGloryPartyHP", {(0 + 0),(341 - 241),(2 - 1)}, "WoG/EF Party HP", "Set the Word of Glory HP threshold for casting on party.");
v6("Slider", v19, "APL.Paladin.RetHealing.FlashofLightPlayerHP", {(0 - 0),(187 - 87),(1228 - (322 + 905))}, "Flash of Light Player HP", "Set the Flash of Light HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.FlashofLightPartyHP", {(1189 - (449 + 740)),(1047 - (245 + 702)),(1 + 0)}, "Flash of Light Party HP", "Set the Flash of Light HP threshold for casting on party.");
v6("Slider", v19, "APL.Paladin.RetHealing.ShieldofVengeanceHP", {(440 - (382 + 58)),(84 + 16),(2 - 1)}, "Shield of Vengeance Player HP", "Set the Shield of Vengeance Player HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.DivineProtectionHP", {(0 - 0),(9 + 91),(215 - (22 + 192))}, "Divine Protection Player HP", "Set the Divine Protection HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.BlessingOfSacrificeHP", {(1463 - (1404 + 59)),(134 - 34),(563 - (334 + 228))}, "Blessing of Sacrifice Party HP", "Set the Blessing of Sacrifice HP threshold for casting on party.");
v6("CheckButton", v19, "APL.Paladin.RetHealing.IntercessionTarget", "Intercession on Target", "Use Intercession on your Target");
v6("Dropdown", v19, "APL.Paladin.RetHealing.UnboundFreedomUnit", v38, "Unbound Freedom Unit", "Select the Unit you want to Use your Blessing of Freedom if Unbound Freedom skilled");
v8(v19, "APL.Paladin.RetHealing");
v6("CheckButton", v16, "APL.Paladin.Retribution.AttackOutOfCombat", "Attack out of combat", "Attack out of combat");
v6("CheckButton", v16, "APL.Paladin.Retribution.XalatathsBargain", "Blinding Light for Spheres", "Save Blinding Light for Xal'atath's Bargain");
v6("CheckButton", v16, "APL.Paladin.Retribution.UseBoF", "Enable Blessing of Freedom", "Enable this option to use Blessing of Freedom");
v6("CheckButton", v16, "APL.Paladin.Retribution.UseCleanse", "Enable Cleanse", "Enable this option to use Cleanse");
v6("Dropdown", v16, "APL.Paladin.Retribution.AuraSelect", v39, "Select Aura", "Aura you want to use");
v8(v16, "APL.Paladin.Retribution");
v6("Slider", v17, "APL.Paladin.RetCooldowns.Mobcount", {(0 - 0),(18 + 42),(1 + 0)}, "Mobcount", "Mobcount");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.RacialsSetting", v34, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.Trinket1Setting", v34, "Trinket 1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.Trinket2Setting", v34, "Trinket 2 Usage", "Select how to use Trinket 2.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.PotionSetting", v34, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.DivineTollSetting", v34, "Divine Toll Usage", "Select how to use Divine Toll.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.AvengingWrathSetting", v34, "Avenging Wrath Usage", "Select how to use Avenging Wrath.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.ExecutionSentenceSetting", v34, "Execution Sentence Usage", "Select how to use Execution Sentence.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.FinalReckoningSetting", v34, "Final Reckoning Usage", "Select how to use Final Reckoning.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.CrusadeSetting", v34, "Crusade Usage", "Select how to use Crusade.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.WakeofAshesSetting", v34, "Wake of Ashes Usage", "Select how to use Wake of Ashes.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.WeaponSetting", v34, "Weapon Usage", "Change your Weapon usage.");
v8(v17, "APL.Paladin.RetCooldowns");
v6("Slider", v18, "APL.Paladin.RetTTD.AvengingWrathTTD", {(0 - 0),(164 - 104),(1 + 0)}, "Avenging Wrath TTD", "TTD to use Avenging Wrath on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.ExecutionSentenceTTD", {(0 + 0),(30 + 30),(766 - (574 + 191))}, "Execution Sentence TTD", "TTD to use Execution Sentence on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.FinalReckoningTTD", {(0 - 0),(909 - (254 + 595)),(1 - 0)}, "Final Reckoning TTD", "TTD to use Final Reckoning on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.CrusadeTTD", {(0 - 0),(96 - 36),(2 - 1)}, "Crusade TTD", "TTD to use Crusade on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.RacialsTTD", {(0 + 0),(866 - (118 + 688)),(1 + 0)}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.TrinketsTTD", {(0 - 0),(115 - 55),(2 - 1)}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.DivineTollTTD", {(0 - 0),(1856 - (503 + 1293)),(1 + 0)}, "Divine Toll TTD", "TTD to use Divine Toll on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.WakeofAshesTTD", {(0 + 0),(55 + 5),(734 - (711 + 22))}, "Wake of Ashes TTD", "TTD to use Wake of Ashes on Dungeon Mobs");
v8(v18, "APL.Paladin.RetTTD");
v6("Slider", v20, "APL.Paladin.Holy.DivineProtectionHP", {(859 - (240 + 619)),(159 - 59),(1745 - (1344 + 400))}, "Divine Protection Player HP", "Set the Divine Protection HP Threshold.");
v6("Slider", v20, "APL.Paladin.Holy.BubbleHP", {(0 + 0),(427 - 327),(1740 - (404 + 1335))}, "Bubble HP", "Set the Bubble HP Threshold.");
v6("CheckButton", v20, "APL.Paladin.Holy.Overcap", "Ignore Overcap", "Ignore Overcapping logic and always cast Spenders");
v6("CheckButton", v20, "APL.Paladin.Holy.UseHolyShockDPS", "Use Holy Shock for DPS", "Use Holy Shock for DPS (DPS Only Overrides)?");
v6("CheckButton", v20, "APL.Paladin.Holy.UseDTDPS", "Use Divine Toll during DPS Only", "Use Divine Toll DURING DPS ONLY?");
v6("CheckButton", v20, "APL.Paladin.Holy.ManualBeacon", "Manual Beacons", "Would you like to Manual Beacon?");
v6("CheckButton", v20, "APL.Paladin.Holy.AutoTabMelee", "Auto Tab Melee", "Auto Tab to always a target in melee.");
v6("CheckButton", v20, "APL.Paladin.Holy.UseFreedom", "Use Blessing of Freedom", "Use Blessing of Freedom");
v6("CheckButton", v20, "APL.Paladin.Holy.AttackOOC", "Attack with OOC", "Attack not in Combat?");
v6("CheckButton", v20, "APL.Paladin.Holy.UseBL", "Use Blinding Light", "Use Blinding Light as a Interupt Option?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.AWUsage", v33, "Avenging Wrath Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.ACUsage", v33, "Avenging Crusader Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.AMUsage", v33, "Aura Mastery Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.BoVUsage", v33, "Beacon of Virtue Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.DTUsage", v33, "Divine Toll Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.HPUsage", v33, "Holy Prism Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.Trinket1Use", v33, "Trinket 1 Usage", "How would you like to use this Cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.Trinket2Use", v33, "Trinket 2 Usage", "How would you like to use this Cooldown?");
v6("Slider", v22, "APL.Paladin.HolyCooldowns.Trinket1HP", {(0 - 0),(36 + 64),(1 + 0)}, "Trinket 1 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("Slider", v22, "APL.Paladin.HolyCooldowns.Trinket2HP", {(0 + 0),(45 + 55),(1494 - (711 + 782))}, "Trinket 2 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("CheckButton", v22, "APL.Paladin.HolyCooldowns.ManualSacredWeapon", "Manual Sacred Weapon", "Manual Sacred Weapon Usage?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.SacredWeaponPartyUnit", v38, "Sacred Weapon Party Unit", "Which Unit to Use on?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.SacredWeaponRaidUnit", v37, "Sacred Weapon Raid Unit", "Which Unit to Use on?");
v6("CheckButton", v21, "APL.Paladin.HolyBlessings.ManualBlessings", "Manual Blessings", "Manual Blessings Usage?");
v6("CheckButton", v21, "APL.Paladin.HolyBlessings.SummerOnSelf", "Summer Always on Self", "Blessing of Summer Always on Self?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingofAutumnParty", v38, "Blessing of Autumn Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingofAutumnRaid", v37, "Blessing of Autumn Raid Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfWinterParty", v38, "Blessing of Winter Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfWinterRaid", v37, "Blessing of Wtiner Raid Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfSummerParty", v38, "Blessing of Summer Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfSummerRaid", v37, "Blessing of Summer Raid Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOFSpringParty", v38, "Blessing of Spring Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOFSpringRaid", v37, "Blessing of Spring Raid Unit", "Which Unit to Use on?");
v6("Slider", v27, "APL.Paladin.HolyAoE.AWHP", {(469 - (270 + 199)),(1919 - (580 + 1239)),(1 + 0)}, "Avenging Wrath  HP", "Set the Avenging Wrath  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.AWCount", {(0 + 0),(4 + 1),(1791 - (1010 + 780))}, "Avenging Wrath Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.ACHP", {(0 - 0),(1936 - (1045 + 791)),(1 - 0)}, "Avenging Crusader  HP", "Set the Avenging Crusader  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.ACCount", {(1574 - (1281 + 293)),(10 - 5),(1 + 0)}, "Avenging Crusder Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.AMHP", {(0 + 0),(52 + 48),(1 + 0)}, "Aura Mastery  HP", "Set the Aura Mastery  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.AMCount", {(0 - 0),(10 - 5),(1456 - (990 + 465))}, "Aura Mastery Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.BoVHP", {(0 + 0),(393 - 293),(627 - (512 + 114))}, "Beacon of Virtue  HP", "Set the Beacon of Virtue  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.BoVCount", {(0 - 0),(3 + 2),(1 + 0)}, "Beacon of Virtue Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.DivineTollHP", {(1994 - (109 + 1885)),(191 - 91),(827 - (802 + 24))}, "Divine Toll  HP", "Set the Divine Toll  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.DivineTollCount", {(0 - 0),(4 + 1),(1 + 0)}, "Divine Toll Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.LoDHP", {(0 - 0),(41 + 59),(1 + 0)}, "Light of Dawn  HP", "Set the Light of Dawn  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.LoDCount", {(1433 - (797 + 636)),(1624 - (1427 + 192)),(2 - 1)}, "Light of Dawn Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.TyrsHP", {(0 + 0),(1376 - (316 + 960)),(1 + 0)}, "Tyr's Deliverance  HP", "Set the Tyr's Deliverance  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.TyrsCount", {(0 - 0),(1811 - (1202 + 604)),(1 - 0)}, "Tyr's Deliverance Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v28, "APL.Paladin.HolyAoE2.HPHP", {(325 - (45 + 280)),(88 + 12),(1 + 0)}, "Holy Prism  HP", "Set the Holy Prism  HP Threshold.");
v6("Slider", v28, "APL.Paladin.HolyAoE2.HPCount", {(0 - 0),(2 + 3),(2 - 1)}, "Holy Prism Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v23, "APL.Paladin.HolyHealing.FoLHP", {(1948 - (1096 + 852)),(142 - 42),(513 - (409 + 103))}, "Flash of Light HP", "Set the Flash of Light HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.FoLIHP", {(95 - (51 + 44)),(1417 - (1114 + 203)),(1 + 0)}, "Flash of Light With Infusion HP", "Set the Flash of Light With Infusion HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HLHP", {(663 - (174 + 489)),(2005 - (830 + 1075)),(1270 - (231 + 1038))}, "Holy Light HP", "Set the Holy Light HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HLIHP", {(1162 - (171 + 991)),(268 - 168),(1 + 0)}, "Holy Light with Infusion HP", "Set the Holy Light with Infusion HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HolyShockHP", {(0 - 0),(309 - 209),(159 - (91 + 67))}, "Holy Shock HP", "Set the Holy Shock HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HolyShock2HP", {(0 + 0),(1 + 99),(1 + 0)}, "Holy Shock 2nd Charge HP", "Set the Holy Shock 2nd Charge HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HolyShockRHP", {(0 - 0),(233 - 133),(882 - (614 + 267))}, "Holy Shock Rising Sun HP", "Set the Holy Shock Rising Sun HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.WoGHP", {(0 - 0),(285 - 185),(1 - 0)}, "Word of Glory/EF HP", "Set the Word of Glory/Eternal Flame HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.WoGTankHP", {(1812 - (1293 + 519)),(261 - 161),(4 - 3)}, "Word of Glory/EF On Tank HP", "Set the Word of Glory/Eternal Flame  On Tank HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.WoGOverHP", {(0 + 0),(232 - 132),(1 + 0)}, "Word of Glory/EF over LoD HP", "Set the Word of Glory/Eternal Flame  over LoDHP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HBHP", {(1096 - (709 + 387)),(290 - 190),(1 - 0)}, "Holy Bulward HP", "Set the Holy Bulwark HP threshold.");
v6("CheckButton", v23, "APL.Paladin.HolyHealing.HBTank", "Holy Bulwark Tank Only", "Would you like Rotation to only use Holy Bulwark on Tanks (Unless a unit is very low?");
v6("CheckButton", v24, "APL.Paladin.HolySpecialHealing.UseBoP", "Use BoP Logic", "Would you like Rotation to Use Special Logic Outside of Health for BoP??");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.BoPHP", {(0 + 0),(25 + 75),(1 - 0)}, "Blessing of Protection HP", "Set theBlessing of Protection HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.BoSHP", {(1283 - (1040 + 243)),(1947 - (559 + 1288)),(455 - (13 + 441))}, "Blessing of Sacrfice  HP", "Set the Blessing of Sacrfice HP threshold.");
v6("CheckButton", v24, "APL.Paladin.HolySpecialHealing.UseBoS", "Use BoS Logic", "Would you like Rotation to Use Special Logic Outside of Health for Sac??");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.FoLDFHP", {(0 - 0),(4 + 96),(1 + 0)}, "Divine Favor with Flash of Light HP", "Set the Divine Favor with Flash of Light HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.HLDFHP", {(0 - 0),(183 - 83),(1 + 0)}, "Divine Favor HP", "Set the Divine Favor with Holy Light HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.HLBoth", {(0 + 0),(533 - (153 + 280)),(1 + 0)}, "Holy Light /w Both Buffs HP", "Set the Divine Favor with Holy Light with Favor and Infusion HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.FoLBoth", {(0 + 0),(73 + 27),(1 + 0)}, "FoL /w Both Buffs HP", "Set the Divine Favor with Flash of Light with Favor and Infusion HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.HandofDivinityHP", {(0 + 0),(1149 - (572 + 477)),(1 + 0)}, "Hand Of Divinity HP", "Set the Hand of Divinity HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.LoHHP", {(86 - (84 + 2)),(73 + 27),(1 + 0)}, "Lay on Hands HP", "Set the Lay on Hands HP threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AWHP", {(1333 - (605 + 728)),(222 - 122),(3 - 2)}, "Avenging Wrath HP", "Set the Avenging Wrath  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AWCount", {(0 - 0),(529 - (457 + 32)),(1403 - (832 + 570))}, "Avenging Wrath Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.ACHP", {(0 + 0),(49 + 51),(2 - 1)}, "Avenging Crusader  HP", "Set the Avenging Crusader  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.ACCount", {(0 - 0),(658 - (232 + 421)),(1 + 0)}, "Avenging Crusder Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AMHP", {(0 - 0),(261 - 161),(1454 - (666 + 787))}, "Aura Mastery  HP", "Set the Aura Mastery  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AMCount", {(0 + 0),(63 - 23),(2 - 1)}, "Aura Mastery Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.BoVHP", {(899 - (503 + 396)),(193 - 93),(1 + 0)}, "Beacon of Virtue  HP", "Set the Beacon of Virtue  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.BoVCount", {(0 + 0),(5 + 0),(2 - 1)}, "Beacon of Virtue Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.DivineTollHP", {(0 - 0),(231 - 131),(1136 - (832 + 303))}, "Divine Toll  HP", "Set the Divine Toll  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.DivineTollCount", {(0 + 0),(1 + 4),(4 - 3)}, "Divine Toll Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.LoDHP", {(0 - 0),(1173 - (1036 + 37)),(1 - 0)}, "Light of Dawn  HP", "Set the Light of Dawn  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.LoDCount", {(1480 - (641 + 839)),(12 - 7),(1 + 0)}, "Light of Dawn Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.TyrsHP", {(0 + 0),(954 - (174 + 680)),(1 - 0)}, "Tyr's Deliverance  HP", "Set the Tyr's Deliverance  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.TyrsCount", {(739 - (396 + 343)),(1482 - (29 + 1448)),(3 - 2)}, "Tyr's Deliverance Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v31, "APL.Paladin.HolyRaidAoE2.HPHP", {(0 + 0),(674 - (102 + 472)),(1 + 0)}, "Holy Prism  HP", "Set the Holy Prism  HP Threshold.");
v6("Slider", v31, "APL.Paladin.HolyRaidAoE2.HPCount", {(1545 - (320 + 1225)),(4 + 1),(1860 - (821 + 1038))}, "Holy Prism Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.FoLHP", {(0 + 0),(38 + 62),(1027 - (834 + 192))}, "Flash of Light HP", "Set the Flash of Light HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.FoLIHP", {(0 + 0),(154 - 54),(1 + 0)}, "Flash of Light With Infusion HP", "Set the Flash of Light With Infusion HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HLHP", {(362 - (112 + 250)),(250 - 150),(1 + 0)}, "Holy Light HP", "Set the Holy Light HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HLIHP", {(0 + 0),(1514 - (1001 + 413)),(883 - (244 + 638))}, "Holy Light with Infusion HP", "Set the Holy Light with Infusion HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HolyShockHP", {(0 - 0),(2006 - (1665 + 241)),(1 + 0)}, "Holy Shock HP", "Set the Holy Shock HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HolyShock2HP", {(0 - 0),(1199 - (35 + 1064)),(2 - 1)}, "Holy Shock 2nd Charge HP", "Set the Holy Shock 2nd Charge HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HolyShockRHP", {(1236 - (298 + 938)),(1766 - (636 + 1030)),(1 + 0)}, "Holy Shock Rising Sun HP", "Set the Holy Shock Rising Sun HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.WoGHP", {(0 + 0),(20 + 80),(3 - 2)}, "Word of Glory/EF HP", "Set the Word of Glory/Eternal Flame  HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.WoGTankHP", {(0 - 0),(39 + 61),(1284 - (1035 + 248))}, "Word of Glory/EF On Tank HP", "Set the Word of Glory/Eternal Flame  On Tank HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.WoGOverHP", {(0 + 0),(1233 - (549 + 584)),(3 - 2)}, "Word of Glory/EF over LoD HP", "Set the Word of Glory/Eternal Flame  over LoDHP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HBHP", {(0 + 0),(323 - 223),(1341 - (1093 + 247))}, "Holy Bulward HP", "Set the Holy Bulwark HP threshold.");
v6("CheckButton", v29, "APL.Paladin.HolyRaidHealing.HBTank", "Holy Bulwark Tank Only", "Would you like Rotation to only use Holy Bulwark on Tanks (Unless a unit is very low?");
v6("CheckButton", v32, "APL.Paladin.HolyRaidSpecialHealing.UseBoP", "Use BoP Logic", "Would you like Rotation to Use Special Logic Outside of Health for BoP??");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.BoPHP", {(0 + 0),(339 - 239),(2 - 1)}, "Blessing of Protection HP", "Set theBlessing of Protection HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.BoSHP", {(0 - 0),(76 + 24),(689 - (364 + 324))}, "Blessing of Sacrfice  HP", "Set the Blessing of Sacrfice HP threshold.");
v6("CheckButton", v32, "APL.Paladin.HolyRaidSpecialHealing.UseBoS", "Use BoS Logic", "Would you like Rotation to Use Special Logic Outside of Health for Sac??");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.FoLDFHP", {(0 - 0),(418 - 318),(2 - 1)}, "Divine Favor with Flash of Light HP", "Set the Divine Favor with Flash of Light HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.HLDFHP", {(0 + 0),(1186 - (686 + 400)),(230 - (73 + 156))}, "Divine Favor HP", "Set the Divine Favor with Holy Light HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.HLBoth", {(811 - (721 + 90)),(324 - 224),(1 - 0)}, "Holy Light /w Both Buffs HP", "Set the Divine Favor with Holy Light with Favor and Infusion HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.FoLBoth", {(0 + 0),(74 + 26),(3 - 2)}, "FoL /w Both Buffs HP", "Set the Divine Favor with Flash of Light with Favor and Infusion HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.HandofDivinityHP", {(1993 - (1238 + 755)),(1634 - (709 + 825)),(1 - 0)}, "Hand Of Divinity HP", "Set the Hand of Divinity HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.LoHHP", {(0 - 0),(933 - (171 + 662)),(3 - 2)}, "Lay on Hands HP", "Set the Lay on Hands HP threshold.");
v6("CheckButton", v25, "APL.Paladin.HolyTyrs.BeforeTyrs", "Hand of Divinity Before Tyr's", "Attempt to use Hand of Divinity before Tyrs");
v6("Slider", v25, "APL.Paladin.HolyTyrs.TyrFoLHP", {(0 - 0),(1586 - (35 + 1451)),(1994 - (941 + 1052))}, "Flash of Light with Tyrs HP", "Set the Flash of Light with Tyrs HP threshold.");
v6("Slider", v25, "APL.Paladin.HolyTyrs.TyrHLHP", {(1514 - (822 + 692)),(48 + 52),(1 + 0)}, "Holy Light with Tyrs HP", "Set the Holy Light with Tyrs HP threshold.");
v8(v32, "APL.Paladin.HolyRaidSpecialHealing");
v8(v30, "APL.Paladin.HolyRaidAoE");
v8(v31, "APL.Paladin.HolyRaidAoE2");
v8(v29, "APL.Paladin.HolyRaidHealing");
v8(v26, "APL.Paladin.HolyDaybreak");
v8(v25, "APL.Paladin.HolyTyrs");
v8(v24, "APL.Paladin.HolySpecialHealing");
v8(v22, "APL.Paladin.HolyCooldowns");
v8(v21, "APL.Paladin.HolyBlessings");
v8(v27, "APL.Paladin.HolyAoE");
v8(v28, "APL.Paladin.HolyAoE2");
v8(v23, "APL.Paladin.HolyHealing");
v8(v20, "APL.Paladin.Holy");
v9.APL.Paladin.Holy.Display = function()
	v3.GUI.HidePanel(v26);
	v3.GUI.ShowPanel(v25);
	v3.GUI.ShowPanel(v24);
	v3.GUI.ShowPanel(v22);
	v3.GUI.ShowPanel(v27);
	v3.GUI.ShowPanel(v23);
	v3.GUI.ShowPanel(v20);
	v3.GUI.ShowPanel(v30);
	v3.GUI.ShowPanel(v29);
	v3.GUI.ShowPanel(v32);
	v3.GUI.ShowPanel(v28);
	v3.GUI.ShowPanel(v31);
	v3.GUI.ShowPanel(v21);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v13);
	v3.GUI.HidePanel(v14);
end;
v9.APL.Paladin.Retribution.Display = function()
	v3.GUI.ShowPanel(v18);
	v3.GUI.ShowPanel(v16);
	v3.GUI.ShowPanel(v17);
	v3.GUI.ShowPanel(v19);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v13);
	v3.GUI.HidePanel(v14);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v32);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v31);
	v3.GUI.HidePanel(v21);
end;
v9.APL.Paladin.Protection.Display = function()
	v3.GUI.ShowPanel(v13);
	v3.GUI.ShowPanel(v14);
	v3.GUI.ShowPanel(v15);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v32);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v31);
	v3.GUI.HidePanel(v21);
end;
