local v0, v1 = ...;
local v2 = HeroRotation();
local v3 = HeroLib;
local v4 = v3.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v2.HRGUIGet().CreateARPanelOption;
local v8 = v2.HRGUIGet().CreateARPanelOptions;
local v9 = v2.GUISettingsGet();
v9.APL.Paladin = {Commons={Enabled={Trinkets=true,Potions=true,Items=true}},Protection={PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},Consecration=true,UseBoF=true,UseCleanse=true,AttackOutOfCombat=true,UseFreedom=true,Mobcount=(12 - 8),AvengingWrathSetting="With Cooldowns",RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",TrinketHP=(114 - 74),PotionSetting="With Cooldowns",DivineTollSetting="With Cooldowns",EyeOfTyrSetting="With Cooldowns"},ProtectionDefensives={BubbleHP=(28 - 13),LoHHP=(38 - 23),BoPHP=(639 - (555 + 64)),BoPDebuff=true,GoAKHP=(971 - (857 + 74)),WordofGloryPlayerHP=(608 - (367 + 201)),FreeWordofGloryPlayerHP=(1017 - (214 + 713)),WordofGloryPartyHP=(6 + 14),FreeWordofGloryPartyHP=(10 + 50),WordofGloryFaithintheLight=true,ArdentDefenderHP=(937 - (282 + 595)),LoHPartyHP=(1647 - (1523 + 114)),BlessingOfSacrificeHP=(27 + 3),BlessingOfSpellwardingHP=(35 - 10),TankBusters=true,IntercessionTarget=true,MostDefensive=true},ProtTTD={AvengingWrathTTD=(1085 - (68 + 997)),RacialsTTD=(1290 - (226 + 1044)),TrinketsTTD=(87 - 67),DivineTollTTD=(137 - (32 + 85))},Retribution={AuraSelect="Crusader Aura",PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},AttackOutOfCombat=false,UseCleanse=true,UseBoF=true,XalatathsBargain=true},RetCooldowns={Mobcount=(2 + 0),AvengingWrathSetting="With Cooldowns",ExecutionSentenceSetting="With Cooldowns",FinalReckoningSetting="With Cooldowns",CrusadeSetting="With Cooldowns",RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",PotionSetting="With Cooldowns",DivineTollSetting="With Cooldowns",WakeofAshesSetting="With Cooldowns",WeaponSetting="With Cooldowns"},RetHealing={BubbleHP=(4 + 11),LoHHP=(972 - (892 + 65)),LoHPartyHP=(23 - 13),WordofGloryPlayerHP=(27 - 12),WordofGloryPartyHP=(0 - 0),FlashofLightPlayerHP=(350 - (87 + 263)),FlashofLightPartyHP=(180 - (67 + 113)),ShieldofVengeanceHP=(70 + 25),DivineProtectionHP=(122 - 72),BoPHP=(15 + 5),BlessingOfSacrificeHP=(119 - 89),BoPDebuff=true,BoPPlayerOnly=false,UnboundFreedomUnit="party1",IntercessionTarget=true},RetTTD={AvengingWrathTTD=(972 - (802 + 150)),ExecutionSentenceTTD=(53 - 33),FinalReckoningTTD=(36 - 16),CrusadeTTD=(15 + 5),RacialsTTD=(1017 - (915 + 82)),TrinketsTTD=(56 - 36),DivineTollTTD=(12 + 8),WakeofAshesTTD=(26 - 6)},Holy={BubbleHP=(1202 - (1069 + 118)),DivineProtectionHP=(113 - 63),Overcap=true,UseSoTR=false,UseDTDPS=false,UseHolyShockDPS=true,ManualBeacon=false,AutoTabMelee=false,EntangleSelf=true,AttackOOC=false,UseFreedom=true,UseBL=false,PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"}},HolyBlessings={ManualBlessings=false,SummerOnSelf=true,BlessingofAutumnParty="player",BlessingofAutumnRaid="raid1",BlessingOfWinterParty="player",BlessingOfWinterRaid="raid1",BlessingOfSummerParty="player",BlessingOfSummerRaid="raid1",BlessingOFSpringParty="player",BlessingOFSpringRaid="raid1"},HolyCooldowns={AWUsage="With Logic",ACUsage="With Logic",DayUsage="With Logic",AMUsage="With Logic",BoVUsage="With Logic",DTUsage="With Logic",LHUsage="With Logic",HPUsage="With Logic",Trinket1Use="With Logic",Trinket2Use="With Logic",Trinket1HP=(142 - 77),Trinket2HP=(12 + 53),ManualSacredWeapon=false,SacredWeaponPartyUnit="player",SacredWeaponRaidUnit="raid1"},HolyAoE={AWHP=(79 - 34),ACHP=(75 + 0),AMHP=(836 - (368 + 423)),BoVHP=(266 - 181),DivineTollHP=(98 - (10 + 8)),LoDHP=(326 - 241),TyrsHP=(532 - (416 + 26)),AWCount=(12 - 8),ACCount=(2 + 1),AMCount=(6 - 2),BoVCount=(441 - (145 + 293)),DivineTollCount=(433 - (44 + 386)),LoDCount=(1490 - (998 + 488)),TyrsCount=(1 + 0)},HolyAoE2={HPHP=(70 + 15),LHHP=(852 - (201 + 571)),HPCount=(1140 - (116 + 1022)),LHCount=(12 - 9)},HolyHealing={WoGHP=(36 + 24),FoLHP=(54 - 39),FoLIHP=(124 - 89),HLHP=(869 - (814 + 45)),HLIHP=(110 - 65),HolyShockHP=(6 + 93),HolyShock2HP=(23 + 42),HolyShockRHP=(950 - (261 + 624)),WoGTankHP=(133 - 58),WoGOverHP=(1105 - (1020 + 60)),HBHP=(1498 - (630 + 793)),HBTank=true},HolySpecialHealing={LoHHP=(33 - 23),BoPHP=(47 - 37),BoSHP=(18 + 27),UseBoS=true,UseBoP=true,DivineFavorHP=(223 - 158),FoLDFHP=(1792 - (760 + 987)),HLDFHP=(1998 - (1789 + 124)),HandofDivinityHP=(821 - (745 + 21)),HLBoth=(19 + 36),FoLBoth=(178 - 113)},HolyRaidAoE={AWHP=(176 - 131),ACHP=(1 + 74),AMHP=(36 + 9),BoVHP=(1140 - (87 + 968)),DivineTollHP=(352 - 272),LoDHP=(78 + 7),TyrsHP=(203 - 113),AWCount=(1417 - (447 + 966)),ACCount=(8 - 5),AMCount=(1821 - (1703 + 114)),BoVCount=(704 - (376 + 325)),DivineTollCount=(4 - 1),LoDCount=(12 - 8),TyrsCount=(1 + 0)},HolyRaidAoE2={HPHP=(186 - 101),LHHP=(94 - (9 + 5)),HPCount=(378 - (85 + 291)),LHCount=(1268 - (243 + 1022))},HolyRaidHealing={WoGHP=(228 - 168),FoLHP=(13 + 2),FoLIHP=(1215 - (1123 + 57)),HLHP=(9 + 1),HLIHP=(299 - (163 + 91)),HolyShockHP=(2029 - (1869 + 61)),HolyShock2HP=(19 + 46),HolyShockRHP=(228 - 163),WoGTankHP=(115 - 40),WoGOverHP=(4 + 21),HBHP=(102 - 27),HBTank=true},HolyRaidSpecialHealing={LoHHP=(10 + 0),BoPHP=(1484 - (1329 + 145)),BoSHP=(1016 - (140 + 831)),UseBoS=true,UseBoP=true,DivineFavorHP=(1915 - (1409 + 441)),FoLDFHP=(763 - (15 + 703)),HLDFHP=(40 + 45),HandofDivinityHP=(493 - (262 + 176)),HLBoth=(1776 - (345 + 1376)),FoLBoth=(753 - (198 + 490))},HolyTyrs={BeforeTyrs=true,TyrFoLHP=(0 - 0),TyrHLHP=(0 - 0)},HolyDaybreak={DaybreakHP=(1286 - (696 + 510)),DaybreakCount=(10 - 5),DaybreakAfterDT=true,DayBreakCombo=true,DaybreakComboHP=(1352 - (1091 + 171)),DaybreakComboUnit=(1 + 4)}};
v2.HRGUIGet().LoadSettingsRecursively(v9);
local v11 = v2.HRGUIGet().Panel;
local v12 = v5(v11, "Paladin");
local v13 = v5(v12, "Protection");
local v14 = v5(v13, "Defensives");
local v15 = v5(v13, "TTD");
local v16 = v5(v12, "Retribution");
local v17 = v5(v12, "Cooldowns");
local v18 = v5(v16, "TTD");
local v19 = v5(v16, "Healing/Defensives");
local v20 = v5(v12, "Holy");
local v21 = v5(v20, "Blessings");
local v22 = v5(v20, "Cooldowns");
local v23 = v5(v20, "Healing");
local v24 = v5(v20, "Special Healing");
local v25 = v5(v20, "Tyr's Deliverance");
local v26 = v5(v20, "Day Break");
local v27 = v5(v20, "AoE Healing");
local v28 = v5(v20, "AoE Healing 2");
local v29 = v5(v20, "Raid Healing");
local v30 = v5(v20, "Raid AoE Healing");
local v31 = v5(v20, "Raid AoE Healing 2");
local v32 = v5(v20, "Raid Special Healing");
local v33 = {"With Cooldowns","With Logic","With Cooldowns and Logic","Not Used"};
local v34 = {"Not Used","Always","With Cooldowns","With Small or Cooldowns","On Mobcount","On Mobcount or Cooldowns","On Bosses","Mobcount or Boss"};
local v35 = {"None","Tank","Healer","Tank and Healer","DD","All"};
local v36 = {"Not Used","Always","With Cooldowns","With Small or Cooldowns","On Mobcount","On Mobcount or Cooldowns","On Bosses","Mobcount or Boss","On HealthPercent"};
local v37 = {"raid1","raid2","raid3","raid4","raid5","raid6","raid7","raid8","raid9","raid10","raid11","raid12","raid13","raid14","raid15","raid16","raid17","raid18","raid19","raid20","raid21","raid22","raid23","raid24","raid25","raid26","raid27","raid28","raid29","raid30","raid31","raid32","raid33","raid34","raid35","raid36","raid37","raid38","raid39","raid40"};
local v38 = {"player","party1","party2","party3","party4"};
local v39 = {"None","Crusader Aura","Devotion Aura","Concentration Aura"};
v8(v12, "APL.Paladin.Commons");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.BubbleHP", {(1500 - (1408 + 92)),(1388 - (993 + 295)),(1172 - (418 + 753))}, "Bubble HP", "Set the Bubble HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.LoHHP", {(0 + 0),(26 + 74),(1770 - (1749 + 20))}, "Lay on Hands HP", "Set the Lay on Hands HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.LoHPartyHP", {(1322 - (1249 + 73)),(1245 - (466 + 679)),(2 - 1)}, "Lay on Hands Party HP", "Set the Lay on Hands on Player HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.BoPHP", {(0 + 0),(295 - 195),(115 - (4 + 110))}, "Blessing of Protection HP", "Set the Blessing of Protection on HP threshold.");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.BoPDebuff", "Blessing of Protection on Debuff", "Use Blessing of Protection on Debuffs");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.GoAKHP", {(1427 - (41 + 1386)),(68 + 32),(2 - 1)}, "Guardian of Ancient Kings HP", "Set the Guardian of Ancient Kings HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.ArdentDefenderHP", {(0 - 0),(82 + 18),(1 - 0)}, "Ardent Defender HP", "Set the Ardent Defender HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.BlessingOfSpellwardingHP", {(0 + 0),(378 - 278),(2 - 1)}, "Blessing Of Spellwarding HP", "Set the party Blessing Of Spellwarding threshold for casting on a friendly.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.WordofGloryPlayerHP", {(320 - (53 + 267)),(513 - (15 + 398)),(3 - 2)}, "Player Word of Glory HP", "Set the Word of Glory HP threshold for casting on ourself: if we drop below this HP, we'll prio WOG over economy globals.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.FreeWordofGloryPlayerHP", {(0 + 0),(79 + 21),(1 + 0)}, "Free Word of Glory Player HP", "Set the Free Word of Glory HP threshold for casting on ourself.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.WordofGloryPartyHP", {(0 - 0),(51 + 49),(2 - 1)}, "Party Word of Glory HP", "Set the party Word of Glory HP threshold for casting on a friendly.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.FreeWordofGloryPartyHP", {(1551 - (1126 + 425)),(391 - 291),(2 - 1)}, "Free Word of Glory Party HP", "Set the Free Word of Glory HP threshold for casting on party.");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.WordofGloryFaithintheLight", "Word of Glory with FitL", "Use Word of Glory with Faith in the Light");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.BlessingOfSacrificeHP", {(0 - 0),(1077 - (553 + 424)),(1 + 0)}, "Blessing of Sacrifice Party HP", "Set the Blessing of Sacrifice HP threshold for casting on party.");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.TankBusters", "Defensives on Tank Busters", "Use Defensives on Tank Busters");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.IntercessionTarget", "Intercession on Target", "Use Intercession on your Target");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.MostDefensive", "Most Defensive", "Will adjust the rotation to be more defensive");
v8(v14, "APL.Paladin.ProtectionDefensives");
v6("CheckButton", v13, "APL.Paladin.Protection.Consecration", "Consecration while moving", "Use Consecration while moving");
v6("CheckButton", v13, "APL.Paladin.Protection.AttackOutOfCombat", "Attack out of combat", "Attack out of combat");
v6("CheckButton", v13, "APL.Paladin.Protection.UseFreedom", "Use Blessing of Freedom", "Use Blessing of Freedom");
v6("CheckButton", v13, "APL.Paladin.Protection.UseBoF", "Enable Blessing of Freedom", "Enable this option to use Blessing of Freedom");
v6("CheckButton", v13, "APL.Paladin.Protection.UseCleanse", "Enable Cleanse", "Enable this option to use Cleanse");
v6("Slider", v13, "APL.Paladin.Protection.Mobcount", {(0 + 0),(35 + 25),(2 - 1)}, "Mobcount", "Mobcount");
v6("Dropdown", v13, "APL.Paladin.Protection.RacialsSetting", v34, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v13, "APL.Paladin.Protection.Trinket1Setting", v36, "Trinket 1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v13, "APL.Paladin.Protection.Trinket2Setting", v36, "Trinket 2 Usage", "Select how to use Trinket 2.");
v6("Slider", v13, "APL.Paladin.Protection.TrinketHP", {(0 + 0),(853 - (239 + 514)),(1330 - (797 + 532))}, "Trinket HP", "HP Value to use the Trinket setting");
v6("Dropdown", v13, "APL.Paladin.Protection.PotionSetting", v34, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v13, "APL.Paladin.Protection.DivineTollSetting", v34, "Divine Toll Usage", "Select how to use Divine Toll.");
v6("Dropdown", v13, "APL.Paladin.Protection.AvengingWrathSetting", v34, "Avenging Wrath Usage", "Select how to use Avenging Wrath.");
v6("Dropdown", v13, "APL.Paladin.Protection.EyeOfTyrSetting", v34, "Eye of Tyr Usage", "Select how to use Eye of Tyr.");
v8(v13, "APL.Paladin.Protection");
v6("Slider", v15, "APL.Paladin.ProtTTD.AvengingWrathTTD", {(0 + 0),(1262 - (373 + 829)),(1131 - (369 + 761))}, "Avenging Wrath TTD", "TTD to use Avenging Wrath on Dungeon Mobs");
v6("Slider", v15, "APL.Paladin.ProtTTD.RacialsTTD", {(0 - 0),(298 - (64 + 174)),(1 - 0)}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v15, "APL.Paladin.ProtTTD.TrinketsTTD", {(216 - (42 + 174)),(50 + 10),(1505 - (363 + 1141))}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v15, "APL.Paladin.ProtTTD.DivineTollTTD", {(0 - 0),(45 + 15),(1 + 0)}, "Divine Toll TTD", "TTD to use Divine Toll on Dungeon Mobs");
v8(v15, "APL.Paladin.ProtTTD");
v6("Slider", v19, "APL.Paladin.RetHealing.BubbleHP", {(1933 - (565 + 1368)),(1761 - (1477 + 184)),(1 + 0)}, "Bubble Player HP", "Set the Bubble on Player HP threshold.");
v6("Slider", v19, "APL.Paladin.RetHealing.LoHHP", {(0 - 0),(404 - (244 + 60)),(477 - (41 + 435))}, "Lay on Hands Player HP", "Set the Lay on Hands on Player HP threshold.");
v6("Slider", v19, "APL.Paladin.RetHealing.LoHPartyHP", {(0 + 0),(33 + 67),(1 + 0)}, "Lay on Hands Party HP", "Set the Lay on Hands on Party HP threshold.");
v6("Slider", v19, "APL.Paladin.RetHealing.BoPHP", {(267 - (176 + 91)),(147 - 47),(1876 - (157 + 1718))}, "Blessing of Protection HP", "Set the Blessing of Protection on HP threshold.");
v6("CheckButton", v19, "APL.Paladin.RetHealing.BoPDebuff", "Blessing of Protection on Debuff", "Use Blessing of Protection on Debuffs");
v6("CheckButton", v19, "APL.Paladin.RetHealing.BoPPlayerOnly", "Blessing of Protection Player only", "Use Blessing of Protection only on Player");
v6("Slider", v19, "APL.Paladin.RetHealing.WordofGloryPlayerHP", {(0 - 0),(1118 - (697 + 321)),(1 - 0)}, "WoG/EF Player HP", "Set the Word of Glory HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.WordofGloryPartyHP", {(0 + 0),(268 - 168),(612 - (602 + 9))}, "WoG/EF Party HP", "Set the Word of Glory HP threshold for casting on party.");
v6("Slider", v19, "APL.Paladin.RetHealing.FlashofLightPlayerHP", {(872 - (826 + 46)),(315 - 215),(1899 - (260 + 1638))}, "Flash of Light Player HP", "Set the Flash of Light HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.FlashofLightPartyHP", {(0 - 0),(206 - 106),(1206 - (902 + 303))}, "Flash of Light Party HP", "Set the Flash of Light HP threshold for casting on party.");
v6("Slider", v19, "APL.Paladin.RetHealing.ShieldofVengeanceHP", {(0 - 0),(1790 - (1121 + 569)),(684 - (483 + 200))}, "Shield of Vengeance Player HP", "Set the Shield of Vengeance Player HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.DivineProtectionHP", {(0 - 0),(865 - (468 + 297)),(3 - 2)}, "Divine Protection Player HP", "Set the Divine Protection HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.BlessingOfSacrificeHP", {(0 - 0),(336 - (141 + 95)),(2 - 1)}, "Blessing of Sacrifice Party HP", "Set the Blessing of Sacrifice HP threshold for casting on party.");
v6("CheckButton", v19, "APL.Paladin.RetHealing.IntercessionTarget", "Intercession on Target", "Use Intercession on your Target");
v6("Dropdown", v19, "APL.Paladin.RetHealing.UnboundFreedomUnit", v38, "Unbound Freedom Unit", "Select the Unit you want to Use your Blessing of Freedom if Unbound Freedom skilled");
v8(v19, "APL.Paladin.RetHealing");
v6("CheckButton", v16, "APL.Paladin.Retribution.AttackOutOfCombat", "Attack out of combat", "Attack out of combat");
v6("CheckButton", v16, "APL.Paladin.Retribution.XalatathsBargain", "Blinding Light for Spheres", "Save Blinding Light for Xal'atath's Bargain");
v6("CheckButton", v16, "APL.Paladin.Retribution.UseBoF", "Enable Blessing of Freedom", "Enable this option to use Blessing of Freedom");
v6("CheckButton", v16, "APL.Paladin.Retribution.UseCleanse", "Enable Cleanse", "Enable this option to use Cleanse");
v6("Dropdown", v16, "APL.Paladin.Retribution.AuraSelect", v39, "Select Aura", "Aura you want to use");
v8(v16, "APL.Paladin.Retribution");
v6("Slider", v17, "APL.Paladin.RetCooldowns.Mobcount", {(0 + 0),(43 + 17),(1 - 0)}, "Mobcount", "Mobcount");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.RacialsSetting", v34, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.Trinket1Setting", v34, "Trinket 1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.Trinket2Setting", v34, "Trinket 2 Usage", "Select how to use Trinket 2.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.PotionSetting", v34, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.DivineTollSetting", v34, "Divine Toll Usage", "Select how to use Divine Toll.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.AvengingWrathSetting", v34, "Avenging Wrath Usage", "Select how to use Avenging Wrath.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.ExecutionSentenceSetting", v34, "Execution Sentence Usage", "Select how to use Execution Sentence.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.FinalReckoningSetting", v34, "Final Reckoning Usage", "Select how to use Final Reckoning.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.CrusadeSetting", v34, "Crusade Usage", "Select how to use Crusade.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.WakeofAshesSetting", v34, "Wake of Ashes Usage", "Select how to use Wake of Ashes.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.WeaponSetting", v34, "Weapon Usage", "Change your Weapon usage.");
v8(v17, "APL.Paladin.RetCooldowns");
v6("Slider", v18, "APL.Paladin.RetTTD.AvengingWrathTTD", {(163 - (92 + 71)),(100 - 40),(1 + 0)}, "Avenging Wrath TTD", "TTD to use Avenging Wrath on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.ExecutionSentenceTTD", {(0 + 0),(186 - (55 + 71)),(1791 - (573 + 1217))}, "Execution Sentence TTD", "TTD to use Execution Sentence on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.FinalReckoningTTD", {(0 + 0),(999 - (714 + 225)),(1 - 0)}, "Final Reckoning TTD", "TTD to use Final Reckoning on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.CrusadeTTD", {(0 - 0),(108 - (25 + 23)),(1887 - (927 + 959))}, "Crusade TTD", "TTD to use Crusade on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.RacialsTTD", {(732 - (16 + 716)),(157 - (11 + 86)),(286 - (175 + 110))}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.TrinketsTTD", {(0 - 0),(167 - 107),(1062 - (810 + 251))}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.DivineTollTTD", {(0 + 0),(593 - (43 + 490)),(3 - 2)}, "Divine Toll TTD", "TTD to use Divine Toll on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.WakeofAshesTTD", {(0 + 0),(4 + 56),(406 - (255 + 150))}, "Wake of Ashes TTD", "TTD to use Wake of Ashes on Dungeon Mobs");
v8(v18, "APL.Paladin.RetTTD");
v6("Slider", v20, "APL.Paladin.Holy.DivineProtectionHP", {(0 + 0),(322 - 222),(407 - (183 + 223))}, "Divine Protection Player HP", "Set the Divine Protection HP Threshold.");
v6("Slider", v20, "APL.Paladin.Holy.BubbleHP", {(0 + 0),(437 - (10 + 327)),(339 - (118 + 220))}, "Bubble HP", "Set the Bubble HP Threshold.");
v6("CheckButton", v20, "APL.Paladin.Holy.Overcap", "Ignore Overcap", "Ignore Overcapping logic and always cast Spenders");
v6("CheckButton", v20, "APL.Paladin.Holy.UseHolyShockDPS", "Use Holy Shock for DPS", "Use Holy Shock for DPS (DPS Only Overrides)?");
v6("CheckButton", v20, "APL.Paladin.Holy.UseDTDPS", "Use Divine Toll during DPS Only", "Use Divine Toll DURING DPS ONLY?");
v6("CheckButton", v20, "APL.Paladin.Holy.ManualBeacon", "Manual Beacons", "Would you like to Manual Beacon?");
v6("CheckButton", v20, "APL.Paladin.Holy.AutoTabMelee", "Auto Tab Melee", "Auto Tab to always a target in melee.");
v6("CheckButton", v20, "APL.Paladin.Holy.UseFreedom", "Use Blessing of Freedom", "Use Blessing of Freedom");
v6("CheckButton", v20, "APL.Paladin.Holy.AttackOOC", "Attack with OOC", "Attack not in Combat?");
v6("CheckButton", v20, "APL.Paladin.Holy.UseBL", "Use Blinding Light", "Use Blinding Light as a Interupt Option?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.AWUsage", v33, "Avenging Wrath Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.ACUsage", v33, "Avenging Crusader Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.AMUsage", v33, "Aura Mastery Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.BoVUsage", v33, "Beacon of Virtue Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.DTUsage", v33, "Divine Toll Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.HPUsage", v33, "Holy Prism Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.Trinket1Use", v33, "Trinket 1 Usage", "How would you like to use this Cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.Trinket2Use", v33, "Trinket 2 Usage", "How would you like to use this Cooldown?");
v6("Slider", v22, "APL.Paladin.HolyCooldowns.Trinket1HP", {(449 - (108 + 341)),(422 - 322),(1 - 0)}, "Trinket 1 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("Slider", v22, "APL.Paladin.HolyCooldowns.Trinket2HP", {(0 + 0),(297 - 197),(1 + 0)}, "Trinket 2 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("CheckButton", v22, "APL.Paladin.HolyCooldowns.ManualSacredWeapon", "Manual Sacred Weapon", "Manual Sacred Weapon Usage?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.SacredWeaponPartyUnit", v38, "Sacred Weapon Party Unit", "Which Unit to Use on?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.SacredWeaponRaidUnit", v37, "Sacred Weapon Raid Unit", "Which Unit to Use on?");
v6("CheckButton", v21, "APL.Paladin.HolyBlessings.ManualBlessings", "Manual Blessings", "Manual Blessings Usage?");
v6("CheckButton", v21, "APL.Paladin.HolyBlessings.SummerOnSelf", "Summer Always on Self", "Blessing of Summer Always on Self?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingofAutumnParty", v38, "Blessing of Autumn Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingofAutumnRaid", v37, "Blessing of Autumn Raid Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfWinterParty", v38, "Blessing of Winter Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfWinterRaid", v37, "Blessing of Wtiner Raid Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfSummerParty", v38, "Blessing of Summer Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfSummerRaid", v37, "Blessing of Summer Raid Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOFSpringParty", v38, "Blessing of Spring Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOFSpringRaid", v37, "Blessing of Spring Raid Unit", "Which Unit to Use on?");
v6("Slider", v27, "APL.Paladin.HolyAoE.AWHP", {(0 - 0),(1267 - (645 + 522)),(1 + 0)}, "Avenging Wrath  HP", "Set the Avenging Wrath  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.AWCount", {(0 - 0),(12 - 7),(506 - (351 + 154))}, "Avenging Wrath Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.ACHP", {(266 - (28 + 238)),(1659 - (1381 + 178)),(1 + 0)}, "Avenging Crusader  HP", "Set the Avenging Crusader  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.ACCount", {(0 - 0),(475 - (381 + 89)),(1 + 0)}, "Avenging Crusder Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.AMHP", {(1156 - (1074 + 82)),(1884 - (214 + 1570)),(1 + 0)}, "Aura Mastery  HP", "Set the Aura Mastery  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.AMCount", {(0 + 0),(1731 - (1668 + 58)),(2 - 1)}, "Aura Mastery Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.BoVHP", {(0 - 0),(19 + 81),(3 - 2)}, "Beacon of Virtue  HP", "Set the Beacon of Virtue  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.BoVCount", {(1469 - (1269 + 200)),(820 - (98 + 717)),(1 - 0)}, "Beacon of Virtue Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.DivineTollHP", {(0 + 0),(17 + 83),(2 - 1)}, "Divine Toll  HP", "Set the Divine Toll  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.DivineTollCount", {(0 + 0),(5 + 0),(1 + 0)}, "Divine Toll Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.LoDHP", {(0 - 0),(35 + 65),(1 + 0)}, "Light of Dawn  HP", "Set the Light of Dawn  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.LoDCount", {(326 - (192 + 134)),(3 + 2),(1 + 0)}, "Light of Dawn Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.TyrsHP", {(551 - (83 + 468)),(466 - 366),(2 - 1)}, "Tyr's Deliverance  HP", "Set the Tyr's Deliverance  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.TyrsCount", {(0 + 0),(2 + 3),(1 + 0)}, "Tyr's Deliverance Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v28, "APL.Paladin.HolyAoE2.HPHP", {(1911 - (340 + 1571)),(1872 - (1733 + 39)),(1035 - (125 + 909))}, "Holy Prism  HP", "Set the Holy Prism  HP Threshold.");
v6("Slider", v28, "APL.Paladin.HolyAoE2.HPCount", {(0 + 0),(5 + 0),(237 - (46 + 190))}, "Holy Prism Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v23, "APL.Paladin.HolyHealing.FoLHP", {(0 + 0),(826 - (228 + 498)),(1 + 0)}, "Flash of Light HP", "Set the Flash of Light HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.FoLIHP", {(0 - 0),(624 - (303 + 221)),(1 + 0)}, "Flash of Light With Infusion HP", "Set the Flash of Light With Infusion HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HLHP", {(0 - 0),(249 - 149),(3 - 2)}, "Holy Light HP", "Set the Holy Light HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HLIHP", {(0 - 0),(1348 - (111 + 1137)),(2 - 1)}, "Holy Light with Infusion HP", "Set the Holy Light with Infusion HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HolyShockHP", {(523 - (423 + 100)),(276 - 176),(772 - (326 + 445))}, "Holy Shock HP", "Set the Holy Shock HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HolyShock2HP", {(0 - 0),(811 - (530 + 181)),(33 - (19 + 13))}, "Holy Shock 2nd Charge HP", "Set the Holy Shock 2nd Charge HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HolyShockRHP", {(0 - 0),(26 + 74),(1 - 0)}, "Holy Shock Rising Sun HP", "Set the Holy Shock Rising Sun HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.WoGHP", {(0 - 0),(191 - 91),(2 - 1)}, "Word of Glory/EF HP", "Set the Word of Glory/Eternal Flame HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.WoGTankHP", {(0 + 0),(24 + 76),(1 + 0)}, "Word of Glory/EF On Tank HP", "Set the Word of Glory/Eternal Flame  On Tank HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.WoGOverHP", {(1858 - (673 + 1185)),(321 - 221),(1 + 0)}, "Word of Glory/EF over LoD HP", "Set the Word of Glory/Eternal Flame  over LoDHP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HBHP", {(0 - 0),(199 - 99),(1881 - (446 + 1434))}, "Holy Bulward HP", "Set the Holy Bulwark HP threshold.");
v6("CheckButton", v23, "APL.Paladin.HolyHealing.HBTank", "Holy Bulwark Tank Only", "Would you like Rotation to only use Holy Bulwark on Tanks (Unless a unit is very low?");
v6("CheckButton", v24, "APL.Paladin.HolySpecialHealing.UseBoP", "Use BoP Logic", "Would you like Rotation to Use Special Logic Outside of Health for BoP??");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.BoPHP", {(0 - 0),(2031 - (609 + 1322)),(3 - 2)}, "Blessing of Protection HP", "Set theBlessing of Protection HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.BoSHP", {(0 - 0),(363 - 263),(1 + 0)}, "Blessing of Sacrfice  HP", "Set the Blessing of Sacrfice HP threshold.");
v6("CheckButton", v24, "APL.Paladin.HolySpecialHealing.UseBoS", "Use BoS Logic", "Would you like Rotation to Use Special Logic Outside of Health for Sac??");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.FoLDFHP", {(0 + 0),(67 + 33),(1 + 0)}, "Divine Favor with Flash of Light HP", "Set the Divine Favor with Flash of Light HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.HLDFHP", {(0 + 0),(288 - 188),(1 + 0)}, "Divine Favor HP", "Set the Divine Favor with Holy Light HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.HLBoth", {(0 + 0),(152 - 52),(668 - (89 + 578))}, "Holy Light /w Both Buffs HP", "Set the Divine Favor with Holy Light with Favor and Infusion HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.FoLBoth", {(0 - 0),(14 + 86),(1 + 0)}, "FoL /w Both Buffs HP", "Set the Divine Favor with Flash of Light with Favor and Infusion HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.HandofDivinityHP", {(0 - 0),(942 - (497 + 345)),(1 + 0)}, "Hand Of Divinity HP", "Set the Hand of Divinity HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.LoHHP", {(0 + 0),(5 + 95),(1 + 0)}, "Lay on Hands HP", "Set the Lay on Hands HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.AwakeningHP", {(0 + 0),(43 + 57),(1 + 0)}, "Awakening HP", "Set the Awakening HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.AwakeningCount", {(0 - 0),(801 - (588 + 208)),(1801 - (884 + 916))}, "Awakening Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.JudgementInAC", {(0 + 0),(1989 - (1569 + 320)),(1 + 0)}, "Judgement In AC Cast", "Set the Judgement In AC threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AWHP", {(605 - (316 + 289)),(5 + 95),(426 - (360 + 65))}, "Avenging Wrath HP", "Set the Avenging Wrath  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AWCount", {(254 - (79 + 175)),(32 + 8),(1 - 0)}, "Avenging Wrath Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.ACHP", {(181 - (92 + 89)),(52 + 48),(3 - 2)}, "Avenging Crusader  HP", "Set the Avenging Crusader  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.ACCount", {(0 - 0),(3 + 2),(1 + 0)}, "Avenging Crusder Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AMHP", {(1244 - (485 + 759)),(1289 - (442 + 747)),(947 - (88 + 858))}, "Aura Mastery  HP", "Set the Aura Mastery  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AMCount", {(0 + 0),(829 - (766 + 23)),(1 - 0)}, "Aura Mastery Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.BoVHP", {(0 - 0),(71 + 29),(1 + 0)}, "Beacon of Virtue  HP", "Set the Beacon of Virtue  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.BoVCount", {(913 - (910 + 3)),(1689 - (1466 + 218)),(1149 - (556 + 592))}, "Beacon of Virtue Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.DivineTollHP", {(808 - (329 + 479)),(343 - 243),(1 + 0)}, "Divine Toll  HP", "Set the Divine Toll  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.DivineTollCount", {(0 + 0),(1394 - (135 + 1254)),(4 - 3)}, "Divine Toll Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.LoDHP", {(1527 - (389 + 1138)),(95 + 5),(1 + 0)}, "Light of Dawn  HP", "Set the Light of Dawn  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.LoDCount", {(0 - 0),(1469 - (157 + 1307)),(2 - 1)}, "Light of Dawn Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.TyrsHP", {(0 - 0),(247 - 147),(1 + 0)}, "Tyr's Deliverance  HP", "Set the Tyr's Deliverance  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.TyrsCount", {(0 + 0),(309 - (300 + 4)),(2 - 1)}, "Tyr's Deliverance Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v31, "APL.Paladin.HolyRaidAoE2.HPHP", {(0 + 0),(58 + 42),(1 + 0)}, "Holy Prism  HP", "Set the Holy Prism  HP Threshold.");
v6("Slider", v31, "APL.Paladin.HolyRaidAoE2.HPCount", {(0 + 0),(11 - 6),(694 - (627 + 66))}, "Holy Prism Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.FoLHP", {(602 - (512 + 90)),(817 - (373 + 344)),(1 + 0)}, "Flash of Light HP", "Set the Flash of Light HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.FoLIHP", {(0 - 0),(73 + 27),(1 + 0)}, "Flash of Light With Infusion HP", "Set the Flash of Light With Infusion HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HLHP", {(1259 - (233 + 1026)),(52 + 48),(1 + 0)}, "Holy Light HP", "Set the Holy Light HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HLIHP", {(221 - (55 + 166)),(11 + 89),(298 - (36 + 261))}, "Holy Light with Infusion HP", "Set the Holy Light with Infusion HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HolyShockHP", {(1368 - (34 + 1334)),(78 + 22),(22 - (20 + 1))}, "Holy Shock HP", "Set the Holy Shock HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HolyShock2HP", {(319 - (134 + 185)),(785 - (314 + 371)),(969 - (478 + 490))}, "Holy Shock 2nd Charge HP", "Set the Holy Shock 2nd Charge HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HolyShockRHP", {(1172 - (786 + 386)),(1479 - (1055 + 324)),(1 + 0)}, "Holy Shock Rising Sun HP", "Set the Holy Shock Rising Sun HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.WoGHP", {(0 - 0),(284 - 184),(1 + 0)}, "Word of Glory/EF HP", "Set the Word of Glory/Eternal Flame  HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.WoGTankHP", {(0 - 0),(255 - 155),(2 - 1)}, "Word of Glory/EF On Tank HP", "Set the Word of Glory/Eternal Flame  On Tank HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.WoGOverHP", {(0 + 0),(160 - 60),(1269 - (1249 + 19))}, "Word of Glory/EF over LoD HP", "Set the Word of Glory/Eternal Flame  over LoDHP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HBHP", {(0 - 0),(79 + 21),(1 + 0)}, "Holy Bulward HP", "Set the Holy Bulwark HP threshold.");
v6("CheckButton", v29, "APL.Paladin.HolyRaidHealing.HBTank", "Holy Bulwark Tank Only", "Would you like Rotation to only use Holy Bulwark on Tanks (Unless a unit is very low?");
v6("CheckButton", v32, "APL.Paladin.HolyRaidSpecialHealing.UseBoP", "Use BoP Logic", "Would you like Rotation to Use Special Logic Outside of Health for BoP??");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.BoPHP", {(0 + 0),(570 - (224 + 246)),(1 - 0)}, "Blessing of Protection HP", "Set theBlessing of Protection HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.BoSHP", {(0 + 0),(198 - 98),(514 - (203 + 310))}, "Blessing of Sacrfice  HP", "Set the Blessing of Sacrfice HP threshold.");
v6("CheckButton", v32, "APL.Paladin.HolyRaidSpecialHealing.UseBoS", "Use BoS Logic", "Would you like Rotation to Use Special Logic Outside of Health for Sac??");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.FoLDFHP", {(0 + 0),(184 - 84),(865 - (196 + 668))}, "Divine Favor with Flash of Light HP", "Set the Divine Favor with Flash of Light HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.HLDFHP", {(0 - 0),(193 - (4 + 89)),(1 + 0)}, "Divine Favor HP", "Set the Divine Favor with Holy Light HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.HLBoth", {(0 + 0),(1553 - (28 + 1425)),(1 + 0)}, "Holy Light /w Both Buffs HP", "Set the Divine Favor with Holy Light with Favor and Infusion HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.FoLBoth", {(0 - 0),(397 - (45 + 252)),(1 + 0)}, "FoL /w Both Buffs HP", "Set the Divine Favor with Flash of Light with Favor and Infusion HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.HandofDivinityHP", {(433 - (114 + 319)),(128 - 28),(1 - 0)}, "Hand Of Divinity HP", "Set the Hand of Divinity HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.LoHHP", {(1963 - (556 + 1407)),(565 - (170 + 295)),(1 + 0)}, "Lay on Hands HP", "Set the Lay on Hands HP threshold.");
v6("CheckButton", v25, "APL.Paladin.HolyTyrs.BeforeTyrs", "Hand of Divinity Before Tyr's", "Attempt to use Hand of Divinity before Tyrs");
v6("Slider", v25, "APL.Paladin.HolyTyrs.TyrFoLHP", {(0 + 0),(57 + 43),(1 + 0)}, "Flash of Light with Tyrs HP", "Set the Flash of Light with Tyrs HP threshold.");
v6("Slider", v25, "APL.Paladin.HolyTyrs.TyrHLHP", {(0 - 0),(305 - 205),(1781 - (389 + 1391))}, "Holy Light with Tyrs HP", "Set the Holy Light with Tyrs HP threshold.");
v8(v32, "APL.Paladin.HolyRaidSpecialHealing");
v8(v30, "APL.Paladin.HolyRaidAoE");
v8(v31, "APL.Paladin.HolyRaidAoE2");
v8(v29, "APL.Paladin.HolyRaidHealing");
v8(v26, "APL.Paladin.HolyDaybreak");
v8(v25, "APL.Paladin.HolyTyrs");
v8(v24, "APL.Paladin.HolySpecialHealing");
v8(v22, "APL.Paladin.HolyCooldowns");
v8(v21, "APL.Paladin.HolyBlessings");
v8(v27, "APL.Paladin.HolyAoE");
v8(v28, "APL.Paladin.HolyAoE2");
v8(v23, "APL.Paladin.HolyHealing");
v8(v20, "APL.Paladin.Holy");
v9.APL.Paladin.Holy.Display = function()
	v3.GUI.HidePanel(v26);
	v3.GUI.ShowPanel(v25);
	v3.GUI.ShowPanel(v24);
	v3.GUI.ShowPanel(v22);
	v3.GUI.ShowPanel(v27);
	v3.GUI.ShowPanel(v23);
	v3.GUI.ShowPanel(v20);
	v3.GUI.ShowPanel(v30);
	v3.GUI.ShowPanel(v29);
	v3.GUI.ShowPanel(v32);
	v3.GUI.ShowPanel(v28);
	v3.GUI.ShowPanel(v31);
	v3.GUI.ShowPanel(v21);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v13);
	v3.GUI.HidePanel(v14);
end;
v9.APL.Paladin.Retribution.Display = function()
	v3.GUI.ShowPanel(v18);
	v3.GUI.ShowPanel(v16);
	v3.GUI.ShowPanel(v17);
	v3.GUI.ShowPanel(v19);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v13);
	v3.GUI.HidePanel(v14);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v32);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v31);
	v3.GUI.HidePanel(v21);
end;
v9.APL.Paladin.Protection.Display = function()
	v3.GUI.ShowPanel(v13);
	v3.GUI.ShowPanel(v14);
	v3.GUI.ShowPanel(v15);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v32);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v31);
	v3.GUI.HidePanel(v21);
end;
