local v0, v1 = ...;
local v2 = HeroRotation();
local v3 = HeroLib;
local v4 = v3.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v2.HRGUIGet().CreateARPanelOption;
local v8 = v2.HRGUIGet().CreateARPanelOptions;
local v9 = v2.GUISettingsGet();
v9.APL.Paladin = {Commons={Enabled={Trinkets=true,Potions=true,Items=true}},Protection={PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},Consecration=true,UseBoF=true,UseCleanse=true,AttackOutOfCombat=true,UseFreedom=true,Mobcount=(12 - 8),AvengingWrathSetting="With Cooldowns",RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",TrinketHP=(114 - 74),PotionSetting="With Cooldowns",DivineTollSetting="With Cooldowns",EyeOfTyrSetting="With Cooldowns"},ProtectionDefensives={BubbleHP=(28 - 13),LoHHP=(38 - 23),BoPHP=(639 - (555 + 64)),BoPDebuff=true,GoAKHP=(971 - (857 + 74)),WordofGloryPlayerHP=(608 - (367 + 201)),FreeWordofGloryPlayerHP=(1017 - (214 + 713)),WordofGloryPartyHP=(6 + 14),FreeWordofGloryPartyHP=(10 + 50),WordofGloryFaithintheLight=true,ArdentDefenderHP=(937 - (282 + 595)),LoHPartyHP=(1647 - (1523 + 114)),BlessingOfSacrificeHP=(27 + 3),BlessingOfSpellwardingHP=(35 - 10),TankBusters=true,IntercessionTarget=true,MostDefensive=true},ProtTTD={AvengingWrathTTD=(1085 - (68 + 997)),RacialsTTD=(1290 - (226 + 1044)),TrinketsTTD=(87 - 67),DivineTollTTD=(137 - (32 + 85))},Retribution={AuraSelect="Crusader Aura",PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},AttackOutOfCombat=false,UseCleanse=true,UseBoF=true,XalatathsBargain=true},RetCooldowns={Mobcount=(2 + 0),AvengingWrathSetting="With Cooldowns",ExecutionSentenceSetting="With Cooldowns",FinalReckoningSetting="With Cooldowns",CrusadeSetting="With Cooldowns",RacialsSetting="With Cooldowns",Trinket1Setting="With Cooldowns",Trinket2Setting="With Cooldowns",PotionSetting="With Cooldowns",DivineTollSetting="With Cooldowns",WakeofAshesSetting="With Cooldowns",DivineHammerSetting="With Cooldowns",WeaponSetting="With Cooldowns"},RetHealing={BubbleHP=(4 + 11),LoHHP=(972 - (892 + 65)),LoHPartyHP=(23 - 13),WordofGloryPlayerHP=(27 - 12),WordofGloryPartyHP=(0 - 0),FlashofLightPlayerHP=(350 - (87 + 263)),FlashofLightPartyHP=(180 - (67 + 113)),ShieldofVengeanceHP=(70 + 25),DivineProtectionHP=(122 - 72),BoPHP=(15 + 5),BlessingOfSacrificeHP=(119 - 89),BoPDebuff=true,BoPPlayerOnly=false,UnboundFreedomUnit="party1",IntercessionTarget=true},RetTTD={AvengingWrathTTD=(972 - (802 + 150)),ExecutionSentenceTTD=(53 - 33),FinalReckoningTTD=(36 - 16),CrusadeTTD=(15 + 5),RacialsTTD=(1017 - (915 + 82)),TrinketsTTD=(56 - 36),DivineTollTTD=(12 + 8),WakeofAshesTTD=(26 - 6),DivineHammerTTD=(1207 - (1069 + 118))},Holy={BubbleHP=(33 - 18),DivineProtectionHP=(109 - 59),Overcap=true,UseSoTR=false,UseDTDPS=false,UseHolyShockDPS=true,ManualBeacon=false,AutoTabMelee=false,EntangleSelf=true,AttackOOC=false,UseFreedom=true,UseBL=false,PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"}},HolyBlessings={ManualBlessings=false,SummerOnSelf=true,BlessingofAutumnParty="player",BlessingofAutumnRaid="raid1",BlessingOfWinterParty="player",BlessingOfWinterRaid="raid1",BlessingOfSummerParty="player",BlessingOfSummerRaid="raid1",BlessingOFSpringParty="player",BlessingOFSpringRaid="raid1"},HolyCooldowns={AWUsage="With Logic",ACUsage="With Logic",DayUsage="With Logic",AMUsage="With Logic",BoVUsage="With Logic",DTUsage="With Logic",LHUsage="With Logic",HPUsage="With Logic",Trinket1Use="With Logic",Trinket2Use="With Logic",Trinket1HP=(12 + 53),Trinket2HP=(115 - 50),ManualSacredWeapon=false,SacredWeaponPartyUnit="player",SacredWeaponRaidUnit="raid1"},HolyAoE={AWHP=(45 + 0),AWCount=(793 - (368 + 423)),ACHP=(201 - 137),ACCount=(21 - (10 + 8)),AMHP=(0 - 0),AMCount=(446 - (416 + 26)),BoVHP=(267 - 183),BoVCount=(2 + 1),DivineTollHP=(156 - 67),DivineTollCount=(441 - (145 + 293)),LoDHP=(430 - (44 + 386)),LoDCount=(1491 - (998 + 488)),TyrsHP=(0 + 0),TyrsCount=(5 + 0)},HolyAoE2={HPHP=(861 - (201 + 571)),LHHP=(1218 - (116 + 1022)),HPCount=(12 - 9),LHCount=(2 + 1)},HolyHealing={FoLHP=(0 - 0),FoLIHP=(0 - 0),HLHP=(859 - (814 + 45)),HLIHP=(0 - 0),HolyShockHP=(5 + 76),HolyShock2HP=(29 + 53),HolyShockRHP=(972 - (261 + 624)),WoGHP=(157 - 68),WoGTankHP=(1163 - (1020 + 60)),WoGOverHP=(1423 - (630 + 793)),HBHP=(331 - 233),HBTank=true},HolySpecialHealing={UseBoP=false,BoPHP=(0 - 0),BoSHP=(0 + 0),UseBoS=false,FoLDFHP=(0 - 0),HLDFHP=(1747 - (760 + 987)),HLBoth=(1987 - (1789 + 124)),FoLBoth=(766 - (745 + 21)),HandofDivinityHP=(26 + 48),LoHHP=(27 - 17),JudgementInAC=(384 - 286),AwakeningCount=(1 + 0),AwakeningHP=(66 + 18),DivineFavorHP=(1055 - (87 + 968))},HolyRaidAoE={AWHP=(347 - 268),AWCount=(8 + 0),ACHP=(178 - 99),ACCount=(1418 - (447 + 966)),AMHP=(0 - 0),AMCount=(1857 - (1703 + 114)),BoVHP=(790 - (376 + 325)),BoVCount=(8 - 3),DivineTollHP=(273 - 184),DivineTollCount=(2 + 2),LoDHP=(0 - 0),LoDCount=(19 - (9 + 5)),TyrsHP=(376 - (85 + 291)),TyrsCount=(1270 - (243 + 1022))},HolyRaidAoE2={HPHP=(338 - 249),LHHP=(66 + 14),HPCount=(1184 - (1123 + 57)),LHCount=(3 + 0)},HolyRaidHealing={FoLHP=(254 - (163 + 91)),FoLIHP=(1930 - (1869 + 61)),HLHP=(0 + 0),HLIHP=(0 - 0),HolyShockHP=(143 - 49),HolyShock2HP=(12 + 73),HolyShockRHP=(123 - 33),WoGHP=(87 + 5),WoGTankHP=(1559 - (1329 + 145)),WoGOverHP=(971 - (140 + 831)),HBHP=(1948 - (1409 + 441)),HBTank=true},HolyRaidSpecialHealing={UseBoP=false,BoPHP=(718 - (15 + 703)),BoSHP=(0 + 0),UseBoS=false,FoLDFHP=(438 - (262 + 176)),HLDFHP=(1721 - (345 + 1376)),HLBoth=(762 - (198 + 490)),FoLBoth=(0 - 0),HandofDivinityHP=(177 - 103),LoHHP=(1216 - (696 + 510)),JudgementInAC=(205 - 107),AwakeningCount=(1263 - (1091 + 171)),AwakeningHP=(14 + 70),DivineFavorHP=(0 - 0)},HolyTyrs={BeforeTyrs=false,TyrFoLHP=(0 - 0),TyrHLHP=(374 - (123 + 251))},HolyDaybreak={DaybreakHP=(397 - 317),DaybreakCount=(703 - (208 + 490)),DaybreakAfterDT=true,DayBreakCombo=true,DaybreakComboHP=(8 + 82),DaybreakComboUnit=(3 + 2)}};
v2.HRGUIGet().LoadSettingsRecursively(v9);
local v11 = v2.HRGUIGet().Panel;
local v12 = v5(v11, "Paladin");
local v13 = v5(v12, "Protection");
local v14 = v5(v13, "Defensives");
local v15 = v5(v13, "TTD");
local v16 = v5(v12, "Retribution");
local v17 = v5(v12, "Cooldowns");
local v18 = v5(v16, "TTD");
local v19 = v5(v16, "Healing/Defensives");
local v20 = v5(v12, "Holy");
local v21 = v5(v20, "Blessings");
local v22 = v5(v20, "Cooldowns");
local v23 = v5(v20, "Healing");
local v24 = v5(v20, "Special Healing");
local v25 = v5(v20, "Tyr's Deliverance");
local v26 = v5(v20, "Day Break");
local v27 = v5(v20, "AoE Healing");
local v28 = v5(v20, "AoE Healing 2");
local v29 = v5(v20, "Raid Healing");
local v30 = v5(v20, "Raid AoE Healing");
local v31 = v5(v20, "Raid AoE Healing 2");
local v32 = v5(v20, "Raid Special Healing");
local v33 = {"With Cooldowns","With Logic","With Cooldowns and Logic","Not Used"};
local v34 = {"Not Used","Always","With Cooldowns","With Small or Cooldowns","On Mobcount","On Mobcount or Cooldowns","On Bosses","Mobcount or Boss"};
local v35 = {"None","Tank","Healer","Tank and Healer","DD","All"};
local v36 = {"Not Used","Always","With Cooldowns","With Small or Cooldowns","On Mobcount","On Mobcount or Cooldowns","On Bosses","Mobcount or Boss","On HealthPercent"};
local v37 = {"raid1","raid2","raid3","raid4","raid5","raid6","raid7","raid8","raid9","raid10","raid11","raid12","raid13","raid14","raid15","raid16","raid17","raid18","raid19","raid20","raid21","raid22","raid23","raid24","raid25","raid26","raid27","raid28","raid29","raid30","raid31","raid32","raid33","raid34","raid35","raid36","raid37","raid38","raid39","raid40"};
local v38 = {"player","party1","party2","party3","party4"};
local v39 = {"None","Crusader Aura","Devotion Aura","Concentration Aura"};
v8(v12, "APL.Paladin.Commons");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.BubbleHP", {(0 + 0),(629 - (406 + 123)),(1 + 0)}, "Bubble HP", "Set the Bubble HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.LoHHP", {(0 + 0),(240 - 140),(1901 - (106 + 1794))}, "Lay on Hands HP", "Set the Lay on Hands HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.LoHPartyHP", {(0 + 0),(270 - 170),(585 - (57 + 527))}, "Lay on Hands Party HP", "Set the Lay on Hands on Player HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.BoPHP", {(103 - (17 + 86)),(223 - 123),(167 - (122 + 44))}, "Blessing of Protection HP", "Set the Blessing of Protection on HP threshold.");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.BoPDebuff", "Blessing of Protection on Debuff", "Use Blessing of Protection on Debuffs");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.GoAKHP", {(0 - 0),(15 + 85),(66 - (30 + 35))}, "Guardian of Ancient Kings HP", "Set the Guardian of Ancient Kings HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.ArdentDefenderHP", {(1257 - (1043 + 214)),(1312 - (323 + 889)),(581 - (361 + 219))}, "Ardent Defender HP", "Set the Ardent Defender HP threshold.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.BlessingOfSpellwardingHP", {(0 + 0),(1082 - (18 + 964)),(1 + 0)}, "Blessing Of Spellwarding HP", "Set the party Blessing Of Spellwarding threshold for casting on a friendly.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.WordofGloryPlayerHP", {(850 - (20 + 830)),(226 - (116 + 10)),(739 - (542 + 196))}, "Player Word of Glory HP", "Set the Word of Glory HP threshold for casting on ourself: if we drop below this HP, we'll prio WOG over economy globals.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.FreeWordofGloryPlayerHP", {(0 + 0),(36 + 64),(2 - 1)}, "Free Word of Glory Player HP", "Set the Free Word of Glory HP threshold for casting on ourself.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.WordofGloryPartyHP", {(405 - (118 + 287)),(1221 - (118 + 1003)),(378 - (142 + 235))}, "Party Word of Glory HP", "Set the party Word of Glory HP threshold for casting on a friendly.");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.FreeWordofGloryPartyHP", {(0 + 0),(189 - 89),(1 + 0)}, "Free Word of Glory Party HP", "Set the Free Word of Glory HP threshold for casting on party.");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.WordofGloryFaithintheLight", "Word of Glory with FitL", "Use Word of Glory with Faith in the Light");
v6("Slider", v14, "APL.Paladin.ProtectionDefensives.BlessingOfSacrificeHP", {(0 + 0),(216 - 116),(2 - 1)}, "Blessing of Sacrifice Party HP", "Set the Blessing of Sacrifice HP threshold for casting on party.");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.TankBusters", "Defensives on Tank Busters", "Use Defensives on Tank Busters");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.IntercessionTarget", "Intercession on Target", "Use Intercession on your Target");
v6("CheckButton", v14, "APL.Paladin.ProtectionDefensives.MostDefensive", "Most Defensive", "Will adjust the rotation to be more defensive");
v8(v14, "APL.Paladin.ProtectionDefensives");
v6("CheckButton", v13, "APL.Paladin.Protection.Consecration", "Consecration while moving", "Use Consecration while moving");
v6("CheckButton", v13, "APL.Paladin.Protection.AttackOutOfCombat", "Attack out of combat", "Attack out of combat");
v6("CheckButton", v13, "APL.Paladin.Protection.UseFreedom", "Use Blessing of Freedom", "Use Blessing of Freedom");
v6("CheckButton", v13, "APL.Paladin.Protection.UseBoF", "Enable Blessing of Freedom", "Enable this option to use Blessing of Freedom");
v6("CheckButton", v13, "APL.Paladin.Protection.UseCleanse", "Enable Cleanse", "Enable this option to use Cleanse");
v6("Slider", v13, "APL.Paladin.Protection.Mobcount", {(0 - 0),(22 + 38),(1 + 0)}, "Mobcount", "Mobcount");
v6("Dropdown", v13, "APL.Paladin.Protection.RacialsSetting", v34, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v13, "APL.Paladin.Protection.Trinket1Setting", v36, "Trinket 1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v13, "APL.Paladin.Protection.Trinket2Setting", v36, "Trinket 2 Usage", "Select how to use Trinket 2.");
v6("Slider", v13, "APL.Paladin.Protection.TrinketHP", {(0 - 0),(831 - (476 + 255)),(1 + 0)}, "Trinket HP", "HP Value to use the Trinket setting");
v6("Dropdown", v13, "APL.Paladin.Protection.PotionSetting", v34, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v13, "APL.Paladin.Protection.DivineTollSetting", v34, "Divine Toll Usage", "Select how to use Divine Toll.");
v6("Dropdown", v13, "APL.Paladin.Protection.AvengingWrathSetting", v34, "Avenging Wrath Usage", "Select how to use Avenging Wrath.");
v6("Dropdown", v13, "APL.Paladin.Protection.EyeOfTyrSetting", v34, "Eye of Tyr Usage", "Select how to use Eye of Tyr.");
v8(v13, "APL.Paladin.Protection");
v6("Slider", v15, "APL.Paladin.ProtTTD.AvengingWrathTTD", {(0 - 0),(9 + 51),(337 - (144 + 192))}, "Avenging Wrath TTD", "TTD to use Avenging Wrath on Dungeon Mobs");
v6("Slider", v15, "APL.Paladin.ProtTTD.RacialsTTD", {(0 + 0),(26 + 34),(1581 - (1183 + 397))}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v15, "APL.Paladin.ProtTTD.TrinketsTTD", {(0 + 0),(2035 - (1913 + 62)),(2 - 1)}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v15, "APL.Paladin.ProtTTD.DivineTollTTD", {(0 - 0),(81 - 21),(857 - (564 + 292))}, "Divine Toll TTD", "TTD to use Divine Toll on Dungeon Mobs");
v8(v15, "APL.Paladin.ProtTTD");
v6("Slider", v19, "APL.Paladin.RetHealing.BubbleHP", {(0 - 0),(77 + 23),(1002 - (938 + 63))}, "Bubble Player HP", "Set the Bubble on Player HP threshold.");
v6("Slider", v19, "APL.Paladin.RetHealing.LoHHP", {(1125 - (936 + 189)),(1713 - (1565 + 48)),(1139 - (782 + 356))}, "Lay on Hands Player HP", "Set the Lay on Hands on Player HP threshold.");
v6("Slider", v19, "APL.Paladin.RetHealing.LoHPartyHP", {(0 - 0),(1192 - (975 + 117)),(1 + 0)}, "Lay on Hands Party HP", "Set the Lay on Hands on Party HP threshold.");
v6("Slider", v19, "APL.Paladin.RetHealing.BoPHP", {(0 - 0),(272 - 172),(2 - 1)}, "Blessing of Protection HP", "Set the Blessing of Protection on HP threshold.");
v6("CheckButton", v19, "APL.Paladin.RetHealing.BoPDebuff", "Blessing of Protection on Debuff", "Use Blessing of Protection on Debuffs");
v6("CheckButton", v19, "APL.Paladin.RetHealing.BoPPlayerOnly", "Blessing of Protection Player only", "Use Blessing of Protection only on Player");
v6("Slider", v19, "APL.Paladin.RetHealing.WordofGloryPlayerHP", {(0 - 0),(1327 - (322 + 905)),(1190 - (449 + 740))}, "WoG/EF Player HP", "Set the Word of Glory HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.WordofGloryPartyHP", {(947 - (245 + 702)),(33 + 67),(441 - (382 + 58))}, "WoG/EF Party HP", "Set the Word of Glory HP threshold for casting on party.");
v6("Slider", v19, "APL.Paladin.RetHealing.FlashofLightPlayerHP", {(0 + 0),(297 - 197),(1 - 0)}, "Flash of Light Player HP", "Set the Flash of Light HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.FlashofLightPartyHP", {(0 + 0),(314 - (22 + 192)),(1464 - (1404 + 59))}, "Flash of Light Party HP", "Set the Flash of Light HP threshold for casting on party.");
v6("Slider", v19, "APL.Paladin.RetHealing.ShieldofVengeanceHP", {(0 - 0),(662 - (334 + 228)),(2 - 1)}, "Shield of Vengeance Player HP", "Set the Shield of Vengeance Player HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.DivineProtectionHP", {(0 + 0),(99 + 1),(2 - 1)}, "Divine Protection Player HP", "Set the Divine Protection HP threshold for casting on ourself.");
v6("Slider", v19, "APL.Paladin.RetHealing.BlessingOfSacrificeHP", {(0 - 0),(53 + 47),(1 + 0)}, "Blessing of Sacrifice Party HP", "Set the Blessing of Sacrifice HP threshold for casting on party.");
v6("CheckButton", v19, "APL.Paladin.RetHealing.IntercessionTarget", "Intercession on Target", "Use Intercession on your Target");
v6("Dropdown", v19, "APL.Paladin.RetHealing.UnboundFreedomUnit", v38, "Unbound Freedom Unit", "Select the Unit you want to Use your Blessing of Freedom if Unbound Freedom skilled");
v8(v19, "APL.Paladin.RetHealing");
v6("CheckButton", v16, "APL.Paladin.Retribution.AttackOutOfCombat", "Attack out of combat", "Attack out of combat");
v6("CheckButton", v16, "APL.Paladin.Retribution.XalatathsBargain", "Blinding Light for Spheres", "Save Blinding Light for Xal'atath's Bargain");
v6("CheckButton", v16, "APL.Paladin.Retribution.UseBoF", "Enable Blessing of Freedom", "Enable this option to use Blessing of Freedom");
v6("CheckButton", v16, "APL.Paladin.Retribution.UseCleanse", "Enable Cleanse", "Enable this option to use Cleanse");
v6("Dropdown", v16, "APL.Paladin.Retribution.AuraSelect", v39, "Select Aura", "Aura you want to use");
v8(v16, "APL.Paladin.Retribution");
v6("Slider", v17, "APL.Paladin.RetCooldowns.Mobcount", {(0 + 0),(825 - (574 + 191)),(2 - 1)}, "Mobcount", "Mobcount");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.RacialsSetting", v34, "Racials Usage", "Select how to use Racials.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.Trinket1Setting", v34, "Trinket 1 Usage", "Select how to use Trinket 1.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.Trinket2Setting", v34, "Trinket 2 Usage", "Select how to use Trinket 2.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.PotionSetting", v34, "Potion Usage", "Select how to use Potion.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.DivineTollSetting", v34, "Divine Toll Usage", "Select how to use Divine Toll.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.AvengingWrathSetting", v34, "Avenging Wrath Usage", "Select how to use Avenging Wrath.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.ExecutionSentenceSetting", v34, "Execution Sentence Usage", "Select how to use Execution Sentence.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.FinalReckoningSetting", v34, "Final Reckoning Usage", "Select how to use Final Reckoning.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.CrusadeSetting", v34, "Crusade Usage", "Select how to use Crusade.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.WakeofAshesSetting", v34, "Wake of Ashes Usage", "Select how to use Wake of Ashes.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.DivineHammerSetting", v34, "Divine Hammer Usage", "Select how to use Divine Hammer.");
v6("Dropdown", v17, "APL.Paladin.RetCooldowns.WeaponSetting", v34, "Weapon Usage", "Change your Weapon usage.");
v8(v17, "APL.Paladin.RetCooldowns");
v6("Slider", v18, "APL.Paladin.RetTTD.AvengingWrathTTD", {(849 - (254 + 595)),(79 - 19),(2 - 1)}, "Avenging Wrath TTD", "TTD to use Avenging Wrath on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.ExecutionSentenceTTD", {(0 - 0),(175 - 115),(1 + 0)}, "Execution Sentence TTD", "TTD to use Execution Sentence on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.FinalReckoningTTD", {(806 - (118 + 688)),(12 + 48),(3 - 2)}, "Final Reckoning TTD", "TTD to use Final Reckoning on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.CrusadeTTD", {(0 - 0),(146 - 86),(2 - 1)}, "Crusade TTD", "TTD to use Crusade on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.RacialsTTD", {(1796 - (503 + 1293)),(44 + 16),(1 + 0)}, "Racials TTD", "TTD to use Racials on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.TrinketsTTD", {(0 + 0),(793 - (711 + 22)),(860 - (240 + 619))}, "Trinkets TTD", "TTD to use Trinkets on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.DivineTollTTD", {(0 - 0),(1804 - (1344 + 400)),(1 + 0)}, "Divine Toll TTD", "TTD to use Divine Toll on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.WakeofAshesTTD", {(0 - 0),(1799 - (404 + 1335)),(1 - 0)}, "Wake of Ashes TTD", "TTD to use Wake of Ashes on Dungeon Mobs");
v6("Slider", v18, "APL.Paladin.RetTTD.DivineHammerTTD", {(0 + 0),(42 + 18),(1 + 0)}, "Wake of Ashes TTD", "TTD to use Wake of Ashes on Dungeon Mobs");
v8(v18, "APL.Paladin.RetTTD");
v6("Slider", v20, "APL.Paladin.Holy.DivineProtectionHP", {(0 + 0),(1593 - (711 + 782)),(470 - (270 + 199))}, "Divine Protection Player HP", "Set the Divine Protection HP Threshold.");
v6("Slider", v20, "APL.Paladin.Holy.BubbleHP", {(1819 - (580 + 1239)),(96 + 4),(1 + 0)}, "Bubble HP", "Set the Bubble HP Threshold.");
v6("CheckButton", v20, "APL.Paladin.Holy.Overcap", "Ignore Overcap", "Ignore Overcapping logic and always cast Spenders");
v6("CheckButton", v20, "APL.Paladin.Holy.UseHolyShockDPS", "Use Holy Shock for DPS", "Use Holy Shock for DPS (DPS Only Overrides)?");
v6("CheckButton", v20, "APL.Paladin.Holy.UseDTDPS", "Use Divine Toll during DPS Only", "Use Divine Toll DURING DPS ONLY?");
v6("CheckButton", v20, "APL.Paladin.Holy.ManualBeacon", "Manual Beacons", "Would you like to Manual Beacon?");
v6("CheckButton", v20, "APL.Paladin.Holy.AutoTabMelee", "Auto Tab Melee", "Auto Tab to always a target in melee.");
v6("CheckButton", v20, "APL.Paladin.Holy.UseFreedom", "Use Blessing of Freedom", "Use Blessing of Freedom");
v6("CheckButton", v20, "APL.Paladin.Holy.AttackOOC", "Attack with OOC", "Attack not in Combat?");
v6("CheckButton", v20, "APL.Paladin.Holy.UseBL", "Use Blinding Light", "Use Blinding Light as a Interupt Option?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.AWUsage", v33, "Avenging Wrath Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.ACUsage", v33, "Avenging Crusader Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.AMUsage", v33, "Aura Mastery Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.BoVUsage", v33, "Beacon of Virtue Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.DTUsage", v33, "Divine Toll Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.HPUsage", v33, "Holy Prism Usage", "How you would like to use this cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.Trinket1Use", v33, "Trinket 1 Usage", "How would you like to use this Cooldown?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.Trinket2Use", v33, "Trinket 2 Usage", "How would you like to use this Cooldown?");
v6("Slider", v22, "APL.Paladin.HolyCooldowns.Trinket1HP", {(0 + 0),(1890 - (1010 + 780)),(4 - 3)}, "Trinket 1 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("Slider", v22, "APL.Paladin.HolyCooldowns.Trinket2HP", {(1836 - (1045 + 791)),(152 - 52),(1575 - (1281 + 293))}, "Trinket 2 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("CheckButton", v22, "APL.Paladin.HolyCooldowns.ManualSacredWeapon", "Manual Sacred Weapon", "Manual Sacred Weapon Usage?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.SacredWeaponPartyUnit", v38, "Sacred Weapon Party Unit", "Which Unit to Use on?");
v6("Dropdown", v22, "APL.Paladin.HolyCooldowns.SacredWeaponRaidUnit", v37, "Sacred Weapon Raid Unit", "Which Unit to Use on?");
v6("CheckButton", v21, "APL.Paladin.HolyBlessings.ManualBlessings", "Manual Blessings", "Manual Blessings Usage?");
v6("CheckButton", v21, "APL.Paladin.HolyBlessings.SummerOnSelf", "Summer Always on Self", "Blessing of Summer Always on Self?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingofAutumnParty", v38, "Blessing of Autumn Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingofAutumnRaid", v37, "Blessing of Autumn Raid Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfWinterParty", v38, "Blessing of Winter Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfWinterRaid", v37, "Blessing of Wtiner Raid Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfSummerParty", v38, "Blessing of Summer Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOfSummerRaid", v37, "Blessing of Summer Raid Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOFSpringParty", v38, "Blessing of Spring Party Unit", "Which Unit to Use on?");
v6("Dropdown", v21, "APL.Paladin.HolyBlessings.BlessingOFSpringRaid", v37, "Blessing of Spring Raid Unit", "Which Unit to Use on?");
v6("Slider", v27, "APL.Paladin.HolyAoE.AWHP", {(0 - 0),(94 + 6),(1 + 0)}, "Avenging Wrath  HP", "Set the Avenging Wrath  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.AWCount", {(0 + 0),(5 + 0),(1 - 0)}, "Avenging Wrath Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.ACHP", {(0 - 0),(1555 - (990 + 465)),(1 + 0)}, "Avenging Crusader  HP", "Set the Avenging Crusader  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.ACCount", {(0 - 0),(631 - (512 + 114)),(1 - 0)}, "Avenging Crusder Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.AMHP", {(0 + 0),(87 + 13),(1995 - (109 + 1885))}, "Aura Mastery  HP", "Set the Aura Mastery  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.AMCount", {(0 - 0),(831 - (802 + 24)),(1 - 0)}, "Aura Mastery Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.BoVHP", {(0 + 0),(22 + 78),(3 - 2)}, "Beacon of Virtue  HP", "Set the Beacon of Virtue  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.BoVCount", {(0 + 0),(4 + 1),(1434 - (797 + 636))}, "Beacon of Virtue Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.DivineTollHP", {(1619 - (1427 + 192)),(232 - 132),(1 + 0)}, "Divine Toll  HP", "Set the Divine Toll  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.DivineTollCount", {(1276 - (316 + 960)),(4 + 1),(3 - 2)}, "Divine Toll Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.LoDHP", {(1806 - (1202 + 604)),(166 - 66),(326 - (45 + 280))}, "Light of Dawn  HP", "Set the Light of Dawn  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.LoDCount", {(0 + 0),(3 + 2),(1 - 0)}, "Light of Dawn Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Paladin.HolyAoE.TyrsHP", {(0 + 0),(274 - 174),(1949 - (1096 + 852))}, "Tyr's Deliverance  HP", "Set the Tyr's Deliverance  HP Threshold.");
v6("Slider", v27, "APL.Paladin.HolyAoE.TyrsCount", {(0 - 0),(517 - (409 + 103)),(96 - (51 + 44))}, "Tyr's Deliverance Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v28, "APL.Paladin.HolyAoE2.HPHP", {(1317 - (1114 + 203)),(22 + 78),(664 - (174 + 489))}, "Holy Prism  HP", "Set the Holy Prism  HP Threshold.");
v6("Slider", v28, "APL.Paladin.HolyAoE2.HPCount", {(1905 - (830 + 1075)),(1274 - (231 + 1038)),(1163 - (171 + 991))}, "Holy Prism Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v23, "APL.Paladin.HolyHealing.FoLHP", {(0 - 0),(81 + 19),(2 - 1)}, "Flash of Light HP", "Set the Flash of Light HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.FoLIHP", {(0 - 0),(258 - (91 + 67)),(1 + 0)}, "Flash of Light With Infusion HP", "Set the Flash of Light With Infusion HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HLHP", {(0 + 0),(53 + 47),(4 - 3)}, "Holy Light HP", "Set the Holy Light HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HLIHP", {(0 - 0),(981 - (614 + 267)),(1 - 0)}, "Holy Light with Infusion HP", "Set the Holy Light with Infusion HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HolyShockHP", {(0 - 0),(175 - 75),(1813 - (1293 + 519))}, "Holy Shock HP", "Set the Holy Shock HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HolyShock2HP", {(0 - 0),(431 - 331),(1 + 0)}, "Holy Shock 2nd Charge HP", "Set the Holy Shock 2nd Charge HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HolyShockRHP", {(0 - 0),(34 + 66),(1097 - (709 + 387))}, "Holy Shock Rising Sun HP", "Set the Holy Shock Rising Sun HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.WoGHP", {(0 - 0),(164 - 64),(1 + 0)}, "Word of Glory/EF HP", "Set the Word of Glory/Eternal Flame HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.WoGTankHP", {(0 + 0),(196 - 96),(1284 - (1040 + 243))}, "Word of Glory/EF On Tank HP", "Set the Word of Glory/Eternal Flame  On Tank HP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.WoGOverHP", {(1847 - (559 + 1288)),(554 - (13 + 441)),(2 - 1)}, "Word of Glory/EF over LoD HP", "Set the Word of Glory/Eternal Flame  over LoDHP threshold.");
v6("Slider", v23, "APL.Paladin.HolyHealing.HBHP", {(0 + 0),(36 + 64),(2 - 1)}, "Holy Bulward HP", "Set the Holy Bulwark HP threshold.");
v6("CheckButton", v23, "APL.Paladin.HolyHealing.HBTank", "Holy Bulwark Tank Only", "Would you like Rotation to only use Holy Bulwark on Tanks (Unless a unit is very low?");
v6("CheckButton", v24, "APL.Paladin.HolySpecialHealing.UseBoP", "Use BoP Logic", "Would you like Rotation to Use Special Logic Outside of Health for BoP??");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.BoPHP", {(0 - 0),(56 + 44),(1 + 0)}, "Blessing of Protection HP", "Set theBlessing of Protection HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.BoSHP", {(433 - (153 + 280)),(90 + 10),(1 + 0)}, "Blessing of Sacrfice  HP", "Set the Blessing of Sacrfice HP threshold.");
v6("CheckButton", v24, "APL.Paladin.HolySpecialHealing.UseBoS", "Use BoS Logic", "Would you like Rotation to Use Special Logic Outside of Health for Sac??");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.FoLDFHP", {(0 + 0),(62 + 38),(1 + 0)}, "Divine Favor with Flash of Light HP", "Set the Divine Favor with Flash of Light HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.HLDFHP", {(1049 - (572 + 477)),(61 + 39),(87 - (84 + 2))}, "Divine Favor HP", "Set the Divine Favor with Holy Light HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.HLBoth", {(0 + 0),(3 + 97),(1334 - (605 + 728))}, "Holy Light /w Both Buffs HP", "Set the Divine Favor with Holy Light with Favor and Infusion HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.FoLBoth", {(0 - 0),(369 - 269),(2 - 1)}, "FoL /w Both Buffs HP", "Set the Divine Favor with Flash of Light with Favor and Infusion HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.HandofDivinityHP", {(489 - (457 + 32)),(1502 - (832 + 570)),(1 + 0)}, "Hand Of Divinity HP", "Set the Hand of Divinity HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.LoHHP", {(0 + 0),(269 - 169),(1 - 0)}, "Lay on Hands HP", "Set the Lay on Hands HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.AwakeningHP", {(653 - (232 + 421)),(25 + 75),(3 - 2)}, "Awakening HP", "Set the Awakening HP threshold.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.AwakeningCount", {(0 - 0),(1458 - (666 + 787)),(1 + 0)}, "Awakening Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v24, "APL.Paladin.HolySpecialHealing.JudgementInAC", {(0 - 0),(306 - 206),(900 - (503 + 396))}, "Judgement In AC Cast", "Set the Judgement In AC threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AWHP", {(0 - 0),(60 + 40),(1 + 0)}, "Avenging Wrath HP", "Set the Avenging Wrath  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AWCount", {(0 + 0),(121 - 81),(1 - 0)}, "Avenging Wrath Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.ACHP", {(0 - 0),(1235 - (832 + 303)),(1 + 0)}, "Avenging Crusader  HP", "Set the Avenging Crusader  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.ACCount", {(0 + 0),(24 - 19),(2 - 1)}, "Avenging Crusder Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AMHP", {(1073 - (1036 + 37)),(194 - 94),(1481 - (641 + 839))}, "Aura Mastery  HP", "Set the Aura Mastery  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.AMCount", {(0 - 0),(19 + 21),(1 + 0)}, "Aura Mastery Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.BoVHP", {(854 - (174 + 680)),(207 - 107),(740 - (396 + 343))}, "Beacon of Virtue  HP", "Set the Beacon of Virtue  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.BoVCount", {(1477 - (29 + 1448)),(18 - 13),(1 + 0)}, "Beacon of Virtue Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.DivineTollHP", {(574 - (102 + 472)),(56 + 44),(1546 - (320 + 1225))}, "Divine Toll  HP", "Set the Divine Toll  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.DivineTollCount", {(0 + 0),(1864 - (821 + 1038)),(1 + 0)}, "Divine Toll Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.LoDHP", {(0 + 0),(1126 - (834 + 192)),(1 + 0)}, "Light of Dawn  HP", "Set the Light of Dawn  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.LoDCount", {(0 - 0),(2 + 3),(363 - (112 + 250))}, "Light of Dawn Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.TyrsHP", {(0 - 0),(52 + 48),(1 + 0)}, "Tyr's Deliverance  HP", "Set the Tyr's Deliverance  HP Threshold.");
v6("Slider", v30, "APL.Paladin.HolyRaidAoE.TyrsCount", {(1414 - (1001 + 413)),(887 - (244 + 638)),(2 - 1)}, "Tyr's Deliverance Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v31, "APL.Paladin.HolyRaidAoE2.HPHP", {(1906 - (1665 + 241)),(46 + 54),(2 - 1)}, "Holy Prism  HP", "Set the Holy Prism  HP Threshold.");
v6("Slider", v31, "APL.Paladin.HolyRaidAoE2.HPCount", {(1099 - (35 + 1064)),(10 - 5),(1237 - (298 + 938))}, "Holy Prism Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.FoLHP", {(1666 - (636 + 1030)),(98 + 2),(1 + 0)}, "Flash of Light HP", "Set the Flash of Light HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.FoLIHP", {(0 + 0),(381 - 281),(1 - 0)}, "Flash of Light With Infusion HP", "Set the Flash of Light With Infusion HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HLHP", {(0 + 0),(1383 - (1035 + 248)),(1 + 0)}, "Holy Light HP", "Set the Holy Light HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HLIHP", {(1133 - (549 + 584)),(343 - 243),(1 + 0)}, "Holy Light with Infusion HP", "Set the Holy Light with Infusion HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HolyShockHP", {(0 - 0),(1440 - (1093 + 247)),(1 + 0)}, "Holy Shock HP", "Set the Holy Shock HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HolyShock2HP", {(0 - 0),(251 - 151),(3 - 2)}, "Holy Shock 2nd Charge HP", "Set the Holy Shock 2nd Charge HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HolyShockRHP", {(0 + 0),(788 - (364 + 324)),(2 - 1)}, "Holy Shock Rising Sun HP", "Set the Holy Shock Rising Sun HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.WoGHP", {(0 - 0),(303 - 203),(1 + 0)}, "Word of Glory/EF HP", "Set the Word of Glory/Eternal Flame  HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.WoGTankHP", {(1086 - (686 + 400)),(329 - (73 + 156)),(812 - (721 + 90))}, "Word of Glory/EF On Tank HP", "Set the Word of Glory/Eternal Flame  On Tank HP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.WoGOverHP", {(0 - 0),(162 - 62),(1 + 0)}, "Word of Glory/EF over LoD HP", "Set the Word of Glory/Eternal Flame  over LoDHP threshold.");
v6("Slider", v29, "APL.Paladin.HolyRaidHealing.HBHP", {(0 + 0),(332 - 232),(1994 - (1238 + 755))}, "Holy Bulward HP", "Set the Holy Bulwark HP threshold.");
v6("CheckButton", v29, "APL.Paladin.HolyRaidHealing.HBTank", "Holy Bulwark Tank Only", "Would you like Rotation to only use Holy Bulwark on Tanks (Unless a unit is very low?");
v6("CheckButton", v32, "APL.Paladin.HolyRaidSpecialHealing.UseBoP", "Use BoP Logic", "Would you like Rotation to Use Special Logic Outside of Health for BoP??");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.BoPHP", {(1534 - (709 + 825)),(145 - 45),(3 - 2)}, "Blessing of Protection HP", "Set theBlessing of Protection HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.BoSHP", {(833 - (171 + 662)),(350 - 250),(4 - 3)}, "Blessing of Sacrfice  HP", "Set the Blessing of Sacrfice HP threshold.");
v6("CheckButton", v32, "APL.Paladin.HolyRaidSpecialHealing.UseBoS", "Use BoS Logic", "Would you like Rotation to Use Special Logic Outside of Health for Sac??");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.FoLDFHP", {(1486 - (35 + 1451)),(2093 - (941 + 1052)),(1515 - (822 + 692))}, "Divine Favor with Flash of Light HP", "Set the Divine Favor with Flash of Light HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.HLDFHP", {(0 + 0),(99 + 1),(2 - 1)}, "Divine Favor HP", "Set the Divine Favor with Holy Light HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.HLBoth", {(0 - 0),(64 + 36),(1 - 0)}, "Holy Light /w Both Buffs HP", "Set the Divine Favor with Holy Light with Favor and Infusion HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.FoLBoth", {(1206 - (741 + 465)),(53 + 47),(2 - 1)}, "FoL /w Both Buffs HP", "Set the Divine Favor with Flash of Light with Favor and Infusion HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.HandofDivinityHP", {(0 + 0),(1330 - (957 + 273)),(1 + 0)}, "Hand Of Divinity HP", "Set the Hand of Divinity HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.LoHHP", {(0 - 0),(495 - 395),(1 + 0)}, "Lay on Hands HP", "Set the Lay on Hands HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.AwakeningHP", {(0 - 0),(335 - 235),(312 - (309 + 2))}, "Awakening HP", "Set the Awakening HP threshold.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.AwakeningCount", {(1212 - (1090 + 122)),(16 - 11),(1119 - (628 + 490))}, "Awakening Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v32, "APL.Paladin.HolyRaidSpecialHealing.JudgementInAC", {(0 - 0),(874 - (431 + 343)),(2 - 1)}, "Judgement In AC Cast", "Set the Judgement In AC threshold.");
v6("CheckButton", v25, "APL.Paladin.HolyTyrs.BeforeTyrs", "Hand of Divinity Before Tyr's", "Attempt to use Hand of Divinity before Tyrs");
v6("Slider", v25, "APL.Paladin.HolyTyrs.TyrFoLHP", {(0 + 0),(115 - (6 + 9)),(1 + 0)}, "Flash of Light with Tyrs HP", "Set the Flash of Light with Tyrs HP threshold.");
v6("Slider", v25, "APL.Paladin.HolyTyrs.TyrHLHP", {(0 + 0),(71 + 29),(2 - 1)}, "Holy Light with Tyrs HP", "Set the Holy Light with Tyrs HP threshold.");
v8(v32, "APL.Paladin.HolyRaidSpecialHealing");
v8(v30, "APL.Paladin.HolyRaidAoE");
v8(v31, "APL.Paladin.HolyRaidAoE2");
v8(v29, "APL.Paladin.HolyRaidHealing");
v8(v26, "APL.Paladin.HolyDaybreak");
v8(v25, "APL.Paladin.HolyTyrs");
v8(v24, "APL.Paladin.HolySpecialHealing");
v8(v22, "APL.Paladin.HolyCooldowns");
v8(v21, "APL.Paladin.HolyBlessings");
v8(v27, "APL.Paladin.HolyAoE");
v8(v28, "APL.Paladin.HolyAoE2");
v8(v23, "APL.Paladin.HolyHealing");
v8(v20, "APL.Paladin.Holy");
v9.APL.Paladin.Holy.Display = function()
	v3.GUI.HidePanel(v26);
	v3.GUI.ShowPanel(v25);
	v3.GUI.ShowPanel(v24);
	v3.GUI.ShowPanel(v22);
	v3.GUI.ShowPanel(v27);
	v3.GUI.ShowPanel(v23);
	v3.GUI.ShowPanel(v20);
	v3.GUI.ShowPanel(v30);
	v3.GUI.ShowPanel(v29);
	v3.GUI.ShowPanel(v32);
	v3.GUI.ShowPanel(v28);
	v3.GUI.ShowPanel(v31);
	v3.GUI.ShowPanel(v21);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v13);
	v3.GUI.HidePanel(v14);
end;
v9.APL.Paladin.Retribution.Display = function()
	v3.GUI.ShowPanel(v18);
	v3.GUI.ShowPanel(v16);
	v3.GUI.ShowPanel(v17);
	v3.GUI.ShowPanel(v19);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v13);
	v3.GUI.HidePanel(v14);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v32);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v31);
	v3.GUI.HidePanel(v21);
end;
v9.APL.Paladin.Protection.Display = function()
	v3.GUI.ShowPanel(v13);
	v3.GUI.ShowPanel(v14);
	v3.GUI.ShowPanel(v15);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v32);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v31);
	v3.GUI.HidePanel(v21);
end;
