local v0, v1 = ...;
local v2 = HeroLib;
local v3 = HeroRotation();
local v4 = v2.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v3.HRGUIGet().CreateARPanelOption;
local v8 = v3.HRGUIGet().CreateARPanelOptions;
local v9 = v3.GUISettingsGet();
v9.APL.Rogue = {Commons={UseSoloVanish=false,Enabled={Potions=true,Trinket1=true,Trinket2=true,Items=true,Shiv=true,Racials=true,IgnoreTtdOnBoss=true},OnlyAttackEnnemyInCombat=true,OnlyAttackEnnemyInCombatSolo=false},Defense={CrimsonVialHP=(93 - 63),EvasionHP=(85 - 55),FeintHP=(57 - 27),FeintDanger=true,CloakofShadowsHP=(77 - 47)},Assassination={EnvenomDMGOffset=(622 - (555 + 64)),MutilateDMGOffset=(934 - (857 + 74)),AlwaysSuggestGarrote=false,UsePriorityRotation="Toggle",PotionType={Selected="Power"},PotionRank={Selected="Any"},TimeToDie={Cooldowns=(583 - (367 + 201))}},Assassination_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=true,AutoTargetStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(987 - (214 + 713)),InterruptPercentChannel=(16 + 44)},UseBlind=true,UseCheapShop=true,UseKidneyShot=true},Outlaw={RolltheBonesLogic="SimC",AutoTabGS=false,PotionType={Selected="Power"},PotionRank={Selected="Any"},TimeToDie={AdrenalineRush=(2 + 8),Stealth=(887 - (282 + 595)),ThistleTea=(1647 - (1523 + 114)),Trinkets=(9 + 1),KillingSpree=(6 - 1)}},Outlaw_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=true,AutoTargetStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(1125 - (68 + 997)),InterruptPercentChannel=(1330 - (226 + 1044))},UseBlind=true,UseCheapShop=true,UseKidneyShot=true},Subtlety={EviscerateDMGOffset=(12 - 9),ShDEcoCharge=(118.75 - (32 + 85)),BurnShadowDance="On Bosses not in Dungeons",UsePriorityRotation="Toggle",PotionType={Selected="Power"},PotionRank={Selected="Any"},StealthMacro={Vanish=true,Shadowmeld=true,ShadowDance=true},TimeToDie={Cooldowns=(15 + 0)}},Subtlety_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=true,AutoTargetStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(14 + 46),InterruptPercentChannel=(1017 - (892 + 65))},UseBlind=true,UseCheapShop=true,UseKidneyShot=true}};
v9.APL.Rogue.Commons.Enabled["Shiv Auto Target"] = true;
v9.APL.Rogue.Commons.Enabled["Tricks of Trade Focus"] = true;
v3.HRGUIGet().LoadSettingsRecursively(v9);
local v13 = v3.HRGUIGet().Panel;
local v14 = v5(v13, "Rogue");
local v15 = v5(v13, "Defense");
local v16 = v5(v13, "Assassination");
local v17 = v5(v13, "Outlaw");
local v18 = v5(v13, "Subtlety");
local v19 = v5(v17, "Interrupt");
v8(v19, "APL.Rogue.Outlaw_Interrupt");
v6("CheckButton", v19, "APL.Rogue.Outlaw_Interrupt.UseBlind", "Use Blind", "Use Blind for stun and or interrupt.");
v6("CheckButton", v19, "APL.Rogue.Outlaw_Interrupt.UseCheapShop", "Use Cheap Shot", "Use Cheap Shot for stun and or interrupt.");
v6("CheckButton", v19, "APL.Rogue.Outlaw_Interrupt.UseKidneyShot", "Use Kidney Shot", "Use Kidney Shot for stun and or interrupt.");
local v20 = v5(v16, "Interrupt");
v8(v20, "APL.Rogue.Assassination_Interrupt");
v6("CheckButton", v20, "APL.Rogue.Assassination_Interrupt.UseBlind", "Use Blind", "Use Blind for stun and or interrupt.");
v6("CheckButton", v20, "APL.Rogue.Assassination_Interrupt.UseCheapShop", "Use Cheap Shot", "Use Cheap Shot for stun and or interrupt.");
v6("CheckButton", v20, "APL.Rogue.Assassination_Interrupt.UseKidneyShot", "Use Kidney Shot", "Use Kidney Shot for stun and or interrupt.");
local v21 = v5(v18, "Interrupt");
v8(v21, "APL.Rogue.Subtlety_Interrupt");
v6("CheckButton", v21, "APL.Rogue.Subtlety_Interrupt.UseBlind", "Use Blind", "Use Blind for stun and or interrupt.");
v6("CheckButton", v21, "APL.Rogue.Subtlety_Interrupt.UseCheapShop", "Use Cheap Shot", "Use Cheap Shot for stun and or interrupt.");
v6("CheckButton", v21, "APL.Rogue.Subtlety_Interrupt.UseKidneyShot", "Use Kidney Shot", "Use Kidney Shot for stun and or interrupt.");
v6("CheckButton", v14, "APL.Rogue.Commons.UseSoloVanish", "Use Vanish while Solo", "Suggest Vanish while Solo.\nDisable to save prevent mobs resetting.");
v6("CheckButton", v14, "APL.Rogue.Commons.OnlyAttackEnnemyInCombat", "Only attack in combat", "Only attack enemy in combat.");
v6("CheckButton", v14, "APL.Rogue.Commons.OnlyAttackEnnemyInCombatSolo", "Only attack in combat Solo", "Only attack enemy in combat when solo.");
v8(v14, "APL.Rogue.Commons");
v6("Slider", v15, "APL.Rogue.Defense.CrimsonVialHP", {(0 - 0),(450 - (87 + 263)),(1 + 0)}, "Crimson Vial HP", "Set the Crimson Vial HP threshold.");
v6("Slider", v15, "APL.Rogue.Defense.EvasionHP", {(0 + 0),(1052 - (802 + 150)),(1 - 0)}, "Evasion HP", "Set the Evasion HP threshold.");
v6("Slider", v15, "APL.Rogue.Defense.FeintHP", {(997 - (915 + 82)),(59 + 41),(1188 - (1069 + 118))}, "Feint HP", "Set the Feint HP threshold.");
v6("CheckButton", v15, "APL.Rogue.Defense.FeintDanger", "Use Feint on danger", "Use feint on dangerous spell.");
v6("Slider", v15, "APL.Rogue.Defense.CloakofShadowsHP", {(0 - 0),(177 - 77),(792 - (368 + 423))}, "Cloak of Shadows HP", "Set the Cloak of Shadows HP threshold.");
v8(v15, "APL.Rogue.Defense");
v6("Slider", v16, "APL.Rogue.Assassination.EnvenomDMGOffset", {(19 - (10 + 8)),(447 - (416 + 26)),(0.25 + 0)}, "Envenom DMG Offset", "Set the Envenom DMG Offset.");
v6("Slider", v16, "APL.Rogue.Assassination.MutilateDMGOffset", {(439 - (145 + 293)),(1491 - (998 + 488)),(0.25 + 0)}, "Mutilate DMG Offset", "Set the Mutilate DMG Offset.");
v6("Dropdown", v16, "APL.Rogue.Assassination.UsePriorityRotation", {"Toggle","On Bosses"}, "Use Priority Rotation", "Select when to show rotation for maximum priority damage (at the cost of overall AoE damage.)\nAuto will function as Never except on specific encounters where AoE is not recommended.");
v6("CheckButton", v16, "APL.Rogue.Assassination.AlwaysSuggestGarrote", "Always Suggest Garrote", "Don't prevent Garrote suggestions when using Subterfuge and Vanish is ready. These should ideally be synced, but can be useful if holding Vanish for specific fights.");
v8(v16, "APL.Rogue.Assassination");
v6("Dropdown", v17, "APL.Rogue.Outlaw.RolltheBonesLogic", {"SimC","1+ Buff","Broadside","Buried Treasure","Grand Melee","Skull and Crossbones","Ruthless Precision","True Bearing"}, "Roll the Bones Logic", "Define the Roll the Bones logic to follow.\n(SimC highly recommended!)");
v6("CheckButton", v17, "APL.Rogue.Outlaw.AutoTabGS", "Auto Target GS", "Auto Target Ghost Strike target.");
v8(v17, "APL.Rogue.Outlaw");
v6("Slider", v18, "APL.Rogue.Subtlety.EviscerateDMGOffset", {(1 - 0),(1428 - (630 + 793)),(0.25 - 0)}, "Eviscerate Damage Offset", "Set the Eviscerate Damage Offset, used to compute the rupture threshold.");
v6("Slider", v18, "APL.Rogue.Subtlety.ShDEcoCharge", {(3 - 2),(1915 - (1789 + 124)),(0.1 + 0)}, "ShD Eco Charge", "Set the Shadow Dance Eco Charge threshold.");
v6("Dropdown", v18, "APL.Rogue.Subtlety.UsePriorityRotation", {"Toggle","On Bosses"}, "Use Priority Rotation", "Select when to show rotation for maximum priority damage (at the cost of overall AoE damage.)\nAuto will function as Never except on specific encounters where AoE is not recommended.");
v6("Dropdown", v18, "APL.Rogue.Subtlety.BurnShadowDance", {"Always","On Bosses","On Bosses not in Dungeons"}, "Burn Shadow Dance before Death", "Use remaining Shadow Dance charges when the target is about to die.");
v6("CheckButton", v18, "APL.Rogue.Subtlety.StealthMacro.Vanish", "Stealth Combo - Vanish", "Allow suggesting Vanish stealth ability combos (recommended)");
v6("CheckButton", v18, "APL.Rogue.Subtlety.StealthMacro.Shadowmeld", "Stealth Combo - Shadowmeld", "Allow suggesting Shadowmeld stealth ability combos (recommended)");
v6("CheckButton", v18, "APL.Rogue.Subtlety.StealthMacro.ShadowDance", "Stealth Combo - Shadow Dance", "Allow suggesting Shadow Dance stealth ability combos (recommended)");
v8(v18, "APL.Rogue.Subtlety");
local v22 = v4.GetPanelByName("Interrupt");
v9.APL.Rogue.AddCommonToggle = function()
	v3.ResetToggle();
	v3.ToggleIconFrame:AddButtonCustom("S", 4 - 3, "Stealth", "stealth");
	v3.ToggleIconFrame:AddButtonCustom("I", 3 + 0, "Interrupt", "interrupt");
end;
v9.APL.Rogue.Outlaw.Display = function()
	v9.APL.Rogue.AddCommonToggle();
	v3.ToggleIconFrame:AddButtonCustom("P", 4 - 2, "Precast", "precast");
	v2.GUI.HidePanel(v18);
	v2.GUI.HidePanel(v16);
	v2.GUI.ShowPanel(v17);
	v2.GUI.ShowPanel(v19);
	v2.GUI.HidePanel(v20);
	v2.GUI.HidePanel(v21);
	v2.GUI.HidePanel(v22);
end;
v9.APL.Rogue.Assassination.Display = function()
	v9.APL.Rogue.AddCommonToggle();
	v3.ToggleIconFrame:AddButtonCustom("P", 1415 - (447 + 966), "Priority", "priority");
	v3.ToggleIconFrame:AddButtonCustom("S", 10 - 6, "Small CDs", "smallcds");
	v2.GUI.HidePanel(v18);
	v2.GUI.ShowPanel(v16);
	v2.GUI.HidePanel(v17);
	v2.GUI.HidePanel(v19);
	v2.GUI.ShowPanel(v20);
	v2.GUI.HidePanel(v21);
	v2.GUI.HidePanel(v22);
end;
v9.APL.Rogue.Subtlety.Display = function()
	v9.APL.Rogue.AddCommonToggle();
	v3.ToggleIconFrame:AddButtonCustom("P", 1819 - (1703 + 114), "Priority", "priority");
	v3.ToggleIconFrame:AddButtonCustom("S", 705 - (376 + 325), "Small CDs", "smallcds");
	v2.GUI.ShowPanel(v18);
	v2.GUI.HidePanel(v16);
	v2.GUI.HidePanel(v17);
	v2.GUI.HidePanel(v19);
	v2.GUI.HidePanel(v20);
	v2.GUI.ShowPanel(v21);
	v2.GUI.HidePanel(v22);
end;
