local v0, v1 = ...;
local v2 = HeroRotation();
local v3 = HeroLib;
local v4 = v3.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v2.HRGUIGet().CreateARPanelOption;
local v8 = v2.HRGUIGet().CreateARPanelOptions;
local v9 = v2.GUISettingsGet();
v9.APL.Mage = {Commons={ForceAOE=false,UseTemporalWarp=true,Enabled={Potions=true,Trinkets=true,Items=true},OnlyAttackEnnemyInCombat=true,OnlyAttackEnnemyInCombatSolo=true,GroundSpellOnlyIfMouseover=true,GroundSpellOnlyIfCameraFree=true,TimeToTimeCastTime=true,AutoBuff=true,AutoTargetSpellSteal=true,DisplayStyle={Potions="Suggested",Trinkets="Suggested",Items="Suggested",Signature="Suggested"}},Defense={Defensive={IceCold=(62 - 42),Barrier=(85 - 55),MassBarrier=(57 - 27),MirrorImage=(206 - 126)}},Frost={PotionType={Selected="Tempered Potion"},TimeToDie={FrozenOrb=(629 - (555 + 64)),IcyVeins=(946 - (857 + 74)),CometStorm=(578 - (367 + 201)),TimeWrap=(937 - (214 + 713)),Trinkets=(3 + 7)}},Frost_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=true,AutoTargetStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(10 + 50),InterruptPercentChannel=(937 - (282 + 595))}},Fire={DisableCombustion=false,MirrorImagesBeforePull=false,UseScorchSniping=false,PotionType={Selected="Tempered Potion"},TimeToDie={Combustion=(1651 - (1523 + 114)),SKB=(8 + 0),TimeWrap=(14 - 4),Trinkets=(1075 - (68 + 997))}},Fire_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=true,AutoTargetStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(1330 - (226 + 1044)),InterruptPercentChannel=(261 - 201)}},Arcane={MirrorImagesBeforePull=true,PotionType={Selected="Tempered Potion"},Enabled={ManaGem=true},TimeToDie={TouchoftheMagi=(132 - (32 + 85)),ArcaneSurge=(20 + 0),PresenceOfMind=(3 + 9),TimeWrap=(967 - (892 + 65)),Trinkets=(35 - 20)}},Arcane_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=true,AutoTargetStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(110 - 50),InterruptPercentChannel=(110 - 50)}}};
v2.HRGUIGet().LoadSettingsRecursively(v9);
local v11 = v2.HRGUIGet().Panel;
local v12 = v5(v11, "Mage");
local v13 = v5(v11, "Arcane");
local v14 = v5(v13, "Interrupt");
v8(v14, "APL.Mage.Arcane_Interrupt");
local v15 = v5(v11, "Fire");
local v16 = v5(v15, "Interrupt");
v8(v16, "APL.Mage.Fire_Interrupt");
local v17 = v5(v11, "Frost");
local v18 = v5(v17, "Interrupt");
v8(v18, "APL.Mage.Frost_Interrupt");
local v19 = v5(v11, "Defense");
v8(v19, "APL.Mage.Defense");
v8(v12, "APL.Mage.Commons");
v6("CheckButton", v12, "APL.Mage.Commons.ForceAOE", "AoE toggle forced", "The AoE toggle is now forcing aoe to be used and ignore the target count.");
v6("CheckButton", v12, "APL.Mage.Commons.UseTemporalWarp", "Suggest Time Warp with Temporal Warp", "Show Time Warp when the Temporal Warp talent is selected.");
v6("CheckButton", v12, "APL.Mage.Commons.OnlyAttackEnnemyInCombat", "Only attack in combat", "Only attack enemy in combat.");
v6("CheckButton", v12, "APL.Mage.Commons.OnlyAttackEnnemyInCombatSolo", "Only attack in combat Solo", "Only attack enemy in combat when solo.");
v6("CheckButton", v12, "APL.Mage.Commons.GroundSpellOnlyIfMouseover", "Only use Ground Spells if Mouseover ", "Only use ground spell if the mouse is over a target.");
v6("CheckButton", v12, "APL.Mage.Commons.GroundSpellOnlyIfCameraFree", "Only use Ground Spells if Camera is not busy ", "Only use Ground Spells if Camera is not busy.");
v6("CheckButton", v12, "APL.Mage.Commons.TimeToTimeCastTime", "Time to die check for cast time ", "Time to die check for cast time,p avoid wasting long cast on dead mobs.");
v6("CheckButton", v12, "APL.Mage.Commons.AutoBuff", "Auto Buff Intellect", "Auto Buff Intellect");
v6("CheckButton", v12, "APL.Mage.Commons.AutoTargetSpellSteal", "Auto Buff Spell Steal", "Auto Target for Spell Steal");
v6("CheckButton", v13, "APL.Mage.Arcane.MirrorImagesBeforePull", "Use Mirror Images Precombat", "Enable this option to show Mirror Images during Precombat.");
v8(v13, "APL.Mage.Arcane");
v8(v15, "APL.Mage.Fire");
v6("CheckButton", v15, "APL.Mage.Fire.MirrorImagesBeforePull", "Use Mirror Image before combat", "Enable the use of Mirror image before starting combat.");
v6("CheckButton", v15, "APL.Mage.Fire.UseScorchSniping", "Enable Auto Scorch sniping", "Enable this option to enable Scorch when Searing Touch is talented and one of your non-primary targets is under 30% health.");
v8(v17, "APL.Mage.Frost");
v9.APL.Mage.AddCommonToggle = function()
	v2.ResetToggle();
	v2.ToggleIconFrame:AddButtonCustom("P", 351 - (87 + 263), "Precast", "precast");
	v2.ToggleIconFrame:AddButtonCustom("I", 183 - (67 + 113), "Interrupt", "interrupt");
	v2.ToggleIconFrame:AddButtonCustom("D", 3 + 1, "Dispel", "dispel");
end;
local v21 = v4.GetPanelByName("Interrupt");
v9.APL.Mage.Frost.Display = function()
	v9.APL.Mage.AddCommonToggle();
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v13);
	v3.GUI.ShowPanel(v17);
	v3.GUI.ShowPanel(v18);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v14);
	v3.GUI.HidePanel(v21);
end;
v9.APL.Mage.Fire.Display = function()
	v9.APL.Mage.AddCommonToggle();
	v2.ToggleIconFrame:AddButtonCustom("S", 4 - 2, "Skb", "skb");
	v3.GUI.HidePanel(v13);
	v3.GUI.ShowPanel(v15);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v18);
	v3.GUI.ShowPanel(v16);
	v3.GUI.HidePanel(v14);
	v3.GUI.HidePanel(v21);
end;
v9.APL.Mage.Arcane.Display = function()
	v9.APL.Mage.AddCommonToggle();
	v2.ToggleIconFrame:AddButtonCustom("S", 2 + 0, "ShiftingPower", "shiftingpower");
	v3.GUI.ShowPanel(v13);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v16);
	v3.GUI.ShowPanel(v14);
	v3.GUI.HidePanel(v21);
end;
