local v0, v1 = ...;
local v2 = HeroRotation();
local v3 = HeroLib;
local v4 = v3.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v2.HRGUIGet().CreateARPanelOption;
local v8 = v2.HRGUIGet().CreateARPanelOptions;
local v9 = v4.GetPanelByName("Interrupt");
local v10 = v2.GUISettingsGet();
v10.APL.Druid = {Commons={Enabled={Potions=true,Trinkets=true,Items=true},MarkoftheWild="only check us",DisplayStyle={Potions="Suggested",Trinkets="Suggested",Signature="Suggested",Items="Suggested"}},Balance={ShowMoonkinFormOOC=false,DelayBerserking=false,AttackonlyinCombat=true,CursorCheck=true,TabForSoothe=false,SpamDot=true,PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},Defensives={BarkskinHP=(156 - 106),RenewalHP=(114 - 74),RegrowthHP=(19 - 9),RegrowthBloomingHP=(154 - 94),SwiftmendHP=(619 - (555 + 64)),SurvivalInstinctsHP=(931 - (857 + 74)),FrenziedRegenerationHP=(568 - (367 + 201)),IronfurHP=(927 - (214 + 713)),BearFormHP=(0 + 0),MoonkinFormHP=(0 + 0),NaturesVigilHP=(937 - (282 + 595)),NaturesVigilCount=(1640 - (1523 + 114))}},Balance_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=false,AutoTargetStun=false,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(54 + 6),InterruptPercentChannel=(85 - 25)}},Balance_CDUSE={smallcdswithCooldowns=true,Enemycount=(1070 - (68 + 997)),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",Incarnation="with Cooldowns",WarriorofElune="with Cooldowns",ForceofNature="with Cooldowns",WildMushroom="with Cooldowns",FuryofElune="with Cooldowns",ConvoketheSpirits="with Cooldowns"},Balance_TTD={RacialsTTD=(1290 - (226 + 1044)),TrinketsTTD=(87 - 67),IncarnationTTD=(147 - (32 + 85)),WarriorofEluneTTD=(10 + 0),ForceofNatureTTD=(4 + 11),WildMushroomTTD=(972 - (892 + 65)),FuryofEluneTTD=(23 - 13),ConvoketheSpiritsTTD=(18 - 8),PotionsTTD=(36 - 16),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Feral={ShowCatFormOOC=false,AttackonlyinCombat=false,AutoTabDot=false,TabForSoothe=false,PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},Defensives={BarkskinHP=(400 - (87 + 263)),RenewalHP=(220 - (67 + 113)),RegrowthHP=(44 + 16),NaturesVigilHP=(147 - 87),NaturesVigilCount=(3 + 0),SwiftmendHP=(0 - 0),SurvivalInstinctsHP=(952 - (802 + 150)),FrenziedRegenerationHP=(0 - 0),IronfurHP=(0 - 0),BearFormHP=(0 + 0),CatFormHP=(997 - (915 + 82))}},Feral_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=false,AutoTargetStun=false,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(169 - 109),InterruptPercentChannel=(35 + 25)}},Feral_CDUSE={smallcdswithCooldowns=true,Enemycount=(6 - 1),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",Incarnation="with Cooldowns",FeralFrenzy="with Cooldowns",AdaptiveSwarm="with Cooldowns",ConvoketheSpirits="with Cooldowns",TigersFury="always",Djaruun="with Cooldowns"},Feral_TTD={RacialsTTD=(1207 - (1069 + 118)),TrinketsTTD=(45 - 25),FeralFrenzyTTD=(21 - 11),IncarnationTTD=(6 + 24),ConvoketheSpiritsTTD=(17 - 7),TigersFuryTTD=(10 + 0),PotionsTTD=(811 - (368 + 423)),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Guardian={UseIronfurOffensively=true,UseRageDefensively=true,AttackonlyinCombat=false,AutoTabDot=false,TabForSoothe=false,Defensives={RegrowthHP=(188 - 128),RenewalHP=(78 - (10 + 8)),BarkskinHP=(192 - 142),FrenziedRegenHP=(512 - (416 + 26)),SurvivalInstinctsHP=(95 - 65),BristlingFurRage=(22 + 28),NaturesVigilHP=(106 - 46),NaturesVigilCount=(441 - (145 + 293))},PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},DisplayStyle={Defensives="Suggested"}},Guardian_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=false,AutoTargetStun=false,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(490 - (44 + 386)),InterruptPercentChannel=(1546 - (998 + 488))}},Guardian_CDUSE={smallcdswithCooldowns=true,Enemycount=(2 + 3),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",Incarnation="with Cooldowns",RageoftheSleeper="with Cooldowns",LunarBeam="with Cooldowns",ConvoketheSpirits="with Cooldowns",Djaruun="with Cooldowns"},Guardian_TTD={RacialsTTD=(17 + 3),TrinketsTTD=(792 - (201 + 571)),RageoftheSleeperTTD=(1148 - (116 + 1022)),IncarnationTTD=(124 - 94),ConvoketheSpiritsTTD=(6 + 4),LunarBeamTTD=(36 - 26),PotionsTTD=(71 - 51),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Restoration={EfflorUsage=false,InnervateMP=(944 - (814 + 45)),InnervateTree=true,DPSForm="Cat",TabForSoothe=false,ConvokeDPS=false,PredictLogic=true,MoonfireMouseover=false,AttackOOC=false,PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},GCDasOffGCD={HeartOfTheWild=true},OffGCDasOffGCD={},Soul={WildGrowthSoulHP=(221 - 131),RejSoulHP=(2 + 23),RegrowthSoulHP=(13 + 22),WildGrowthSoulCount=(888 - (261 + 624))},Lifebloom={LifeBloomOnBothTanks=true,LifeBloomTarget="Tank",LifebloomRefreshIgnore=(79 - 34)},Cooldowns={HeartOfTheWildUse="With Logic",AdaptiveSwarmUse="With Logic",AdaptiveSwarmHP=(1180 - (1020 + 60)),ConvokeUse="With Logic",NaturesVigilUse="With Logic",NVSpread=true,Trinket1Use="With Logic",Trinket2Use="With Logic",Trinket1HP=(1488 - (630 + 793)),Trinket2HP=(220 - 155)},AoEHealing={ConvokeHP=(355 - 280),FlourishHP=(18 + 27),TranquilityHP=(103 - 73),TreeofLife=(1812 - (760 + 987)),WildGrowthHP=(1998 - (1789 + 124)),WGSpread=true,ConvokeCount=(769 - (745 + 21)),FlourishCount=(2 + 1),TranquilityCount=(7 - 4),TreeofLifeCount=(7 - 5),WildGrowthCount=(1 + 2)},Healing={GerminationHoTHP=(48 + 12),GroveGuardiansHP=(1140 - (87 + 968)),InvigorateHP=(308 - 238),IronbarkHP=(19 + 1),NaturesSwiftnessHP=(101 - 56),Nourish=(1468 - (447 + 966)),OvergrowthHP=(164 - 104),RegrowthHP=(1877 - (1703 + 114)),RegrowthClearHP=(781 - (376 + 325)),RejuvenationHP=(147 - 57),SwiftmendHP=(215 - 145)},RaidAoEHealing={ConvokeHP=(22 + 53),FlourishHP=(98 - 53),TranquilityHP=(44 - (9 + 5)),TreeofLife=(441 - (85 + 291)),WildGrowthHP=(1350 - (243 + 1022)),WGSpread=true,ConvokeCount=(11 - 8),FlourishCount=(3 + 0),TranquilityCount=(1183 - (1123 + 57)),TreeofLifeCount=(2 + 0),WildGrowthCount=(257 - (163 + 91))},RaidHealing={GerminationHoTHP=(1990 - (1869 + 61)),GroveGuardiansHP=(24 + 61),InvigorateHP=(246 - 176),IronbarkHP=(30 - 10),NaturesSwiftnessHP=(7 + 38),Nourish=(75 - 20),OvergrowthHP=(57 + 3),RegrowthHP=(1534 - (1329 + 145)),RegrowthClearHP=(1051 - (140 + 831)),RejuvenationHP=(1940 - (1409 + 441)),SwiftmendHP=(788 - (15 + 703))},TankHealing={CenWardHP=(47 + 53),InvigorateTankHP=(483 - (262 + 176)),InvigorateOnTankOnly=true,IronbarkTankHP=(1761 - (345 + 1376)),IronbarkOnTankOnly=false,RegrowthTankHP=(758 - (198 + 490)),RejTankHP=(419 - 324),SwiftTankHP=(203 - 118)},Defensives={RenewalHP=(1266 - (696 + 510)),BarkskinHP=(104 - 54),FrenziedRegenerationHP=(1332 - (1091 + 171)),BearFormHP=(0 + 0),IronfurHP=(236 - 161)}},Restoration_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,AutoTargetInterrupt=false,AutoTargetStun=false,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(198 - 138),InterruptPercentChannel=(434 - (123 + 251))}}};
v2.HRGUIGet().LoadSettingsRecursively(v10);
local v12 = v2.HRGUIGet().Panel;
local v13 = v5(v12, "Druid");
local v14 = v5(v13, "Balance");
local v15 = v5(v14, "Defensives");
local v16 = v5(v14, "Interrupt");
v8(v16, "APL.Druid.Balance_Interrupt");
local v17 = v5(v14, "TTD");
local v18 = v5(v14, "Cooldown settings");
local v19 = v5(v13, "Feral");
local v20 = v5(v19, "Defensives");
local v21 = v5(v19, "Interrupt");
v8(v21, "APL.Druid.Feral_Interrupt");
local v22 = v5(v19, "TTD");
local v23 = v5(v19, "Cooldown settings");
local v24 = v5(v13, "Guardian");
local v25 = v5(v24, "Defensives");
local v26 = v5(v24, "Interrupt");
v8(v26, "APL.Druid.Guardian_Interrupt");
local v27 = v5(v24, "TTD");
local v28 = v5(v24, "Cooldown settings");
local v29 = v5(v13, "Restoration");
local v30 = v5(v29, "Interrupt");
v8(v30, "APL.Druid.Restoration_Interrupt");
local v31 = v5(v29, "Cooldowns");
local v32 = v5(v29, "Defensives");
local v33 = v5(v29, "AoE Healing");
local v34 = v5(v29, "Healing");
local v35 = v5(v29, "Raid AoE Healing");
local v36 = v5(v29, "Raid Healing");
local v37 = v5(v29, "Tank Healing");
local v38 = v5(v29, "Lifebloom");
local v39 = v5(v29, "Soul of the Forest");
local v40 = {"With Cooldowns","With Logic","With Cooldowns and Logic","Not Used"};
local v41 = {"Not Used","always","with Cooldowns","small CDs","with Cooldowns or AoE","on Enemycount or Cooldowns","on Boss or with Cooldowns","on Boss only","with Bloodlust only","on AOE","on Enemycount","on Boss or on Enemycount"};
v8(v13, "APL.Druid.Commons");
v6("Dropdown", v13, "APL.Druid.Commons.MarkoftheWild", {"dont use","only check us","check whole group"}, "Mark of the Wild", "Decide if we want to use Mark of the Wild and who to check for the Buff.");
v6("CheckButton", v14, "APL.Druid.Balance.ShowMoonkinFormOOC", "Show Moonkin Form Out of Combat", "Enable this if you want the addon to show you the Moonkin Form reminder out of combat.");
v6("CheckButton", v14, "APL.Druid.Balance.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v6("CheckButton", v14, "APL.Druid.Balance.CursorCheck", "Cursor Check", "Will check if an Enemy is at the cursor Place currently before fireing Placeable Spells.");
v6("CheckButton", v14, "APL.Druid.Balance.TabForSoothe", "Soothe Auto Tab", "Enable this if you want the addon to auto tab for Soothe");
v6("CheckButton", v14, "APL.Druid.Balance.SpamDot", "Spam Dot while moving", "Enable this if you want the addon to spam dots while moving before pooling");
v8(v14, "APL.Druid.Balance");
v6("Slider", v15, "APL.Druid.Balance.Defensives.RenewalHP", {(0 - 0),(144 - 44),(2 - 1)}, "Renewal HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Renewal. (Set to 0 to disable)");
v6("Slider", v15, "APL.Druid.Balance.Defensives.BarkskinHP", {(1665 - (970 + 695)),(2090 - (582 + 1408)),(1 - 0)}, "Barkskin HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Barkskin. (Set to 0 to disable)");
v6("Slider", v15, "APL.Druid.Balance.Defensives.RegrowthHP", {(1824 - (1195 + 629)),(341 - (187 + 54)),(1 + 0)}, "Regrowth HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Regrowth. (Set to 0 to disable)");
v6("Slider", v15, "APL.Druid.Balance.Defensives.RegrowthBloomingHP", {(0 - 0),(8 + 92),(1001 - (451 + 549))}, "Regrowth with Blooming Infusion HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Regrowth with Blooming Infusion procc. (Set to 0 to disable)");
v6("Slider", v15, "APL.Druid.Balance.Defensives.NaturesVigilHP", {(0 - 0),(1484 - (746 + 638)),(1 - 0)}, "Natures Vigil HP", "Set the HP threshold of when you want the addon to suggest defensive usgae of Natures Vigil. (Set to 0 to disable)");
v6("Slider", v15, "APL.Druid.Balance.Defensives.NaturesVigilCount", {(1581 - (1535 + 46)),(1 + 4),(1 + 0)}, "Natures Vigil Count", "Set the Unit Count threshold to Cast Natures Vigil.");
v6("Slider", v15, "APL.Druid.Balance.Defensives.SwiftmendHP", {(1467 - (899 + 568)),(241 - 141),(291 - (60 + 230))}, "Swiftmend HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Swiftmend. (Set to 0 to disable)");
v6("Slider", v15, "APL.Druid.Balance.Defensives.SurvivalInstinctsHP", {(0 + 0),(911 - (569 + 242)),(1 + 0)}, "Survival Instincts HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Survival Instincts. (Set to 0 to disable)");
v6("Slider", v15, "APL.Druid.Balance.Defensives.FrenziedRegenerationHP", {(1251 - (721 + 530)),(249 - 149),(701 - (271 + 429))}, "Frenzied Regeneration HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of FrenziedRegeneration. (Set to 0 to disable)");
v6("Slider", v15, "APL.Druid.Balance.Defensives.IronfurHP", {(1500 - (1408 + 92)),(1388 - (993 + 295)),(1172 - (418 + 753))}, "Ironfur HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Ironfur. (Set to 0 to disable)");
v6("Slider", v15, "APL.Druid.Balance.Defensives.BearFormHP", {(0 + 0),(26 + 74),(1770 - (1749 + 20))}, "Bear Form HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Bear Form. (Set to 0 to disable)");
v6("Slider", v15, "APL.Druid.Balance.Defensives.MoonkinFormHP", {(1322 - (1249 + 73)),(1245 - (466 + 679)),(2 - 1)}, "Moonkin Form HP", "Set the HP percentage threshold of when you want the addon to get back into Moonkin Form. (Set to 0 to disable)");
v8(v15, "APL.Druid.Balance.Defensives");
v6("CheckButton", v17, "APL.Druid.Balance_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v17, "APL.Druid.Balance_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v17, "APL.Druid.Balance_TTD.RacialsTTD", {(0 + 0),(177 - 117),(115 - (4 + 110))}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v17, "APL.Druid.Balance_TTD.TrinketsTTD", {(1427 - (41 + 1386)),(41 + 19),(2 - 1)}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v17, "APL.Druid.Balance_TTD.IncarnationTTD", {(0 - 0),(49 + 11),(1 - 0)}, "Incarnation/Celestial Alignment", "Time to die to use Incarnation/Celestial Alignment");
v6("Slider", v17, "APL.Druid.Balance_TTD.ConvoketheSpiritsTTD", {(0 + 0),(226 - 166),(2 - 1)}, "Convoke the Spirits TTD", "Time to die to use Convoke the Spirits");
v6("Slider", v17, "APL.Druid.Balance_TTD.WarriorofEluneTTD", {(320 - (53 + 267)),(473 - (15 + 398)),(3 - 2)}, "Warrior of Elune TTD", "Time to die to use Warrior of Elune");
v6("Slider", v17, "APL.Druid.Balance_TTD.ForceofNatureTTD", {(0 + 0),(47 + 13),(1 + 0)}, "Force of Nature TTD", "Time to die to use Force of Nature");
v6("Slider", v17, "APL.Druid.Balance_TTD.WildMushroomTTD", {(0 - 0),(31 + 29),(2 - 1)}, "Wild Mushroom TTD", "Time to die to use Wild Mushroom");
v6("Slider", v17, "APL.Druid.Balance_TTD.FuryofEluneTTD", {(1551 - (1126 + 425)),(235 - 175),(2 - 1)}, "Fury of Elune TTD", "Time to die to use Fury of Elune");
v6("Slider", v17, "APL.Druid.Balance_TTD.PotionsTTD", {(0 - 0),(1037 - (553 + 424)),(1 + 0)}, "Potions TTD", "Time to die to use DPS Potions");
v8(v17, "APL.Druid.Balance_TTD");
v6("CheckButton", v18, "APL.Druid.Balance_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v18, "APL.Druid.Balance_CDUSE.Enemycount", {(2 + 0),(6 + 4),(2 - 1)}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v18, "APL.Druid.Balance_CDUSE.Racials", v41, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v18, "APL.Druid.Balance_CDUSE.Potions", v41, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v18, "APL.Druid.Balance_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v18, "APL.Druid.Balance_CDUSE.Trinket1", v41, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v18, "APL.Druid.Balance_CDUSE.Trinket2", v41, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v18, "APL.Druid.Balance_CDUSE.Incarnation", v41, "Incarnation/Celestial Alignment", "Choose an option on when to use Incarnation/Celestial Alignment");
v6("Dropdown", v18, "APL.Druid.Balance_CDUSE.WarriorofElune", v41, "Warrior of Elune", "Choose an option on when to use Warrior of Elune");
v6("Dropdown", v18, "APL.Druid.Balance_CDUSE.ForceofNature", v41, "Force of Nature", "Choose an option on when to use Force of Nature");
v6("Dropdown", v18, "APL.Druid.Balance_CDUSE.WildMushroom", v41, "Wild Mushroom", "Choose an option on when to use Wild Mushroom");
v6("Dropdown", v18, "APL.Druid.Balance_CDUSE.FuryofElune", v41, "Fury of Elune", "Choose an option on when to use Fury of Elune");
v6("Dropdown", v18, "APL.Druid.Balance_CDUSE.ConvoketheSpirits", v41, "Convoke the Spirits", "Choose an option on when to use Convoke the Spirits");
v8(v18, "APL.Druid.Balance_CDUSE");
v6("CheckButton", v19, "APL.Druid.Feral.ShowCatFormOOC", "Show Cat Form Out of Combat", "Enable this if you want the addon to show you the Cat Form reminder out of combat.");
v6("CheckButton", v19, "APL.Druid.Feral.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v6("CheckButton", v19, "APL.Druid.Feral.AutoTabDot", "Auto Tab for Multibleeding", "Enable this if you want the addon to auto Tab for Multibleeding.");
v6("CheckButton", v19, "APL.Druid.Feral.TabForSoothe", "Soothe Auto Tab", "Enable this if you want the addon to auto tab for Soothe");
v8(v19, "APL.Druid.Feral");
v6("Slider", v20, "APL.Druid.Feral.Defensives.RenewalHP", {(0 + 0),(853 - (239 + 514)),(1330 - (797 + 532))}, "Renewal HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Renewal. (Set to 0 to disable)");
v6("Slider", v20, "APL.Druid.Feral.Defensives.BarkskinHP", {(0 + 0),(1302 - (373 + 829)),(1131 - (369 + 761))}, "Barkskin HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Barkskin. (Set to 0 to disable)");
v6("Slider", v20, "APL.Druid.Feral.Defensives.RegrowthHP", {(0 - 0),(338 - (64 + 174)),(1 - 0)}, "Regrowth HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Regrowth. (Set to 0 to disable)");
v6("Slider", v20, "APL.Druid.Feral.Defensives.NaturesVigilHP", {(216 - (42 + 174)),(83 + 17),(1505 - (363 + 1141))}, "Natures Vigil HP", "Set the HP threshold of when you want the addon to suggest defensive usgae of Natures Vigil. (Set to 0 to disable)");
v6("Slider", v20, "APL.Druid.Feral.Defensives.NaturesVigilCount", {(0 - 0),(4 + 1),(1 + 0)}, "Natures Vigil Count", "Set the Unit Count threshold to Cast Natures Vigil.");
v6("Slider", v20, "APL.Druid.Feral.Defensives.SwiftmendHP", {(1933 - (565 + 1368)),(1761 - (1477 + 184)),(1 + 0)}, "Swiftmend HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Swiftmend. (Set to 0 to disable)");
v6("Slider", v20, "APL.Druid.Feral.Defensives.SurvivalInstinctsHP", {(0 - 0),(404 - (244 + 60)),(477 - (41 + 435))}, "Survival Instincts HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Survival Instincts. (Set to 0 to disable)");
v6("Slider", v20, "APL.Druid.Feral.Defensives.FrenziedRegenerationHP", {(0 + 0),(33 + 67),(1 + 0)}, "Frenzied Regeneration HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of FrenziedRegeneration. (Set to 0 to disable)");
v6("Slider", v20, "APL.Druid.Feral.Defensives.IronfurHP", {(267 - (176 + 91)),(147 - 47),(1876 - (157 + 1718))}, "Ironfur HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Ironfur. (Set to 0 to disable)");
v6("Slider", v20, "APL.Druid.Feral.Defensives.BearFormHP", {(0 - 0),(1118 - (697 + 321)),(1 - 0)}, "Bear Form HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Bear Form. (Set to 0 to disable)");
v6("Slider", v20, "APL.Druid.Feral.Defensives.CatFormHP", {(0 + 0),(268 - 168),(612 - (602 + 9))}, "Cat Form HP", "Set the HP percentage threshold of when you want the addon to get back into Cat Form. (Set to 0 to disable)");
v8(v20, "APL.Druid.Feral.Defensives");
v6("CheckButton", v22, "APL.Druid.Feral_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v22, "APL.Druid.Feral_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v22, "APL.Druid.Feral_TTD.RacialsTTD", {(872 - (826 + 46)),(189 - 129),(1899 - (260 + 1638))}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v22, "APL.Druid.Feral_TTD.TrinketsTTD", {(0 - 0),(124 - 64),(1206 - (902 + 303))}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v22, "APL.Druid.Feral_TTD.IncarnationTTD", {(0 - 0),(1750 - (1121 + 569)),(684 - (483 + 200))}, "Incarnation/Berserk", "Time to die to use Incarnation/Berserk");
v6("Slider", v22, "APL.Druid.Feral_TTD.ConvoketheSpiritsTTD", {(0 - 0),(825 - (468 + 297)),(3 - 2)}, "Convoke the Spirits TTD", "Time to die to use Convoke the Spirits");
v6("Slider", v22, "APL.Druid.Feral_TTD.FeralFrenzyTTD", {(0 - 0),(296 - (141 + 95)),(2 - 1)}, "Feral Frenzy TTD", "Time to die to use Feral Frenzy");
v6("Slider", v22, "APL.Druid.Feral_TTD.PotionsTTD", {(0 + 0),(43 + 17),(1 - 0)}, "Potions TTD", "Time to die to use DPS Potions");
v6("Slider", v22, "APL.Druid.Feral_TTD.TigersFuryTTD", {(163 - (92 + 71)),(100 - 40),(1 + 0)}, "Tigers Fury TTD", "Time to die to use Tigers Fury");
v8(v22, "APL.Druid.Feral_TTD");
v6("CheckButton", v23, "APL.Druid.Feral_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v23, "APL.Druid.Feral_CDUSE.Enemycount", {(2 + 0),(136 - (55 + 71)),(1791 - (573 + 1217))}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v23, "APL.Druid.Feral_CDUSE.Racials", v41, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v23, "APL.Druid.Feral_CDUSE.Potions", v41, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v23, "APL.Druid.Feral_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v23, "APL.Druid.Feral_CDUSE.Trinket1", v41, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v23, "APL.Druid.Feral_CDUSE.Trinket2", v41, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v23, "APL.Druid.Feral_CDUSE.Incarnation", v41, "Incarnation/Berserk", "Choose an option on when to use Incarnation/Berserk");
v6("Dropdown", v23, "APL.Druid.Feral_CDUSE.FeralFrenzy", v41, "Feral Frenzy", "Choose an option on when to use Feral Frenzy");
v6("Dropdown", v23, "APL.Druid.Feral_CDUSE.AdaptiveSwarm", v41, "Adaptive Swarm", "Choose an option on when to use Adaptive Swarm");
v6("Dropdown", v23, "APL.Druid.Feral_CDUSE.ConvoketheSpirits", v41, "Convoke the Spirits", "Choose an option on when to use Convoke the Spirits");
v6("Dropdown", v23, "APL.Druid.Feral_CDUSE.TigersFury", v41, "Tigers Fury", "Choose an option on when to use Tigers Fury");
v6("Dropdown", v23, "APL.Druid.Feral_CDUSE.Djaruun", v41, "Djaruun, Pillar of the Elder Flame", "Choose an option on when to use Djaruun, Pillar of the Elder Flame");
v8(v23, "APL.Druid.Feral_CDUSE");
v6("CheckButton", v24, "APL.Druid.Guardian.UseIronfurOffensively", "Use Ironfur Offensively", "Enable this if you want offensive Ironfur suggestions (e.g. with Thorns of Iron).");
v6("CheckButton", v24, "APL.Druid.Guardian.UseRageDefensively", "Use Rage Defensively", "Enable this if you want to save rage for defensive use, disabling Maul suggestions.");
v6("CheckButton", v24, "APL.Druid.Guardian.AutoTabDot", "Auto Tab for Multidotting", "Enable this if you want the addon to auto Tab for Multidotting.");
v6("CheckButton", v24, "APL.Druid.Guardian.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v6("CheckButton", v24, "APL.Druid.Guardian.TabForSoothe", "Soothe Auto Tab", "Enable this if you want the addon to auto tab for Soothe");
v8(v24, "APL.Druid.Guardian");
v6("Slider", v25, "APL.Druid.Guardian.Defensives.RenewalHP", {(0 + 0),(1039 - (714 + 225)),(1 - 0)}, "Renewal HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Renewal, if talented. (Set to 0 to disable)");
v6("Slider", v25, "APL.Druid.Guardian.Defensives.RegrowthHP", {(0 - 0),(148 - (25 + 23)),(1887 - (927 + 959))}, "Regrowth HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usage of a Dream of Cenarius buffed Regrowth. (Set to 0 to disable)");
v6("Slider", v25, "APL.Druid.Guardian.Defensives.BarkskinHP", {(732 - (16 + 716)),(197 - (11 + 86)),(286 - (175 + 110))}, "Barkskin Threshold", "Set the HP percentage threshold of when to use Barkskin.");
v6("Slider", v25, "APL.Druid.Guardian.Defensives.FrenziedRegenHP", {(0 - 0),(279 - 179),(1062 - (810 + 251))}, "Frenzied Regen Threshold", "Set the HP percentage threshold of when to use Frenzied Regeneration.");
v6("Slider", v25, "APL.Druid.Guardian.Defensives.SurvivalInstinctsHP", {(0 + 0),(633 - (43 + 490)),(3 - 2)}, "Survival Instincts Threshold", "Set the HP percentage threshold of when to use Survival Instincts.");
v6("Slider", v25, "APL.Druid.Guardian.Defensives.BristlingFurRage", {(0 + 0),(7 + 93),(406 - (255 + 150))}, "Bristling Fur Threshold", "Set the Rage threshold of when to use Bristling Fur.");
v6("Slider", v25, "APL.Druid.Guardian.Defensives.NaturesVigilHP", {(0 + 0),(322 - 222),(407 - (183 + 223))}, "Natures Vigil HP", "Set the HP threshold of when you want the addon to suggest defensive usgae of Natures Vigil. (Set to 0 to disable)");
v6("Slider", v25, "APL.Druid.Guardian.Defensives.NaturesVigilCount", {(0 + 0),(342 - (10 + 327)),(339 - (118 + 220))}, "Natures Vigil Count", "Set the Unit Count threshold to Cast Natures Vigil.");
v8(v25, "APL.Druid.Guardian.Defensives");
v6("CheckButton", v27, "APL.Druid.Guardian_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v27, "APL.Druid.Guardian_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v27, "APL.Druid.Guardian_TTD.RacialsTTD", {(449 - (108 + 341)),(253 - 193),(1 - 0)}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v27, "APL.Druid.Guardian_TTD.TrinketsTTD", {(0 + 0),(178 - 118),(1 + 0)}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v27, "APL.Druid.Guardian_TTD.IncarnationTTD", {(0 - 0),(1227 - (645 + 522)),(1 + 0)}, "Incarnation/Berserk", "Time to die to use Incarnation/Berserk");
v6("Slider", v27, "APL.Druid.Guardian_TTD.ConvoketheSpiritsTTD", {(0 - 0),(151 - 91),(506 - (351 + 154))}, "Convoke the Spirits TTD", "Time to die to use Convoke the Spirits");
v6("Slider", v27, "APL.Druid.Guardian_TTD.RageoftheSleeperTTD", {(266 - (28 + 238)),(1619 - (1381 + 178)),(1 + 0)}, "Rage of the Sleeper TTD", "Time to die to use Rage of the Sleeper");
v6("Slider", v27, "APL.Druid.Guardian_TTD.LunarBeamTTD", {(0 - 0),(530 - (381 + 89)),(1 + 0)}, "Lunar Beam TTD", "Time to die to use Lunar Beam");
v6("Slider", v27, "APL.Druid.Guardian_TTD.PotionsTTD", {(1156 - (1074 + 82)),(1844 - (214 + 1570)),(1 + 0)}, "Potions TTD", "Time to die to use DPS Potions");
v8(v27, "APL.Druid.Guardian_TTD");
v6("CheckButton", v28, "APL.Druid.Guardian_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v28, "APL.Druid.Guardian_CDUSE.Enemycount", {(2 + 0),(1736 - (1668 + 58)),(2 - 1)}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v28, "APL.Druid.Guardian_CDUSE.Racials", v41, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v28, "APL.Druid.Guardian_CDUSE.Potions", v41, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v28, "APL.Druid.Guardian_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v28, "APL.Druid.Guardian_CDUSE.Trinket1", v41, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v28, "APL.Druid.Guardian_CDUSE.Trinket2", v41, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v28, "APL.Druid.Guardian_CDUSE.Incarnation", v41, "Incarnation/Berserk", "Choose an option on when to use Incarnation/Berserk");
v6("Dropdown", v28, "APL.Druid.Guardian_CDUSE.RageoftheSleeper", v41, "Rage of the Sleeper", "Choose an option on when to use Rage of the Sleeper");
v6("Dropdown", v28, "APL.Druid.Guardian_CDUSE.LunarBeam", v41, "Lunar Beam", "Choose an option on when to use Lunar Beam");
v6("Dropdown", v28, "APL.Druid.Guardian_CDUSE.ConvoketheSpirits", v41, "Convoke the Spirits", "Choose an option on when to use Convoke the Spirits");
v6("Dropdown", v28, "APL.Druid.Guardian_CDUSE.Djaruun", v41, "Djaruun, Pillar of the Elder Flame", "Choose an option on when to use Djaruun, Pillar of the Elder Flame");
v8(v28, "APL.Druid.Guardian_CDUSE");
v6("CheckButton", v29, "APL.Druid.Restoration.EfflorUsage", "Use Efflor On Cooldown?", "Enable this if you want the addon to cast Effloresence every 30 seconds.");
v6("Slider", v29, "APL.Druid.Restoration.InnervateMP", {(0 - 0),(19 + 81),(3 - 2)}, "Innervate MP", "Set the MP percentage threshold of when you want to use this at");
v6("CheckButton", v29, "APL.Druid.Restoration.InnervateTree", "Innervate in Tree ?", "Will auto use Innervate if in Tree");
v6("Dropdown", v29, "APL.Druid.Restoration.DPSForm", {"Cat","Owl","None"}, "Which Form to DPS and Use Auto Form", "Select your Form. (Bear is not a option due to it being part of defense)");
v6("CheckButton", v29, "APL.Druid.Restoration.TabForSoothe", "Soothe Auto Tab", "Enable this if you want the addon to auto tab for Soothe");
v6("CheckButton", v29, "APL.Druid.Restoration.ConvokeDPS", "Use Convoke for DPS??", "Will Use Convoke for DPS In Selected Auto Form Only");
v6("CheckButton", v29, "APL.Druid.Restoration.PredictLogic", "Use Predictive Logic??", "Will Rotation Attempt to use Predictive Logic and auto start Ramps etc?");
v6("CheckButton", v29, "APL.Druid.Restoration.MoonfireMouseover", "Mouseover Spread Moonfire", "Will Rotation Attempt spread Moonfire via mouseover targets?");
v6("CheckButton", v29, "APL.Druid.Restoration.AttackOOC", "Attack with OOC", "Attack not in Combat?");
v6("CheckButton", v38, "APL.Druid.Restoration.Lifebloom.LifeBloomOnBothTanks", "Use Lifebloom on Both Tanks in Raid?", "Enable this if you want to keep LB on both Tanks in raid.");
v6("Dropdown", v38, "APL.Druid.Restoration.Lifebloom.LifeBloomTarget", {"Tank","DPS"}, "Lifebloom Target Choice", "Which Spec should Lifebloom be placed on? When only one LB is available");
v6("Slider", v38, "APL.Druid.Restoration.Lifebloom.LifebloomRefreshIgnore", {(0 - 0),(77 + 23),(1 + 0)}, "Lifebloom Ignore Refresh HP", "Set the HP percentage threshold of a unit if they are below that LB will not refresh.");
v6("Dropdown", v31, "APL.Druid.Restoration.Cooldowns.HeartOfTheWildUse", v40, "Heart of the Wild Usage", "How would you like to use this Cooldown?");
v6("Dropdown", v31, "APL.Druid.Restoration.Cooldowns.AdaptiveSwarmUse", v40, "Adaptive Swarm Usage", "How would you like to use this Cooldown?");
v6("Slider", v31, "APL.Druid.Restoration.Cooldowns.AdaptiveSwarmHP", {(0 - 0),(41 + 59),(1 + 0)}, "Adaptive Swarm HP", "Set the HP percentage threshold of when you want to use this at");
v6("Dropdown", v31, "APL.Druid.Restoration.Cooldowns.ConvokeUse", v40, "Convoke the Spirits Usage", "How would you like to use this Cooldown?");
v6("Dropdown", v31, "APL.Druid.Restoration.Cooldowns.NaturesVigilUse", v40, "Nature's Vigil  Usage", "How would you like to use this Cooldown?");
v6("CheckButton", v31, "APL.Druid.Restoration.Cooldowns.NVSpread", "Natures Vigil Spread", "Enable this if you want to auto spread Rej's while NV is active.");
v6("Dropdown", v31, "APL.Druid.Restoration.Cooldowns.Trinket1Use", v40, "Trinket 1 Usage", "How would you like to use this Cooldown?");
v6("Dropdown", v31, "APL.Druid.Restoration.Cooldowns.Trinket2Use", v40, "Trinket 2  Usage", "How would you like to use this Cooldown?");
v6("Slider", v31, "APL.Druid.Restoration.Cooldowns.Trinket1HP", {(1433 - (797 + 636)),(1719 - (1427 + 192)),(2 - 1)}, "Trinket 1 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("Slider", v31, "APL.Druid.Restoration.Cooldowns.Trinket2HP", {(0 + 0),(1376 - (316 + 960)),(1 + 0)}, "Trinket 2 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("Slider", v33, "APL.Druid.Restoration.AoEHealing.ConvokeHP", {(0 - 0),(1906 - (1202 + 604)),(1 - 0)}, "Convoke the Spirits HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v33, "APL.Druid.Restoration.AoEHealing.ConvokeCount", {(325 - (45 + 280)),(5 + 0),(1 + 0)}, "Convoke the Spirits Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v33, "APL.Druid.Restoration.AoEHealing.FlourishHP", {(0 - 0),(40 + 60),(2 - 1)}, "Flourish HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v33, "APL.Druid.Restoration.AoEHealing.FlourishCount", {(1948 - (1096 + 852)),(6 - 1),(513 - (409 + 103))}, "Flourish  Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v33, "APL.Druid.Restoration.AoEHealing.TranquilityHP", {(95 - (51 + 44)),(1417 - (1114 + 203)),(1 + 0)}, "Tranquility HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v33, "APL.Druid.Restoration.AoEHealing.TranquilityCount", {(663 - (174 + 489)),(1910 - (830 + 1075)),(1270 - (231 + 1038))}, "Tranquility Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v33, "APL.Druid.Restoration.AoEHealing.TreeofLife", {(1162 - (171 + 991)),(268 - 168),(1 + 0)}, "Tree of Life HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v33, "APL.Druid.Restoration.AoEHealing.TreeofLifeCount", {(0 - 0),(15 - 10),(159 - (91 + 67))}, "Tree of Life Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v33, "APL.Druid.Restoration.AoEHealing.WildGrowthHP", {(0 + 0),(1 + 99),(1 + 0)}, "Wild Growth HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v33, "APL.Druid.Restoration.AoEHealing.WildGrowthCount", {(0 - 0),(11 - 6),(882 - (614 + 267))}, "Wild Growth Count", "Set the Unit Count threshold to Cast.");
v6("CheckButton", v33, "APL.Druid.Restoration.AoEHealing.WGSpread", "Use Wild Growth for Spread", "Enable this if you want to auto spread WG during Spread Toggle.");
v6("Slider", v39, "APL.Druid.Restoration.Soul.WildGrowthSoulHP", {(0 - 0),(285 - 185),(1 - 0)}, "Wild Growth with Soul HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v39, "APL.Druid.Restoration.Soul.WildGrowthSoulCount", {(1812 - (1293 + 519)),(13 - 8),(4 - 3)}, "Wild Growth with Soul Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v39, "APL.Druid.Restoration.Soul.RejSoulHP", {(0 + 0),(232 - 132),(1 + 0)}, "Rejuvenation with Soul HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v39, "APL.Druid.Restoration.Soul.RegrowthSoulHP", {(1096 - (709 + 387)),(290 - 190),(1 - 0)}, "Regrowth with Soul HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v34, "APL.Druid.Restoration.Healing.GerminationHoTHP", {(0 + 0),(25 + 75),(1 - 0)}, "Germination HoT HP", "Set the MP percentage threshold of when you want to use this at");
v6("Slider", v34, "APL.Druid.Restoration.Healing.GroveGuardiansHP", {(1283 - (1040 + 243)),(1947 - (559 + 1288)),(455 - (13 + 441))}, "Grove Gaurdians HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v34, "APL.Druid.Restoration.Healing.InvigorateHP", {(0 - 0),(4 + 96),(1 + 0)}, "Invigorate HP", "Set the HP percentage threshold of when you want to use this at if not tank only");
v6("Slider", v34, "APL.Druid.Restoration.Healing.IronbarkHP", {(0 - 0),(183 - 83),(1 + 0)}, "Iron Bark HP", "Set the HP percentage threshold of when you want to use this at if not Tank Only");
v6("Slider", v34, "APL.Druid.Restoration.Healing.NaturesSwiftnessHP", {(0 + 0),(533 - (153 + 280)),(1 + 0)}, "Natures Swiftness HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v34, "APL.Druid.Restoration.Healing.Nourish", {(0 + 0),(73 + 27),(1 + 0)}, "Nourish HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v34, "APL.Druid.Restoration.Healing.OvergrowthHP", {(0 + 0),(1149 - (572 + 477)),(1 + 0)}, "Overgrowth HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v34, "APL.Druid.Restoration.Healing.RegrowthHP", {(86 - (84 + 2)),(73 + 27),(1 + 0)}, "Regrowth HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v34, "APL.Druid.Restoration.Healing.RegrowthClearHP", {(1333 - (605 + 728)),(222 - 122),(3 - 2)}, "Regrowth with ClearCasting HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v34, "APL.Druid.Restoration.Healing.RejuvenationHP", {(0 - 0),(589 - (457 + 32)),(1403 - (832 + 570))}, "Rejuvenation HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v34, "APL.Druid.Restoration.Healing.SwiftmendHP", {(0 + 0),(49 + 51),(2 - 1)}, "Swiftmend HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v35, "APL.Druid.Restoration.RaidAoEHealing.ConvokeHP", {(0 - 0),(753 - (232 + 421)),(1 + 0)}, "Convoke the Spirits HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v35, "APL.Druid.Restoration.RaidAoEHealing.ConvokeCount", {(0 - 0),(104 - 64),(1454 - (666 + 787))}, "Convoke the Spirits Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v35, "APL.Druid.Restoration.RaidAoEHealing.FlourishHP", {(0 + 0),(157 - 57),(2 - 1)}, "Flourish HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v35, "APL.Druid.Restoration.RaidAoEHealing.FlourishCount", {(899 - (503 + 396)),(77 - 37),(1 + 0)}, "Flourish  Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v35, "APL.Druid.Restoration.RaidAoEHealing.TranquilityHP", {(0 + 0),(88 + 12),(2 - 1)}, "Tranquility HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v35, "APL.Druid.Restoration.RaidAoEHealing.TranquilityCount", {(0 - 0),(92 - 52),(1136 - (832 + 303))}, "Tranquility Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v35, "APL.Druid.Restoration.RaidAoEHealing.TreeofLife", {(0 + 0),(5 + 95),(4 - 3)}, "Tree of Life HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v35, "APL.Druid.Restoration.RaidAoEHealing.TreeofLifeCount", {(0 - 0),(1113 - (1036 + 37)),(1 - 0)}, "Tree of Life Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v35, "APL.Druid.Restoration.RaidAoEHealing.WildGrowthHP", {(1480 - (641 + 839)),(254 - 154),(1 + 0)}, "Wild Growth HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v35, "APL.Druid.Restoration.RaidAoEHealing.WildGrowthCount", {(0 + 0),(860 - (174 + 680)),(1 - 0)}, "Wild Growth Count", "Set the Unit Count threshold to Cast.");
v6("CheckButton", v35, "APL.Druid.Restoration.RaidAoEHealing.WGSpread", "Use Wild Growth for Spread", "Enable this if you want to auto spread WG during Spread Toggle.");
v6("Slider", v36, "APL.Druid.Restoration.RaidHealing.GerminationHoTHP", {(739 - (396 + 343)),(1577 - (29 + 1448)),(3 - 2)}, "Germination HoT HP", "Set the MP percentage threshold of when you want to use this at");
v6("Slider", v36, "APL.Druid.Restoration.RaidHealing.GroveGuardiansHP", {(0 + 0),(674 - (102 + 472)),(1 + 0)}, "Grove Gaurdians HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v36, "APL.Druid.Restoration.RaidHealing.InvigorateHP", {(1545 - (320 + 1225)),(62 + 38),(1860 - (821 + 1038))}, "Invigorate HP", "Set the HP percentage threshold of when you want to use this at if not tank only");
v6("Slider", v36, "APL.Druid.Restoration.RaidHealing.IronbarkHP", {(0 + 0),(38 + 62),(1027 - (834 + 192))}, "Iron Bark HP", "Set the HP percentage threshold of when you want to use this at if not Tank Only");
v6("Slider", v36, "APL.Druid.Restoration.RaidHealing.NaturesSwiftnessHP", {(0 + 0),(154 - 54),(1 + 0)}, "Natures Swiftness HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v36, "APL.Druid.Restoration.RaidHealing.Nourish", {(362 - (112 + 250)),(250 - 150),(1 + 0)}, "Nourish HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v36, "APL.Druid.Restoration.RaidHealing.OvergrowthHP", {(0 + 0),(1514 - (1001 + 413)),(883 - (244 + 638))}, "Overgrowth HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v36, "APL.Druid.Restoration.RaidHealing.RegrowthHP", {(0 - 0),(2006 - (1665 + 241)),(1 + 0)}, "Regrowth HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v36, "APL.Druid.Restoration.RaidHealing.RegrowthClearHP", {(0 - 0),(1199 - (35 + 1064)),(2 - 1)}, "Regrowth with ClearCasting HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v36, "APL.Druid.Restoration.RaidHealing.RejuvenationHP", {(1236 - (298 + 938)),(1766 - (636 + 1030)),(1 + 0)}, "Rejuvenation HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v36, "APL.Druid.Restoration.RaidHealing.SwiftmendHP", {(0 + 0),(20 + 80),(3 - 2)}, "Swiftmend HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v37, "APL.Druid.Restoration.TankHealing.CenWardHP", {(0 - 0),(39 + 61),(1284 - (1035 + 248))}, "Cenarion Ward HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v37, "APL.Druid.Restoration.TankHealing.InvigorateTankHP", {(0 + 0),(1233 - (549 + 584)),(3 - 2)}, "Invigorate on Tank HP", "Set the HP percentage threshold of when you want to use this at");
v6("CheckButton", v37, "APL.Druid.Restoration.TankHealing.InvigorateOnTankOnly", "Invigorate On Tank Only", "Enable this if you want to use on Tank Only.");
v6("Slider", v37, "APL.Druid.Restoration.TankHealing.IronbarkTankHP", {(0 + 0),(323 - 223),(1341 - (1093 + 247))}, "Ironbark on Tank HP", "Set the HP percentage threshold of when you want to use this at");
v6("CheckButton", v37, "APL.Druid.Restoration.TankHealing.IronbarkOnTankOnly", "Ironbark On Tank Only", "Enable this if you want to use on Tank Only.");
v6("Slider", v37, "APL.Druid.Restoration.TankHealing.RegrowthTankHP", {(0 + 0),(339 - 239),(2 - 1)}, "Regrowth on Tank HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v37, "APL.Druid.Restoration.TankHealing.RejTankHP", {(0 - 0),(76 + 24),(689 - (364 + 324))}, "Rejuvenation on Tank HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v37, "APL.Druid.Restoration.TankHealing.SwiftTankHP", {(0 - 0),(418 - 318),(2 - 1)}, "Swiftmend on Tank HP", "Set the HP percentage threshold of when you want to use this at");
v6("Slider", v32, "APL.Druid.Restoration.Defensives.RenewalHP", {(0 + 0),(1186 - (686 + 400)),(230 - (73 + 156))}, "Renewal HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Renewal. (Set to 0 to disable)");
v6("Slider", v32, "APL.Druid.Restoration.Defensives.BarkskinHP", {(811 - (721 + 90)),(324 - 224),(1 - 0)}, "Barkskin HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Barkskin. (Set to 0 to disable)");
v6("Slider", v32, "APL.Druid.Restoration.Defensives.FrenziedRegenerationHP", {(0 + 0),(74 + 26),(3 - 2)}, "Frenzied Regeneration HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of FrenziedRegeneration. (Set to 0 to disable)");
v6("Slider", v32, "APL.Druid.Restoration.Defensives.IronfurHP", {(1993 - (1238 + 755)),(1634 - (709 + 825)),(1 - 0)}, "Ironfur HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Ironfur. (Set to 0 to disable)");
v6("Slider", v32, "APL.Druid.Restoration.Defensives.BearFormHP", {(0 - 0),(933 - (171 + 662)),(3 - 2)}, "Bear Form HP", "Set the HP percentage threshold of when you want the addon to suggest defensive usgae of Bear Form. (Set to 0 to disable)");
v8(v39, "APL.Druid.Restoration.Soul");
v8(v38, "APL.Druid.Restoration.Lifebloom");
v8(v31, "APL.Druid.Restoration.Cooldowns");
v8(v33, "APL.Druid.Restoration.AoEHealing");
v8(v34, "APL.Druid.Restoration.Healing");
v8(v37, "APL.Druid.Restoration.TankHealing");
v8(v32, "APL.Druid.Restoration.Defensives");
v8(v35, "APL.Druid.Restoration.RaidAoEHealing");
v8(v36, "APL.Druid.Restoration.RaidHealing");
v8(v29, "APL.Druid.Restoration");
v10.APL.Druid.Feral.Display = function()
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v33);
	v3.GUI.HidePanel(v31);
	v3.GUI.HidePanel(v32);
	v3.GUI.HidePanel(v34);
	v3.GUI.HidePanel(v38);
	v3.GUI.HidePanel(v39);
	v3.GUI.HidePanel(v37);
	v3.GUI.HidePanel(v35);
	v3.GUI.HidePanel(v36);
	v3.GUI.HidePanel(v14);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v9);
	v3.GUI.HidePanel(v30);
	v3.GUI.ShowPanel(v19);
	v3.GUI.ShowPanel(v20);
	v3.GUI.ShowPanel(v21);
	v3.GUI.ShowPanel(v22);
	v3.GUI.ShowPanel(v23);
end;
v10.APL.Druid.Balance.Display = function()
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v33);
	v3.GUI.HidePanel(v31);
	v3.GUI.HidePanel(v32);
	v3.GUI.HidePanel(v34);
	v3.GUI.HidePanel(v38);
	v3.GUI.HidePanel(v39);
	v3.GUI.HidePanel(v37);
	v3.GUI.HidePanel(v35);
	v3.GUI.HidePanel(v36);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v9);
	v3.GUI.HidePanel(v30);
	v3.GUI.ShowPanel(v14);
	v3.GUI.ShowPanel(v15);
	v3.GUI.ShowPanel(v16);
	v3.GUI.ShowPanel(v17);
	v3.GUI.ShowPanel(v18);
end;
v10.APL.Druid.Guardian.Display = function()
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v33);
	v3.GUI.HidePanel(v31);
	v3.GUI.HidePanel(v32);
	v3.GUI.HidePanel(v34);
	v3.GUI.HidePanel(v38);
	v3.GUI.HidePanel(v39);
	v3.GUI.HidePanel(v37);
	v3.GUI.HidePanel(v35);
	v3.GUI.HidePanel(v36);
	v3.GUI.HidePanel(v14);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v9);
	v3.GUI.HidePanel(v30);
	v3.GUI.ShowPanel(v24);
	v3.GUI.ShowPanel(v25);
	v3.GUI.ShowPanel(v26);
	v3.GUI.ShowPanel(v27);
	v3.GUI.ShowPanel(v28);
end;
v10.APL.Druid.Restoration.Display = function()
	v3.GUI.ShowPanel(v29);
	v3.GUI.ShowPanel(v33);
	v3.GUI.ShowPanel(v31);
	v3.GUI.ShowPanel(v32);
	v3.GUI.ShowPanel(v34);
	v3.GUI.ShowPanel(v38);
	v3.GUI.ShowPanel(v39);
	v3.GUI.ShowPanel(v37);
	v3.GUI.ShowPanel(v30);
	v3.GUI.ShowPanel(v35);
	v3.GUI.ShowPanel(v36);
	v3.GUI.HidePanel(v14);
	v3.GUI.HidePanel(v15);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v20);
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v9);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v28);
end;
