local v0, v1 = ...;
local v2 = HeroRotation();
local v3 = HeroLib;
local v4 = v3.GUI;
local v5 = v4.CreateChildPanel;
local v6 = v4.CreatePanelOption;
local v7 = v2.HRGUIGet().CreateARPanelOption;
local v8 = v2.HRGUIGet().CreateARPanelOptions;
local v9 = v4.GetPanelByName("Interrupt");
local v10 = v2.GUISettingsGet();
v10.APL.Priest = {Commons={Enabled={Potions=true,Trinkets=true,Items=true},TabForDispelMagic=false,AutoFadeEntangling=false,PowerWordFortitude="only check us",DisplayStyle={Potions="Suggested",Trinkets="Suggested",Items="Suggested",Signature="Suggested"}},Shadow={AttackonlyinCombat=false,Movement="always",VTMinHP=(2 - 1),PreferVTWhenSTinDungeon=false,CursorCheck=true,Defensives={DesperatePrayerHP=(214 - 139),DispersionHP=(0 - 0),FlashHealHP=(77 - 47),PowerWordLifeHP=(649 - (555 + 64)),FadeHP=(951 - (857 + 74)),PWShieldHP=(618 - (367 + 201)),VampiricEmbraceHP=(987 - (214 + 713)),VampiricEmbraceCount=(1 + 2)},PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"}},Shadow_CDUSE={smallcdswithCooldowns=true,Enemycount=(1 + 4),Racials="with Cooldowns",Potions="with Cooldowns",Potionswhensolo=false,Trinket1="with Cooldowns",Trinket2="with Cooldowns",VoidEruption="with Cooldowns",VoidEruptionASAP=false,VoidTorrent="with Cooldowns",ShadowCrash="with Cooldowns",Mindbender="with Cooldowns",PowerInfusion="with Cooldowns",Halo="always",CleverPI=true,Weapon="with Cooldowns"},Shadow_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(937 - (282 + 595)),InterruptPercentChannel=(1697 - (1523 + 114))}},Shadow_TTD={RacialsTTD=(18 + 2),TrinketsTTD=(28 - 8),VoidEruptionTTD=(1085 - (68 + 997)),MindbenderTTD=(1290 - (226 + 1044)),PowerInfusionTTD=(87 - 67),VoidTorrentTTD=(127 - (32 + 85)),WeaponTTD=(10 + 0),PotionsTTD=(5 + 15),HaloTTD=(967 - (892 + 65)),IgnoreWhenSolo=true,IgnoreWhenBoss=true},Disc_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(143 - 83),InterruptPercentChannel=(110 - 50)}},Holy_Interrupt={Interrupt={AutoInterrupt=true,AutoStun=true,InterruptEverythingSolo=true,InterruptEverythingRaid=true,InterruptInDungeon="Whitelist",InterruptInDungeonUseStunAsInterrupt=true,InterruptPercent=(110 - 50),InterruptPercentChannel=(410 - (87 + 263))}},Discipline={Solace=(275 - (67 + 113)),AttackOOC=false,DesperatePrayerHP=(55 + 20),FadeHP=(49 - 29),ShadowfiendMana=(70 + 25),ShadowFiendRamp=true,RenewHP=(258 - 193),RenewMovingHP=(1037 - (802 + 150)),RenewOnlyMoving=true,VoidShiftTankOnly=true,SelectPI=false,PIRaidUnit="raid1",PIGroupUnit="party1",PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"},Trinket1Use="With Logic",Trinket2Use="With Logic",Trinket1HP=(175 - 110),Trinket2HP=(117 - 52)},DiscExtras={Movement=false,UseHolyNova=false,AutoRamp=false,PremUse=true,PremRCount=(3 + 0),PremPCount=(999 - (915 + 82)),PremHP=(155 - 100)},DiscHealing={FlashHealHP=(44 + 31),FlashAtoneIgnoreHP=(32 - 7),FlashHealSurgeHP=(1252 - (1069 + 118)),PainSupHP=(101 - 56),PainSupOnTank=true,PenanceHP=(142 - 77),PWSHP=(17 + 78),PWSAtoneIgnoreHP=(62 - 27),PWSTankHP=(99 + 0)},DiscAoE={EvangHP=(866 - (368 + 423)),VEHP=(251 - 171),RapHP=(83 - (10 + 8)),PWBLHP=(192 - 142),PWRHP=(527 - (416 + 26)),PWRAtoneHP=(143 - 98),HaloHP=(37 + 48),DSHP=(176 - 76),UPHP=(473 - (145 + 293)),EvangCount=(433 - (44 + 386)),VECount=(1489 - (998 + 488)),RapCount=(1 + 2),PWBLCount=(3 + 0),PWRCount=(775 - (201 + 571)),PWRAtoneCount=(1141 - (116 + 1022)),HaloCount=(12 - 9),DSCount=(2 + 1),UPCount=(10 - 7)},DiscRaidHealing={FlashHealHP=(266 - 191),FlashAtoneIgnoreHP=(884 - (814 + 45)),FlashHealSurgeHP=(160 - 95),PainSupHP=(3 + 42),PainSupOnTank=true,PenanceHP=(23 + 42),PWSHP=(980 - (261 + 624)),PWSAtoneIgnoreHP=(62 - 27),PWSTankHP=(1179 - (1020 + 60))},DiscRaidAoE={EvangHP=(1498 - (630 + 793)),VEHP=(271 - 191),RapHP=(307 - 242),PWBLHP=(20 + 30),PWRHP=(292 - 207),PWRAtoneHP=(1792 - (760 + 987)),HaloHP=(1998 - (1789 + 124)),DSHP=(866 - (745 + 21)),UPHP=(13 + 22),EvangCount=(27 - 17),VECount=(27 - 20),RapCount=(1 + 7),PWBLCount=(7 + 1),PWRCount=(1060 - (87 + 968)),PWRAtoneCount=(22 - 17),HaloCount=(6 + 0),DSCount=(13 - 7),UPCount=(1421 - (447 + 966))},Holy={DesperatePrayerHP=(205 - 130),FadeHP=(1837 - (1703 + 114)),ShadowfiendMana=(796 - (376 + 325)),RenewHP=(106 - 41),RenewMovingHP=(261 - 176),RenewOnlyMoving=true,Movement=false,SelectPI=false,PIRaidUnit="raid1",PIGroupUnit="party1",AttackOOC=false,PotionType={Selected="Tempered Potion"},PotionRank={Selected="Any"}},HolyCooldowns={ApotheosisUsage="With Logic",ApotheosisHP=(19 + 46),ApotheosisRaidCount=(12 - 6),ApotheosisPartyCount=(17 - (9 + 5)),Trinket1Use="With Logic",Trinket2Use="With Logic",Trinket1HP=(441 - (85 + 291)),Trinket2HP=(1330 - (243 + 1022)),LightWellHP=(361 - 266),LightWellPCount=(2 + 0),LightWellRCount=(1182 - (1123 + 57)),PremUse=true,PremRCount=(3 + 0),PremPCount=(256 - (163 + 91)),PremHP=(1985 - (1869 + 61))},HolyHealing={HealHP=(24 + 61),FlashHealHP=(228 - 163),FlashHealSurge1HP=(99 - 34),FlashHealSurge2HP=(12 + 73),HolyWordSerenityHP=(109 - 29),GSHP=(24 + 1),GSTank=true,DWHP=(1559 - (1329 + 145))},HolyAoE={CoHHP=(1056 - (140 + 831)),CoHOnlyMoving=true,DHHP=(1895 - (1409 + 441)),DSHP=(818 - (15 + 703)),HaloHP=(47 + 53),HolyNovaHP=(523 - (262 + 176)),SalvHP=(1746 - (345 + 1376)),SancHP=(773 - (198 + 490)),PoHHP=(287 - 222),CoHCount=(6 - 3),DHCount=(1209 - (696 + 510)),DSCount=(5 - 2),HaloCount=(1265 - (1091 + 171)),HolyNovaCount=(1 + 2),SalvCount=(9 - 6),SancCount=(9 - 6),PoHCount=(378 - (123 + 251))},HolyRaidHealing={HealHP=(422 - 337),FlashHealHP=(763 - (208 + 490)),FlashHealSurge1HP=(6 + 59),FlashHealSurge2HP=(38 + 47),HolyWordSerenityHP=(916 - (660 + 176)),GSHP=(4 + 21),GSTank=true,DWHP=(287 - (14 + 188))},HolyRaidAoE={CoHHP=(760 - (534 + 141)),CoHOnlyMoving=true,DHHP=(19 + 26),DSHP=(89 + 11),HaloHP=(97 + 3),HolyNovaHP=(178 - 93),SalvHP=(39 - 14),SancHP=(238 - 153),PoHHP=(3 + 2),CoHCount=(4 + 1),DHCount=(402 - (115 + 281)),DSCount=(13 - 7),HaloCount=(5 + 1),HolyNovaCount=(14 - 8),SalvCount=(29 - 21),SancCount=(872 - (550 + 317)),PoHCount=(7 - 2)}};
v2.HRGUIGet().LoadSettingsRecursively(v10);
local v12 = {"With Cooldowns","With Logic","With Cooldowns and Logic","Not Used"};
local v13 = {"Not Used","always","with Cooldowns","small CDs","with Cooldowns or AoE","on Enemycount or Cooldowns","on Boss or with Cooldowns","on Boss only","with Bloodlust only","on AOE","on Enemycount","on Boss or on Enemycount"};
local v14 = v2.HRGUIGet().Panel;
local v15 = v5(v14, "Priest");
local v16 = v5(v15, "Shadow");
local v17 = v5(v16, "Defensives");
local v18 = v5(v16, "Interrupt");
v8(v18, "APL.Priest.Shadow_Interrupt");
local v19 = v5(v16, "TTD");
local v20 = v5(v16, "Cooldown settings");
local v21 = v5(v15, "Discipline");
local v22 = v5(v21, "Extras");
local v23 = v5(v21, "Healing");
local v24 = v5(v21, "AoE Healing");
local v25 = v5(v21, "AoE Healing2");
local v26 = v5(v21, "Raid Healing");
local v27 = v5(v21, "Raid AoE Healing");
local v28 = v5(v21, "Raid AoE Healing2");
local v29 = v5(v21, "Interrupt");
v8(v29, "APL.Priest.Disc_Interrupt");
local v30 = v5(v15, "Holy");
local v31 = v5(v30, "Cooldowns");
local v32 = v5(v30, "Healing");
local v33 = v5(v30, "AoE Healing");
local v34 = v5(v30, "Raid Healing");
local v35 = v5(v30, "Raid AoE Healing");
local v36 = v5(v30, "Interrupt");
v8(v36, "APL.Priest.Holy_Interrupt");
v8(v15, "APL.Priest.Commons");
local v37 = {"raid1","raid2","raid3","raid4","raid5","raid6","raid7","raid8","raid9","raid10","raid11","raid12","raid13","raid14","raid15","raid16","raid17","raid18","raid19","raid20","raid21","raid22","raid23","raid24","raid25","raid26","raid27","raid28","raid29","raid30","raid31","raid32","raid33","raid34","raid35","raid36","raid37","raid38","raid39","raid40"};
local v38 = {"player","party1","party2","party3","party4"};
v6("CheckButton", v15, "APL.Priest.Commons.TabForDispelMagic", "Dispel Magic Auto Tab", "Enable this if you want the addon to auto tab for Dispel Magic");
v6("Dropdown", v15, "APL.Priest.Commons.PowerWordFortitude", {"dont use","only check us","check whole group"}, "Power Word Fortitude", "Decide if we want to use Power Word Fortitude and who to check for the Buff.");
v6("CheckButton", v15, "APL.Priest.Commons.AutoFadeEntangling", "Auto Fade on Entangling", "Enable this if you want the addon to Auto Fade on Entangling Debuff");
v6("Slider", v17, "APL.Priest.Shadow.Defensives.DesperatePrayerHP", {(1145 - (466 + 679)),(286 - 186),(1 + 0)}, "Desperate Prayer HP", "Set the Desperate Prayer HP threshold.");
v6("Slider", v17, "APL.Priest.Shadow.Defensives.DispersionHP", {(0 - 0),(214 - (4 + 110)),(1428 - (41 + 1386))}, "Dispersion HP", "Set the Dispersion HP threshold.");
v6("Slider", v17, "APL.Priest.Shadow.Defensives.FlashHealHP", {(0 + 0),(289 - 189),(1 - 0)}, "Flash Heal HP", "Set the Flash Heal HP threshold.");
v6("Slider", v17, "APL.Priest.Shadow.Defensives.PowerWordLifeHP", {(0 + 0),(202 - 102),(1 + 0)}, "Power Word Life HP", "Set the Power Word Life HP threshold.");
v6("Slider", v17, "APL.Priest.Shadow.Defensives.FadeHP", {(0 - 0),(269 - 169),(321 - (53 + 267))}, "Fade HP", "Set the Fade HP threshold.");
v6("Slider", v17, "APL.Priest.Shadow.Defensives.PWShieldHP", {(413 - (15 + 398)),(376 - 276),(1 + 0)}, "PW:Shield HP", "Set the PW:Shield HP threshold.");
v6("Slider", v17, "APL.Priest.Shadow.Defensives.VampiricEmbraceHP", {(0 + 0),(8 + 92),(1 - 0)}, "Vampiric Embrace HP", "Set the HP threshold of when you want the addon to suggest defensive usgae of Vampiric Embrace. (Set to 0 to disable)");
v6("Slider", v17, "APL.Priest.Shadow.Defensives.VampiricEmbraceCount", {(0 + 0),(12 - 7),(1552 - (1126 + 425))}, "Vampiric Embrace Count", "Set the Unit Count threshold to Cast Vampiric Embrace.");
v8(v17, "APL.Priest.Shadow.Defensives");
v6("CheckButton", v19, "APL.Priest.Shadow_TTD.IgnoreWhenSolo", "Ignore Time to Die when solo", "Enable this if you want to ignore Time to die when you are solo.");
v6("CheckButton", v19, "APL.Priest.Shadow_TTD.IgnoreWhenBoss", "Ignore Time to Die when in Bossfight", "Enable this if you want to ignore Time to die when you are in a Bossfight.");
v6("Slider", v19, "APL.Priest.Shadow_TTD.RacialsTTD", {(0 - 0),(175 - 115),(4 - 3)}, "Racials TTD", "Time to die to use Racial spells");
v6("Slider", v19, "APL.Priest.Shadow_TTD.TrinketsTTD", {(977 - (553 + 424)),(53 + 7),(1 + 0)}, "Trinkets TTD", "Time to die to use Trinkets");
v6("Slider", v19, "APL.Priest.Shadow_TTD.VoidEruptionTTD", {(0 + 0),(167 - 107),(1 + 0)}, "Void Eruption/Dark Ascension TTD", "Time to die to use Void Eruption/Dark Ascension");
v6("Slider", v19, "APL.Priest.Shadow_TTD.PowerInfusionTTD", {(753 - (239 + 514)),(1389 - (797 + 532)),(1 + 0)}, "Power Infusion TTD", "Time to die to use Power Infusion");
v6("Slider", v19, "APL.Priest.Shadow_TTD.VoidTorrentTTD", {(1202 - (373 + 829)),(1190 - (369 + 761)),(1 - 0)}, "Void Torrent TTD", "Time to die to use Void Torrent");
v6("Slider", v19, "APL.Priest.Shadow_TTD.MindbenderTTD", {(238 - (64 + 174)),(88 - 28),(217 - (42 + 174))}, "Mindbender/Shadowfiend TTD", "Time to die to use Mindbender/Shadowfiend");
v6("Slider", v19, "APL.Priest.Shadow_TTD.WeaponTTD", {(0 + 0),(1564 - (363 + 1141)),(2 - 1)}, "Weapon TTD", "Time to die to use Weapon");
v6("Slider", v19, "APL.Priest.Shadow_TTD.PotionsTTD", {(0 + 0),(38 + 22),(1934 - (565 + 1368))}, "Potions TTD", "Time to die to use DPS Potions");
v6("Slider", v19, "APL.Priest.Shadow_TTD.HaloTTD", {(1661 - (1477 + 184)),(56 + 4),(1 - 0)}, "Halo TTD", "Time to die to use Halo");
v8(v19, "APL.Priest.Shadow_TTD");
v8(v16, "APL.Priest.Shadow");
v6("CheckButton", v16, "APL.Priest.Shadow.PreferVTWhenSTinDungeon", "Prefer VT for dungeon ST", "Prefer to use Vampiric Touch while in single target combat in dungeon content. (Note: This does not apply to raid content.)");
v6("CheckButton", v16, "APL.Priest.Shadow.AttackonlyinCombat", "Only attack Targets in combat", "Enable this if you want the addon to only attack Mobs in combat.");
v6("Dropdown", v16, "APL.Priest.Shadow.Movement", {"never","Only out of combat","Only in Combat","always"}, "Use Movement Abilities", "Use Movement Abilities such as Angelic Feather or Shadow Word Shield.");
v6("CheckButton", v16, "APL.Priest.Shadow.CursorCheck", "Cursor Check", "Will check if an Enemy is at the cursor Place currently before fireing spells like Shadow Crash.");
v6("Slider", v16, "APL.Priest.Shadow.VTMinHP", {(0 + 0),(7 + 13),(1 + 0)}, "Minimum VT HP (in millions)", "Set the minimum HP of a target for Vampiric Touch to be suggested. This value is multiplied by 1,000,000. For example, a value of 10 checks for a target's minimum HP of 10,000,000.");
v6("CheckButton", v20, "APL.Priest.Shadow_CDUSE.smallcdswithCooldowns", "Use small cds when Cd toggle is active", "Small cds will also get triggered when the regular cd toggle is active.");
v6("Slider", v20, "APL.Priest.Shadow_CDUSE.Enemycount", {(269 - (176 + 91)),(14 - 4),(1876 - (157 + 1718))}, "Enemycount", "How many Enemys we need in range to use a selected Cooldown.");
v6("Dropdown", v20, "APL.Priest.Shadow_CDUSE.Racials", v13, "Racials", "Choose an option on when to use Racials");
v6("Dropdown", v20, "APL.Priest.Shadow_CDUSE.Potions", v13, "DPS Potions", "Choose an option on when to use Potions");
v6("CheckButton", v20, "APL.Priest.Shadow_CDUSE.Potionswhensolo", "Use DPS Potions when solo", "Enable this if you want to use Potions even when doing solo stuff.");
v6("Dropdown", v20, "APL.Priest.Shadow_CDUSE.Trinket1", v13, "Trinket1", "Choose an option on when to use Trinket1");
v6("Dropdown", v20, "APL.Priest.Shadow_CDUSE.Trinket2", v13, "Trinket2", "Choose an option on when to use Trinket2");
v6("Dropdown", v20, "APL.Priest.Shadow_CDUSE.VoidEruption", v13, "Void Eruption/Dark Ascension", "Choose an option on when to use Void Eruption/Dark Ascension");
v6("CheckButton", v20, "APL.Priest.Shadow_CDUSE.VoidEruptionASAP", "Void Eruption/Dark Ascension asap", "Enable this if you want to ignore advanced Void Eruption/Dark Ascension conditions and use it asap.");
v6("Dropdown", v20, "APL.Priest.Shadow_CDUSE.VoidTorrent", v13, "Void Torrent", "Choose an option on when to use Void Torrent");
v6("Dropdown", v20, "APL.Priest.Shadow_CDUSE.ShadowCrash", v13, "Shadow Crash", "Choose an option on when to use Shadow Crash");
v6("Dropdown", v20, "APL.Priest.Shadow_CDUSE.Mindbender", v13, "Mindbender/Shadow Fiend", "Choose an option on when to use Mindbender/Shadow Fiend");
v6("Dropdown", v20, "APL.Priest.Shadow_CDUSE.PowerInfusion", v13, "Power Infusion", "Choose an option on when to use Power Infusion");
v6("CheckButton", v20, "APL.Priest.Shadow_CDUSE.CleverPI", "Clever PI use on Focus or self", "Use Power Infusion on Player when solo and on Focus when Focus Target exists.");
v6("Dropdown", v20, "APL.Priest.Shadow_CDUSE.Weapon", v13, "Weapon", "Choose an option on when to use Weapon");
v6("Dropdown", v20, "APL.Priest.Shadow_CDUSE.Halo", v13, "Halo", "Choose an option on when to use Halo");
v8(v20, "APL.Priest.Shadow_CDUSE");
v6("Slider", v21, "APL.Priest.Discipline.ShadowfiendMana", {(0 - 0),(1118 - (697 + 321)),(1 - 0)}, "Mana Percent for Fiend/Bender", "Set the Mana threshold. (Ignored During Ramps)");
v6("CheckButton", v21, "APL.Priest.Discipline.ShadowFiendRamp", "Fiend/Bender/Void during Mini Ramp", "Use Fiend/Beind/Void during mini ramps (Not the toggle or auto ramps)");
v6("Slider", v21, "APL.Priest.Discipline.DesperatePrayerHP", {(0 + 0),(268 - 168),(612 - (602 + 9))}, "Desperate Prayer HP", "Set the Desperate Prayer HP threshold.");
v6("Slider", v21, "APL.Priest.Discipline.FadeHP", {(872 - (826 + 46)),(315 - 215),(1899 - (260 + 1638))}, "Fade HP", "Set the Fade HP threshold.");
v6("Slider", v21, "APL.Priest.Discipline.RenewHP", {(0 - 0),(206 - 106),(1206 - (902 + 303))}, "Renew HP", "Set the Renew HP threshold.");
v6("Slider", v21, "APL.Priest.Discipline.RenewMovingHP", {(0 - 0),(1790 - (1121 + 569)),(684 - (483 + 200))}, "Renew while Moving HP", "Set the Renew while Moving HP threshold.");
v6("CheckButton", v21, "APL.Priest.Discipline.RenewOnlyMoving", "Renew while moving only", "Renew while moving only");
v6("CheckButton", v21, "APL.Priest.Discipline.VoidShiftTankOnly", "Void Shift On Tank Only", "Void Shift On Tank Only??");
v6("CheckButton", v21, "APL.Priest.Discipline.SelectPI", "Select your Unit for PI? ", "Enable this if you'd like to select your unit for PI? ");
v6("Dropdown", v21, "APL.Priest.Discipline.PIGroupUnit", v38, "PI Group Selection", "Unit to always keep PS on in Raid Only");
v6("Dropdown", v21, "APL.Priest.Discipline.PIRaidUnit", v37, "PI Raid Selection", "Unit to always keep PS on in Group Only");
v6("Dropdown", v21, "APL.Priest.Discipline.Trinket1Use", v12, "Trinket 1 Usage", "How would you like to use this Cooldown?");
v6("Dropdown", v21, "APL.Priest.Discipline.Trinket2Use", v12, "Trinket 2  Usage", "How would you like to use this Cooldown?");
v6("Slider", v21, "APL.Priest.Discipline.Trinket1HP", {(0 - 0),(865 - (468 + 297)),(3 - 2)}, "Trinket 1 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("Slider", v21, "APL.Priest.Discipline.Trinket2HP", {(0 - 0),(336 - (141 + 95)),(2 - 1)}, "Trinket 2 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("CheckButton", v21, "APL.Priest.Discipline.ScreamInt", "Use Psychic Stream As Interrupt", "Enable this if you'd like to use it as Interrupt.");
v6("CheckButton", v21, "APL.Priest.Discipline.AttackOOC", "Attack with OOC", "Attack not in Combat?");
v6("CheckButton", v22, "APL.Priest.DiscExtras.Movement", "Use Movement Abilities", "Use Movement Abilities such as Angelic Feather or Shadow Word Shield out of Combat.");
v6("CheckButton", v22, "APL.Priest.DiscExtras.UseHolyNova", "Use Holy Nova", "Use Holy Nova for DPS when within 12 yards of 3 or more targets.");
v6("CheckButton", v22, "APL.Priest.DiscExtras.AutoRamp", "Auto Ramp", "Rotation Will attempt Auto Ramp based on incoming Damage and Logic.");
v6("CheckButton", v22, "APL.Priest.DiscExtras.PremUse", "Use Premontion", "Use Premontion With Logic? Untick if you would like to Manual!");
v6("Slider", v22, "APL.Priest.DiscExtras.PremPCount", {(0 + 0),(4 + 1),(1 - 0)}, "Premontion: Piety Party Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v22, "APL.Priest.DiscExtras.PremRCount", {(163 - (92 + 71)),(67 - 27),(1 + 0)}, "Premontion: Piety Raid Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v22, "APL.Priest.DiscExtras.PremHP", {(0 + 0),(226 - (55 + 71)),(1791 - (573 + 1217))}, "Premontion: Piety HP", "Set the Premontion: Piety HP threshold.");
v6("Slider", v23, "APL.Priest.DiscHealing.FlashHealHP", {(0 + 0),(1039 - (714 + 225)),(1 - 0)}, "Flash Heal HP", "Set the Flash Heal HP threshold.");
v6("Slider", v23, "APL.Priest.DiscHealing.FlashAtoneIgnoreHP", {(0 - 0),(148 - (25 + 23)),(1887 - (927 + 959))}, "Flash Heal Atone Ignore HP", "Set the Flash Heal Atone Ignore HP threshold.");
v6("Slider", v23, "APL.Priest.DiscHealing.FlashHealSurgeHP", {(732 - (16 + 716)),(197 - (11 + 86)),(286 - (175 + 110))}, "Flash Heal Surge of Light HP", "Set the Flash Heal Surge of Light HP threshold.");
v6("Slider", v23, "APL.Priest.DiscHealing.PainSupHP", {(0 - 0),(279 - 179),(1062 - (810 + 251))}, "Pain Suppression HP", "Set the Pain Suppression HP threshold.");
v6("CheckButton", v23, "APL.Priest.DiscHealing.PainSupOnTank", "Pain Suppression on Tank Only", "Pain Suppression on Tank Only?");
v6("Slider", v23, "APL.Priest.DiscHealing.PenanceHP", {(0 + 0),(633 - (43 + 490)),(3 - 2)}, "Penance HP", "Set the Penance HP threshold.");
v6("Slider", v23, "APL.Priest.DiscHealing.PWSHP", {(0 + 0),(7 + 93),(406 - (255 + 150))}, "Power Word: Shield HP", "Set the Power Word: Shield  HP threshold.");
v6("Slider", v23, "APL.Priest.DiscHealing.PWSAtoneIgnoreHP", {(0 + 0),(322 - 222),(407 - (183 + 223))}, "Power Word: Shield Atone Ignore HP", "Set the Flash Heal Atone Ignore HP threshold.");
v6("Slider", v23, "APL.Priest.DiscHealing.PWSTankHP", {(0 + 0),(437 - (10 + 327)),(339 - (118 + 220))}, "Power Word: Shield on Tank HP", "Set the Power Word: Shield on Tank HP threshold.");
v6("Slider", v24, "APL.Priest.DiscAoE.EvangHP", {(449 - (108 + 341)),(422 - 322),(1 - 0)}, "Evangelism HP", "Set the Evangelism HP threshold.");
v6("Slider", v24, "APL.Priest.DiscAoE.EvangCount", {(0 + 0),(14 - 9),(1 + 0)}, "Evangelism Count", "Set the Evangelism Unit Count threshold to Cast.");
v6("Slider", v24, "APL.Priest.DiscAoE.VEHP", {(0 - 0),(1267 - (645 + 522)),(1 + 0)}, "Vampiric Embrace HP", "Set the Vampiric Embrace HP threshold.");
v6("Slider", v24, "APL.Priest.DiscAoE.VECount", {(0 - 0),(12 - 7),(506 - (351 + 154))}, "Vampiric Embrace Count", "Set the Vampiric Embrace Unit Count threshold to Cast.");
v6("Slider", v24, "APL.Priest.DiscAoE.PWBLHP", {(266 - (28 + 238)),(1659 - (1381 + 178)),(1 + 0)}, "PW: Barrier/Luminous  HP", "Set the Power Word : Barrier/Luminous  HP threshold.");
v6("Slider", v24, "APL.Priest.DiscAoE.PWBLCount", {(0 - 0),(475 - (381 + 89)),(1 + 0)}, "PW: Barrier/Luminous  Count", "Set the Power Word : Barrier/Luminous Unit Count threshold to Cast.");
v6("Slider", v24, "APL.Priest.DiscAoE.PWRHP", {(1156 - (1074 + 82)),(1884 - (214 + 1570)),(1 + 0)}, "PW: Radiance HP", "Set the Power Word: Radiance HP threshold.");
v6("Slider", v24, "APL.Priest.DiscAoE.PWRCount", {(0 + 0),(1731 - (1668 + 58)),(2 - 1)}, "PW: Radiance Count", "Set the Power Word: Radiance Unit Count threshold to Cast.");
v6("Slider", v24, "APL.Priest.DiscAoE.PWRAtoneHP", {(0 - 0),(19 + 81),(3 - 2)}, "PW: Radiance Atone Ignore HP", "Set the Power Word: Radiance Atone Ignore HP threshold.");
v6("Slider", v24, "APL.Priest.DiscAoE.PWRAtoneCount", {(1469 - (1269 + 200)),(820 - (98 + 717)),(1 - 0)}, "PW: Radiance Atone Ignore Count", "Set the Power Word: Radiance Atone Ignore Unit Count threshold to Cast.");
v6("Slider", v24, "APL.Priest.DiscAoE.HaloHP", {(0 + 0),(17 + 83),(2 - 1)}, "Halo HP", "Set the Halo HP threshold.");
v6("Slider", v24, "APL.Priest.DiscAoE.HaloCount", {(0 + 0),(5 + 0),(1 + 0)}, "Halo Count", "Set the Halo Unit Count threshold to Cast.");
v6("Slider", v25, "APL.Priest.DiscAoE.DSHP", {(0 - 0),(35 + 65),(1 + 0)}, "Divine Star HP", "Set the Divine Star HP threshold.");
v6("Slider", v25, "APL.Priest.DiscAoE.DSCount", {(326 - (192 + 134)),(3 + 2),(1 + 0)}, "Divine Star Count", "Set the Divine Star Unit Count threshold to Cast.");
v6("Slider", v25, "APL.Priest.DiscAoE.UPHP", {(551 - (83 + 468)),(466 - 366),(2 - 1)}, "Ultimate Pentience HP", "Set the Ultimate Pentience HP threshold.");
v6("Slider", v25, "APL.Priest.DiscAoE.UPCount", {(0 + 0),(2 + 3),(1 + 0)}, "Ultimate Pentience Count", "Set the Ultimate Pentience Unit Count threshold to Cast.");
v6("Slider", v26, "APL.Priest.DiscRaidHealing.FlashHealHP", {(1911 - (340 + 1571)),(1872 - (1733 + 39)),(1035 - (125 + 909))}, "Flash Heal HP", "Set the Flash Heal HP threshold.");
v6("Slider", v26, "APL.Priest.DiscRaidHealing.FlashAtoneIgnoreHP", {(0 + 0),(97 + 3),(237 - (46 + 190))}, "Flash Heal Atone Ignore HP", "Set the Flash Heal Atone Ignore HP threshold.");
v6("Slider", v26, "APL.Priest.DiscRaidHealing.FlashHealSurgeHP", {(0 + 0),(826 - (228 + 498)),(1 + 0)}, "Flash Heal Surge of Light HP", "Set the Flash Heal Surge of Light HP threshold.");
v6("Slider", v26, "APL.Priest.DiscRaidHealing.PainSupHP", {(0 - 0),(624 - (303 + 221)),(1 + 0)}, "Pain Suppression HP", "Set the Pain Suppression HP threshold.");
v6("CheckButton", v26, "APL.Priest.DiscRaidHealing.PainSupOnTank", "Pain Suppression on Tank Only", "Pain Suppression on Tank Only?");
v6("Slider", v26, "APL.Priest.DiscRaidHealing.PenanceHP", {(0 - 0),(249 - 149),(3 - 2)}, "Penance HP", "Set the Penance HP threshold.");
v6("Slider", v26, "APL.Priest.DiscRaidHealing.PWSHP", {(0 - 0),(1348 - (111 + 1137)),(2 - 1)}, "PW: Shield HP", "Set the Power Word: Shield  HP threshold.");
v6("Slider", v26, "APL.Priest.DiscRaidHealing.PWSAtoneIgnoreHP", {(523 - (423 + 100)),(276 - 176),(772 - (326 + 445))}, "PW: Shield Atone Ignore HP", "Set the Flash Heal Atone Ignore HP threshold.");
v6("Slider", v26, "APL.Priest.DiscRaidHealing.PWSTankHP", {(0 - 0),(811 - (530 + 181)),(33 - (19 + 13))}, "PW: Shield on Tank HP", "Set the Power Word: Shield on Tank HP threshold.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.EvangHP", {(0 - 0),(26 + 74),(1 - 0)}, "Evangelism HP", "Set the Evangelism HP threshold.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.EvangCount", {(0 - 0),(76 - 36),(2 - 1)}, "Evangelism Count", "Set the Evangelism Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.VEHP", {(0 + 0),(24 + 76),(1 + 0)}, "Vampiric Embrace HP", "Set the Vampiric Embrace HP threshold.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.VECount", {(1858 - (673 + 1185)),(128 - 88),(1 + 0)}, "Vampiric Embrace Count", "Set the Vampiric Embrace Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.RapHP", {(0 - 0),(199 - 99),(1881 - (446 + 1434))}, "Rapture HP", "Set the Rapture HP threshold.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.RapCount", {(0 - 0),(1971 - (609 + 1322)),(3 - 2)}, "Rapture Count", "Set the Rapture Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.PWBLHP", {(0 - 0),(363 - 263),(1 + 0)}, "PW: Barrier/Luminous  HP", "Set the Power Word : Barrier/Luminous  HP threshold.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.PWBLCount", {(0 + 0),(27 + 13),(1 + 0)}, "PW: Barrier/Luminous  Count", "Set the Power Word : Barrier/Luminous Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.PWRHP", {(0 + 0),(288 - 188),(1 + 0)}, "PW: Radiance HP", "Set the Power Word: Radiance HP threshold.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.PWRCount", {(0 + 0),(60 - 20),(668 - (89 + 578))}, "PW: Radiance Count", "Set the Power Word: Radiance Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.PWRAtoneHP", {(0 - 0),(14 + 86),(1 + 0)}, "PW: Radiance Atone Ignore HP", "Set the Power Word: Radiance Atone Ignore HP threshold.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.PWRAtoneCount", {(0 - 0),(882 - (497 + 345)),(1 + 0)}, "PW: Radiance Atone Ignore Count", "Set the Power Word: Radiance Atone Ignore Unit Count threshold to Cast.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.HaloHP", {(0 + 0),(5 + 95),(1 + 0)}, "Halo HP", "Set the Halo HP threshold.");
v6("Slider", v27, "APL.Priest.DiscRaidAoE.HaloCount", {(0 + 0),(17 + 23),(1 + 0)}, "Halo Count", "Set the Halo Unit Count threshold to Cast.");
v6("Slider", v28, "APL.Priest.DiscRaidAoE.DSHP", {(0 - 0),(896 - (588 + 208)),(1801 - (884 + 916))}, "Divine Star HP", "Set the Divine Star HP threshold.");
v6("Slider", v28, "APL.Priest.DiscRaidAoE.DSCount", {(0 + 0),(1929 - (1569 + 320)),(1 + 0)}, "Divine Star Count", "Set the Divine Star Unit Count threshold to Cast.");
v6("Slider", v28, "APL.Priest.DiscRaidAoE.UPHP", {(605 - (316 + 289)),(5 + 95),(426 - (360 + 65))}, "Ultimate Pentience HP", "Set the Ultimate Pentience HP threshold.");
v6("Slider", v28, "APL.Priest.DiscRaidAoE.UPCount", {(254 - (79 + 175)),(32 + 8),(1 - 0)}, "Ultimate Pentience Count", "Set the Ultimate Pentience Unit Count threshold to Cast.");
v8(v23, "APL.Priest.DiscHealing");
v8(v26, "APL.Priest.DiscRaidHealing");
v8(v21, "APL.Priest.Discipline");
v6("Slider", v30, "APL.Priest.Holy.ShadowfiendMana", {(181 - (92 + 89)),(52 + 48),(3 - 2)}, "Mana Percent for Fiend/Bender", "Set the Mana threshold.");
v6("Slider", v30, "APL.Priest.Holy.DesperatePrayerHP", {(0 - 0),(48 + 52),(1 + 0)}, "Desperate Prayer HP", "Set the Desperate Prayer HP threshold.");
v6("Slider", v30, "APL.Priest.Holy.FadeHP", {(1244 - (485 + 759)),(1289 - (442 + 747)),(947 - (88 + 858))}, "Fade HP", "Set the Fade HP threshold.");
v6("Slider", v30, "APL.Priest.Holy.RenewHP", {(0 + 0),(889 - (766 + 23)),(1 - 0)}, "Renew HP", "Set the Renew HP threshold.");
v6("Slider", v30, "APL.Priest.Holy.RenewMovingHP", {(0 - 0),(71 + 29),(1 + 0)}, "Renew while Moving HP", "Set the Renew while Moving HP threshold.");
v6("CheckButton", v30, "APL.Priest.Holy.RenewOnlyMoving", "Renew while moving only", "Renew while moving only");
v6("CheckButton", v30, "APL.Priest.Holy.VoidShiftTankOnly", "Void Shift On Tank Only", "Void Shift On Tank Only??");
v6("CheckButton", v30, "APL.Priest.Holy.SelectPI", "Select your Unit for PI? ", "Enable this if you'd like to select your unit for PI? ");
v6("Dropdown", v30, "APL.Priest.Holy.PIGroupUnit", v38, "PI Group Selection", "Unit to always keep PS on in Raid Only");
v6("Dropdown", v30, "APL.Priest.Holy.PIRaidUnit", v37, "PI Raid Selection", "Unit to always keep PS on in Group Only");
v6("CheckButton", v30, "APL.Priest.Holy.Movement", "Use Movement Abilities", "Use Movement Abilities such as Angelic Feather or Shadow Word Shield out of Combat.");
v6("CheckButton", v30, "APL.Priest.Holy.AttackOOC", "Attack with OOC", "Attack not in Combat?");
v6("Slider", v32, "APL.Priest.HolyHealing.HealHP", {(913 - (910 + 3)),(1784 - (1466 + 218)),(1149 - (556 + 592))}, "Heal HP", "Set the Heal HP threshold.");
v6("Slider", v32, "APL.Priest.HolyHealing.FlashHealHP", {(808 - (329 + 479)),(343 - 243),(1 + 0)}, "Flash Heal HP", "Set the Flash Heal HP threshold.");
v6("Slider", v32, "APL.Priest.HolyHealing.FlashHealSurge1HP", {(0 + 0),(1489 - (135 + 1254)),(4 - 3)}, "Flash Heal with 1 Stack of Surge of Light HP", "Set the Flash Heal with 1 Stack of Surge of Light HP threshold.");
v6("Slider", v32, "APL.Priest.HolyHealing.FlashHealSurge2HP", {(1527 - (389 + 1138)),(95 + 5),(1 + 0)}, "Flash Heal with 2 Stack of Surge of Light HP", "Set the Flash Heal with 2 Stack of Surge of Light HP threshold.");
v6("Slider", v32, "APL.Priest.HolyHealing.HolyWordSerenityHP", {(0 - 0),(1564 - (157 + 1307)),(2 - 1)}, "Holy Word: Serenity HP", "Set the Holy Word: Serenity HP threshold.");
v6("Slider", v32, "APL.Priest.HolyHealing.GSHP", {(0 - 0),(247 - 147),(1 + 0)}, "Guardian Spirit HP", "Set the Guardian Spirit HP threshold.");
v6("CheckButton", v32, "APL.Priest.HolyHealing.GSTank", "Guardian Spirit On Tank Only", "Guardian Spirit on Tank Only?");
v6("Slider", v32, "APL.Priest.HolyHealing.DWHP", {(0 + 0),(404 - (300 + 4)),(2 - 1)}, "Divine Word HP", "Set the Divine Word HP threshold.");
v6("Slider", v33, "APL.Priest.HolyAoE.CoHHP", {(0 + 0),(58 + 42),(1 + 0)}, "Circle Of Healing HP", "Set the Circle of Healing HP threshold.");
v6("Slider", v33, "APL.Priest.HolyAoE.CoHCount", {(0 + 0),(11 - 6),(694 - (627 + 66))}, "Circle Of Healing Count", "Set the Circle of Healing Unit Count threshold to Cast.");
v6("CheckButton", v33, "APL.Priest.HolyAoE.CoHOnlyMoving", "COH while moving only", "Circle of Healing while moving only");
v6("Slider", v33, "APL.Priest.HolyAoE.DHHP", {(602 - (512 + 90)),(817 - (373 + 344)),(1 + 0)}, "Divine Hymn HP", "Set the Divine Hymn HP threshold.");
v6("Slider", v33, "APL.Priest.HolyAoE.DHCount", {(0 - 0),(4 + 1),(1 + 0)}, "Divine Hymn Count", "Set the Divine Hymn Unit Count threshold to Cast.");
v6("Slider", v33, "APL.Priest.HolyAoE.DSHP", {(1259 - (233 + 1026)),(52 + 48),(1 + 0)}, "Divine Star HP", "Set the Divine Star HP threshold.");
v6("Slider", v33, "APL.Priest.HolyAoE.DSCount", {(221 - (55 + 166)),(1 + 4),(298 - (36 + 261))}, "Divine Star Count", "Set the Divine Star Unit Count threshold to Cast.");
v6("Slider", v33, "APL.Priest.HolyAoE.HaloHP", {(1368 - (34 + 1334)),(78 + 22),(22 - (20 + 1))}, "Halo HP", "Set the Halo HP threshold.");
v6("Slider", v33, "APL.Priest.HolyAoE.HaloCount", {(319 - (134 + 185)),(690 - (314 + 371)),(969 - (478 + 490))}, "Halo Count", "Set the Halo Unit Count threshold to Cast.");
v6("Slider", v33, "APL.Priest.HolyAoE.HolyNovaHP", {(1172 - (786 + 386)),(1479 - (1055 + 324)),(1 + 0)}, "Holy Nova HP", "Set the Halo HP threshold for when at 20 Stacks of Rahspody if talented");
v6("Slider", v33, "APL.Priest.HolyAoE.HolyNovaCount", {(0 - 0),(14 - 9),(1 + 0)}, "Holy Nova Count", "Set the Halo Count threshold for when at 20 Stacks of Rahspody if talented");
v6("Slider", v33, "APL.Priest.HolyAoE.SalvHP", {(0 - 0),(255 - 155),(2 - 1)}, "Holy Word: Savlation HP", "Set the Holy Word: Savlation HP threshold.");
v6("Slider", v33, "APL.Priest.HolyAoE.SalvCount", {(0 + 0),(8 - 3),(1269 - (1249 + 19))}, "Holy Word: Savlation Count", "Set the Holy Word: Savlation Unit Count threshold to Cast.");
v6("Slider", v33, "APL.Priest.HolyAoE.SancHP", {(0 - 0),(79 + 21),(1 + 0)}, "Holy Word: Sanctify HP", "Set the Holy Word: Sanctify HP threshold.");
v6("Slider", v33, "APL.Priest.HolyAoE.SancCount", {(0 + 0),(475 - (224 + 246)),(1 - 0)}, "Holy Word: Sanctify Count", "Set the Holy Word: Sanctify Unit Count threshold to Cast.");
v6("Slider", v33, "APL.Priest.HolyAoE.PoHHP", {(0 + 0),(198 - 98),(514 - (203 + 310))}, "Prayer of Healing HP", "Set the Prayer of Healing HP threshold.");
v6("Slider", v33, "APL.Priest.HolyAoE.PoHCount", {(0 + 0),(8 - 3),(865 - (196 + 668))}, "Prayer of Healing Count", "Set the Prayer of Healing Unit Count threshold to Cast.");
v6("Slider", v34, "APL.Priest.HolyRaidHealing.HealHP", {(0 - 0),(193 - (4 + 89)),(1 + 0)}, "Heal HP", "Set the Heal HP threshold.");
v6("Slider", v34, "APL.Priest.HolyRaidHealing.FlashHealHP", {(0 + 0),(1553 - (28 + 1425)),(1 + 0)}, "Flash Heal HP", "Set the Flash Heal HP threshold.");
v6("Slider", v34, "APL.Priest.HolyRaidHealing.FlashHealSurge1HP", {(0 - 0),(397 - (45 + 252)),(1 + 0)}, "Flash Heal with 1 Stack of Surge of Light HP", "Set the Flash Heal with 1 Stack of Surge of Light HP threshold.");
v6("Slider", v34, "APL.Priest.HolyRaidHealing.FlashHealSurge2HP", {(433 - (114 + 319)),(128 - 28),(1 - 0)}, "Flash Heal with 2 Stack of Surge of Light HP", "Set the Flash Heal with 2 Stack of Surge of Light HP threshold.");
v6("Slider", v34, "APL.Priest.HolyRaidHealing.HolyWordSerenityHP", {(1963 - (556 + 1407)),(565 - (170 + 295)),(1 + 0)}, "Holy Word: Serenity HP", "Set the Holy Word: Serenity HP threshold.");
v6("Slider", v34, "APL.Priest.HolyRaidHealing.GSHP", {(0 + 0),(57 + 43),(1 + 0)}, "Guardian Spirit HP", "Set the Guardian Spirit HP threshold.");
v6("CheckButton", v34, "APL.Priest.HolyRaidHealing.GSTank", "Guardian Spirit On Tank Only", "Guardian Spirit on Tank Only?");
v6("Slider", v34, "APL.Priest.HolyRaidHealing.DWHP", {(0 - 0),(305 - 205),(1781 - (389 + 1391))}, "Divine Word HP", "Set the Divine Word HP threshold.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.CoHHP", {(0 + 0),(1051 - (783 + 168)),(1 + 0)}, "Circle Of Healing HP", "Set the Circle of Healing HP threshold.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.CoHCount", {(0 - 0),(13 + 27),(1 + 0)}, "Circle Of Healing Count", "Set the Circle of Healing Unit Count threshold to Cast.");
v6("CheckButton", v35, "APL.Priest.HolyRaidAoE.CoHOnlyMoving", "CoH while moving only", "Circle of Healing while moving only");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.DHHP", {(0 + 0),(457 - 357),(1 - 0)}, "Divine Hymn HP", "Set the Divine Hymn HP threshold.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.DHCount", {(0 + 0),(1735 - (556 + 1139)),(1 + 0)}, "Divine Hymn Count", "Set the Divine Hymn Unit Count threshold to Cast.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.DSHP", {(169 - (28 + 141)),(123 - 23),(1318 - (486 + 831))}, "Divine Star HP", "Set the Divine Star HP threshold.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.DSCount", {(0 - 0),(126 - 86),(1 + 0)}, "Divine Star Count", "Set the Divine Star Unit Count threshold to Cast.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.HaloHP", {(0 - 0),(2044 - (1129 + 815)),(1751 - (1326 + 424))}, "Halo HP", "Set the Halo HP threshold.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.HaloCount", {(0 - 0),(811 - (720 + 51)),(1777 - (421 + 1355))}, "Halo Count", "Set the Halo Unit Count threshold to Cast.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.HolyNovaHP", {(0 + 0),(365 - 265),(440 - (397 + 42))}, "Holy Nova HP", "Set the Halo HP threshold for when at 20 Stacks of Rahspody if talented");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.HolyNovaCount", {(800 - (24 + 776)),(825 - (222 + 563)),(1 + 0)}, "Holy Nova Count", "Set the Halo Count threshold for when at 20 Stacks of Rahspody if talented");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.SalvHP", {(1798 - (690 + 1108)),(83 + 17),(1 + 0)}, "Holy Word: Savlation HP", "Set the Holy Word: Savlation HP threshold.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.SalvCount", {(0 + 0),(22 + 18),(1 + 0)}, "Holy Word: Savlation Count", "Set the Holy Word: Savlation Unit Count threshold to Cast.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.SancHP", {(0 - 0),(1826 - (1165 + 561)),(3 - 2)}, "Holy Word: Sanctify HP", "Set the Holy Word: Sanctify HP threshold.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.SancCount", {(479 - (341 + 138)),(82 - 42),(3 - 2)}, "Holy Word: Sanctify Count", "Set the Holy Word: Sanctify Unit Count threshold to Cast.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.PoHHP", {(881 - (581 + 300)),(237 - 137),(1236 - (1030 + 205))}, "Prayer of Healing HP", "Set the Prayer of Healing HP threshold.");
v6("Slider", v35, "APL.Priest.HolyRaidAoE.PoHCount", {(0 + 0),(90 - 50),(1 - 0)}, "Prayer of Healing Count", "Set the Prayer of Healing Unit Count threshold to Cast.");
v6("Dropdown", v31, "APL.Priest.HolyCooldowns.ApotheosisUsage", v12, "Apotheosis Usage", "How you would like to use this cooldown?");
v6("Slider", v31, "APL.Priest.HolyCooldowns.ApotheosisHP", {(0 + 0),(29 + 71),(1164 - (671 + 492))}, "Apotheosis HP", "Set the Apotheosis HP threshold.");
v6("Slider", v31, "APL.Priest.HolyCooldowns.ApotheosisRaidCount", {(1215 - (369 + 846)),(35 + 5),(1 + 0)}, "Apotheosis Raid Count", "Set the Apotheosis Count threshold to Cast.");
v6("Slider", v31, "APL.Priest.HolyCooldowns.ApotheosisPartyCount", {(203 - (11 + 192)),(180 - (135 + 40)),(1 + 0)}, "Apotheosis Party Count", "Set the Apotheosis Count threshold to Cast.");
v6("Dropdown", v31, "APL.Priest.HolyCooldowns.Trinket1Use", v12, "Trinket 1 Usage", "How would you like to use this Cooldown?");
v6("Dropdown", v31, "APL.Priest.HolyCooldowns.Trinket2Use", v12, "Trinket 2  Usage", "How would you like to use this Cooldown?");
v6("Slider", v31, "APL.Priest.HolyCooldowns.Trinket1HP", {(0 - 0),(278 - 178),(1414 - (1233 + 180))}, "Trinket 1 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("Slider", v31, "APL.Priest.HolyCooldowns.Trinket2HP", {(1421 - (107 + 1314)),(304 - 204),(1 - 0)}, "Trinket 2 HP", "Set the Avg HP percentage threshold of when you want to use this at");
v6("Slider", v31, "APL.Priest.HolyCooldowns.LightWellHP", {(1910 - (716 + 1194)),(11 + 89),(1 - 0)}, "LightWell HP", "Set the HP threshold.");
v6("Slider", v31, "APL.Priest.HolyCooldowns.LightWellPCount", {(0 - 0),(15 - 10),(434 - (279 + 154))}, "LightWell Party Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v31, "APL.Priest.HolyCooldowns.LightWellRCount", {(0 + 0),(22 + 18),(1 + 0)}, "LightWell Raid Count", "Set the Unit Count threshold to Cast.");
v6("CheckButton", v31, "APL.Priest.HolyCooldowns.PremUse", "Use Premontion", "Use Premontion With Logic? Untick if you would like to Manual!");
v6("Slider", v31, "APL.Priest.HolyCooldowns.PremPCount", {(0 - 0),(1 + 4),(4 - 3)}, "Premontion: Piety Party Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v31, "APL.Priest.HolyCooldowns.PremRCount", {(0 + 0),(1938 - (41 + 1857)),(2 - 1)}, "Premontion: Piety Raid Count", "Set the Unit Count threshold to Cast.");
v6("Slider", v31, "APL.Priest.HolyCooldowns.PremHP", {(1182 - (229 + 953)),(1679 - (874 + 705)),(1 + 0)}, "Premontion: Piety HP", "Set the Premontion: Piety HP threshold.");
v8(v31, "APL.Priest.HolyCooldowns");
v8(v32, "APL.Priest.HolyHealing");
v8(v33, "APL.Priest.HolyAoE");
v8(v34, "APL.Priest.HolyRaidHealing");
v8(v35, "APL.Priest.HolyRaidAoE");
v8(v30, "APL.Priest.Holy");
v10.APL.Priest.Shadow.Display = function()
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v28);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v33);
	v3.GUI.HidePanel(v31);
	v3.GUI.HidePanel(v32);
	v3.GUI.HidePanel(v9);
	v3.GUI.HidePanel(v34);
	v3.GUI.HidePanel(v35);
	v3.GUI.HidePanel(v29);
	v3.GUI.HidePanel(v36);
	v3.GUI.ShowPanel(v16);
	v3.GUI.ShowPanel(v17);
	v3.GUI.ShowPanel(v18);
	v3.GUI.ShowPanel(v19);
	v3.GUI.ShowPanel(v20);
end;
v10.APL.Priest.Discipline.Display = function()
	v3.GUI.ShowPanel(v21);
	v3.GUI.ShowPanel(v23);
	v3.GUI.ShowPanel(v24);
	v3.GUI.ShowPanel(v25);
	v3.GUI.ShowPanel(v26);
	v3.GUI.ShowPanel(v27);
	v3.GUI.ShowPanel(v28);
	v3.GUI.ShowPanel(v22);
	v3.GUI.HidePanel(v29);
	v3.GUI.ShowPanel(v36);
	v3.GUI.HidePanel(v30);
	v3.GUI.HidePanel(v33);
	v3.GUI.HidePanel(v31);
	v3.GUI.HidePanel(v32);
	v3.GUI.HidePanel(v9);
	v3.GUI.HidePanel(v34);
	v3.GUI.HidePanel(v35);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v20);
end;
v10.APL.Priest.Holy.Display = function()
	v3.GUI.HidePanel(v21);
	v3.GUI.HidePanel(v23);
	v3.GUI.HidePanel(v24);
	v3.GUI.HidePanel(v25);
	v3.GUI.HidePanel(v26);
	v3.GUI.HidePanel(v27);
	v3.GUI.HidePanel(v28);
	v3.GUI.ShowPanel(v30);
	v3.GUI.ShowPanel(v33);
	v3.GUI.ShowPanel(v31);
	v3.GUI.ShowPanel(v32);
	v3.GUI.ShowPanel(v34);
	v3.GUI.ShowPanel(v35);
	v3.GUI.HidePanel(v22);
	v3.GUI.HidePanel(v29);
	v3.GUI.ShowPanel(v36);
	v3.GUI.HidePanel(v9);
	v3.GUI.HidePanel(v16);
	v3.GUI.HidePanel(v17);
	v3.GUI.HidePanel(v18);
	v3.GUI.HidePanel(v19);
	v3.GUI.HidePanel(v20);
end;
