name: Auto Tag and Release

on:
  push:
    branches:
      - '*'

jobs:
  auto_tag_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "0")
          if [ "$LATEST_TAG" = "0" ]; then
            echo "::set-output name=tag::1"
          else
            NEW_TAG=$((LATEST_TAG + 1))
            echo "::set-output name=tag::$NEW_TAG"
          fi

      - name: Create new tag
        id: create_tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag ${{ steps.get_latest_tag.outputs.tag }}
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/medi8tor/Addons.git ${{ steps.get_latest_tag.outputs.tag }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: AscendedRotation-${{ steps.get_latest_tag.outputs.tag }}.zip
          exclusions: '*.git* *.pkgmeta *.svn* .editorconfig LICENSE README.md symlink.bat symlink.sh HeroRotation_ClassTemplate HeroRotation_ClassTemplate/*'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.tag }}
          release_name: AscendedRotation ${{ steps.get_latest_tag.outputs.tag }}
          body: |
            Changes: https://github.com/medi8tor/Addons/compare/${{ steps.get_latest_tag.outputs.oldtag }}...${{ steps.get_latest_tag.outputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./AscendedRotation-${{ steps.get_latest_tag.outputs.tag }}.zip
          asset_name: AscendedRotation-${{ steps.get_latest_tag.outputs.tag }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Release
        uses: BigWigsMods/packager@v1