name: Auto Tag

on:
  push:
    branches:
      - '*'

jobs:
  auto_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "0")
          if [ "$LATEST_TAG" = "0" ]; then
            echo "::set-output name=tag::1"
          else
            NEW_TAG=$((LATEST_TAG + 1))
            echo "::set-output name=tag::$NEW_TAG"
          fi

      - name: Create new tag
        id: create_tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag ${{ steps.get_latest_tag.outputs.tag }}
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/medi8tor/Addons.git ${{ steps.get_latest_tag.outputs.tag }}